import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { NextRequest, NextResponse } from "next/server";
import { getOrder, cancelOrderItem, getRefundEligibility } from "@/lib/musement";
import { notifyAdmin } from "@/lib/notify";

// ═══════════════════════════════════════════════════════════════
// GET  /api/bookings/:id/cancel   → refund eligibility check only
// POST /api/bookings/:id/cancel   → perform cancellation
//
// Per Musement Quality Check #10 the partner MUST pre-check the refund
// policy before attempting cancellation (a DELETE on a non-refundable
// item still stands as a charge). The GET form lets the UI render an
// informed confirmation modal; POST commits the cancel and flips the
// Supabase booking to "cancelled".
// ═══════════════════════════════════════════════════════════════

async function getAuthUser() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll();
        },
        setAll(cookiesToSet) {
          try {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options)
            );
          } catch {}
        },
      },
    }
  );
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return user;
}

function getAdminClient() {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { cookies: { getAll: () => [], setAll: () => {} } }
  );
}

async function loadBooking(id: string) {
  const admin = getAdminClient();
  const { data: booking, error } = await admin
    .from("bookings")
    .select("id, status, musement_order_id, musement_status, venue_name, number_of_guests")
    .eq("id", id)
    .single();
  if (error || !booking) return null;
  return booking as {
    id: string;
    status: string;
    musement_order_id: string | null;
    musement_status: string | null;
    venue_name: string;
    number_of_guests: number;
  };
}

// Mock orders (generated by confirm-order when no Musement credentials) are
// identified by the `mock-` prefix and skip the Musement API entirely.
const isMockOrder = (orderId: string | null) =>
  !orderId || orderId.startsWith("mock-");

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getAuthUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const booking = await loadBooking(id);
  if (!booking) return NextResponse.json({ error: "Booking not found" }, { status: 404 });

  if (isMockOrder(booking.musement_order_id)) {
    return NextResponse.json({
      ok: true,
      source: "mock",
      refundable: true,
      refundPercentage: 100,
      message: "Mock booking — can be cancelled locally without Musement.",
    });
  }

  // Real Musement order — fetch the first item uuid and check its refund policy.
  const order = await getOrder(booking.musement_order_id!);
  if (!order || order.tickets.length === 0) {
    return NextResponse.json(
      { error: "Could not fetch the Musement order to check refund eligibility." },
      { status: 502 }
    );
  }

  const itemId = order.tickets[0].ticketId;
  const eligibility = await getRefundEligibility(booking.musement_order_id!, itemId);

  if (!eligibility.ok) {
    return NextResponse.json({
      ok: true,
      source: "musement",
      refundable: false,
      code: eligibility.reason,
      message:
        eligibility.reason === "NO_REFUND_POLICIES"
          ? "This activity has no refund policy. The charge will stand if cancelled."
          : eligibility.reason === "REFUND_WINDOW_CLOSED"
          ? "The refund window has closed for this booking."
          : `Musement API error: ${eligibility.detail || "unknown"}`,
    });
  }

  return NextResponse.json({
    ok: true,
    source: "musement",
    refundable: eligibility.refunded,
    refundPercentage: eligibility.policy?.refundPercentage,
    applicableUntil: eligibility.policy?.applicableUntil,
    remainingTime: eligibility.policy?.remainingTime,
  });
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getAuthUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const body = await request.json().catch(() => ({}));
  const reason: string = body.reason || "CANCELLED-BY-CUSTOMER";

  const booking = await loadBooking(id);
  if (!booking) return NextResponse.json({ error: "Booking not found" }, { status: 404 });

  if (booking.status === "cancelled") {
    return NextResponse.json({ ok: true, alreadyCancelled: true });
  }

  const admin = getAdminClient();

  // Mock order — skip Musement, just flip local state.
  if (isMockOrder(booking.musement_order_id)) {
    await admin.from("bookings").update({ status: "cancelled" }).eq("id", id);
    return NextResponse.json({ ok: true, source: "mock", refunded: false });
  }

  // Real Musement order — fetch all items and cancel each with refund-policy gating.
  const order = await getOrder(booking.musement_order_id!);
  if (!order || order.tickets.length === 0) {
    return NextResponse.json(
      { error: "Could not fetch the Musement order for cancellation." },
      { status: 502 }
    );
  }

  const results: Array<{
    itemId: string;
    ok: boolean;
    reason?: string;
    detail?: string;
    refunded?: boolean;
  }> = [];
  for (const t of order.tickets) {
    const r = await cancelOrderItem(booking.musement_order_id!, t.ticketId, reason);
    if (r.ok) {
      results.push({ itemId: t.ticketId, ok: true, refunded: r.refunded });
    } else {
      results.push({ itemId: t.ticketId, ok: false, reason: r.reason, detail: r.detail });
    }
  }

  const anyFailure = results.some((r) => !r.ok);
  if (anyFailure) {
    return NextResponse.json(
      { error: "One or more items could not be cancelled.", results },
      { status: 409 }
    );
  }

  await admin.from("bookings").update({ status: "cancelled" }).eq("id", id);

  notifyAdmin(
    `❌ Booking cancelled\n\n` +
      `📍 ${booking.venue_name}\n` +
      `👥 ${booking.number_of_guests} guests\n` +
      `🔖 Musement order: ${booking.musement_order_id}\n` +
      `Reason: ${reason}`
  );

  return NextResponse.json({
    ok: true,
    source: "musement",
    refunded: results.some((r) => r.refunded),
    items: results,
  });
}
