import type { CityData } from "./cities-data";

export const austrianCities: CityData[] = [
  {
    slug: "vienna",
    name: "Vienna",
    province: "Vienna",
    country: "Austria",
    flag: "\u{1F1E6}\u{1F1F9}",
    experiences: "4,800+",
    categories: 13,
    viatorDestId: 454,
    tagline: "Imperial elegance — Mozart, Klimt & the world's finest coffee houses",
    description:
      "Vienna is the imperial jewel of Central Europe — a city of grand palaces, world-class opera, legendary coffee houses, and artistic genius from Mozart to Klimt. Consistently ranked the world's most liveable city, TicketMatch.ai provides B2B access to 4,800+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Schönbrunn Palace — The magnificent 1,441-room Habsburg summer residence with gardens and zoo (UNESCO)",
      "St. Stephen's Cathedral — Gothic masterpiece with its iconic mosaic roof and 343-step south tower",
      "Hofburg Palace — The imperial winter residence housing the Spanish Riding School and Sisi Museum",
      "Belvedere Palace — Baroque palace complex home to Klimt's iconic The Kiss",
      "Vienna State Opera — One of the world's premier opera houses with 300+ performances per year",
      "Kunsthistorisches Museum — Imperial art collection rivaling the Louvre with Bruegel, Vermeer, and Raphael",
      "Naschmarkt — Vienna's most popular market with 120+ stalls of food, spices, and restaurants",
      "Prater — Historic amusement park with the iconic Giant Ferris Wheel (Riesenrad) from 1897",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "200+", description: "Kunsthistorisches Museum, Belvedere (The Kiss), Albertina, Leopold Museum, Natural History Museum, and 150+ more at B2B rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "280+", description: "Imperial palace tours, Mozart walks, Ringstraße tram rides, underground Vienna, and Heurigen wine tavern visits." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "100+", description: "Schönbrunn Palace, Hofburg, St. Stephen's Cathedral, Prater Ferris Wheel, Spanish Riding School, and Vienna Zoo." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "120+", description: "Coffee house culture tours, Sachertorte tastings, wine tavern (Heurigen) visits, Naschmarkt walks, and Wiener Schnitzel experiences." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "100+", description: "Vienna State Opera, Musikverein concerts, Klimt trail, Mozart house, and waltz evening experiences." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "Wachau Valley (wine & Danube), Salzburg, Bratislava, Hallstatt, and Melk Abbey." },
    ],
    geoLat: 48.2082,
    geoLon: 16.3738,
    faq: [
      { q: "What group experiences are available in Vienna?", a: "TicketMatch.ai provides access to 4,800+ experiences: Schönbrunn Palace, Belvedere (Klimt), opera performances, coffee house tours, Wachau Valley trips, and more — all at exclusive B2B group rates." },
      { q: "How do I book group tickets for Schönbrunn Palace?", a: "Through TicketMatch.ai, book group Schönbrunn tickets including Grand Tour (40 rooms), Imperial Tour, garden access, zoo visits, and combined Schönbrunn + Hofburg packages at wholesale B2B rates." },
      { q: "What musical experiences are available for groups?", a: "Vienna is the world capital of classical music. TicketMatch.ai offers group Vienna State Opera tickets, Musikverein concerts, Mozart dinners, Strauss waltz evenings, and choir performances at B2B rates." },
      { q: "Can I book Wachau Valley wine tours for groups?", a: "Yes. The UNESCO Wachau Valley is 1 hour from Vienna. TicketMatch.ai offers group Danube cruises, vineyard tastings, Melk Abbey visits, and combined river + wine tours at B2B rates." },
      { q: "Is Vienna good for group travel?", a: "Outstanding. Vienna has Europe's best public transport, is extremely walkable, and offers world-class culture at every turn. TicketMatch.ai helps plan multi-day Vienna + Austria group itineraries." },
    ],
  },
  {
    slug: "salzburg",
    name: "Salzburg",
    province: "Salzburg",
    country: "Austria",
    flag: "\u{1F1E6}\u{1F1F9}",
    experiences: "2,400+",
    categories: 10,
    viatorDestId: 451,
    tagline: "Mozart's birthplace — Sound of Music, baroque splendor & Alpine drama",
    description:
      "Salzburg is a fairy-tale city where baroque architecture meets dramatic Alpine scenery. As Mozart's birthplace and the filming location of The Sound of Music, it's one of Austria's most beloved destinations. TicketMatch.ai provides B2B access to 2,400+ group experiences at exclusive rates.",
    highlights: [
      "Hohensalzburg Fortress — One of Europe's largest and best-preserved medieval castles, towering over the old town",
      "Mozart's Birthplace — The house on Getreidegasse where Wolfgang Amadeus Mozart was born in 1756",
      "Mirabell Palace & Gardens — Baroque palace with the famous Do-Re-Mi steps from The Sound of Music",
      "Salzburg Cathedral — Impressive 17th-century baroque cathedral where Mozart was baptized",
      "Getreidegasse — The charming main shopping street with wrought-iron guild signs and Mozart's birthplace",
      "Hellbrunn Palace — Summer palace famous for its trick fountains and water gardens since 1619",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "140+", description: "Sound of Music tours, Mozart walks, old town guided tours, fortress visits, and Salzburg by night." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "50+", description: "Hohensalzburg Fortress, Mozart's Birthplace, Mirabell Gardens, Hellbrunn trick fountains, and Salzburg Zoo." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "100+", description: "Hallstatt, Eagle's Nest (Berchtesgaden), Salzburg Lake District, Ice Caves, and Sound of Music filming locations." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "50+", description: "Salzburger Nockerl tastings, Mozart Kugel chocolate, beer garden visits, Austrian cooking classes, and Stiegl brewery tours." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "30+", description: "Mozart's Birthplace, Mozart's Residence, Salzburg Museum, Museum der Moderne, and Hangar-7 (Red Bull)." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "40+", description: "Salzburg Festival events, Mozart concerts in historic venues, marionette theatre, and cathedral organ concerts." },
    ],
    geoLat: 47.8095,
    geoLon: 13.0550,
    faq: [
      { q: "What group experiences are available in Salzburg?", a: "TicketMatch.ai provides access to 2,400+ experiences: Sound of Music tours, Mozart sites, Hallstatt day trips, fortress visits, and more — all at exclusive B2B group rates." },
      { q: "What Sound of Music tours are available?", a: "TicketMatch.ai offers group Sound of Music tours covering all filming locations: Mirabell Gardens, Leopoldskron Palace, Mondsee Church, and the Lake District — by bus, bike, or on foot at B2B rates." },
      { q: "Can I book Hallstatt day trips for groups?", a: "Yes. Hallstatt is 1.5 hours from Salzburg. TicketMatch.ai offers group day trips including the Skywalk, salt mine, bone house, and combined Hallstatt + Lake District tours at B2B rates." },
      { q: "Is Salzburg good for group travel?", a: "Excellent. Salzburg's old town is compact and UNESCO-listed, with world-class culture and easy access to the Austrian Alps and lake district. TicketMatch.ai helps plan Salzburg + Alpine group itineraries." },
    ],
  },
  {
    slug: "innsbruck",
    name: "Innsbruck",
    province: "Tyrol",
    country: "Austria",
    flag: "\u{1F1E6}\u{1F1F9}",
    experiences: "1,400+",
    categories: 9,
    viatorDestId: 5173,
    tagline: "Capital of the Alps — imperial history meets world-class mountains",
    description:
      "Innsbruck is the capital of Tyrol, spectacularly set in the heart of the Alps where imperial Habsburg history meets outdoor adventure. Two-time Winter Olympics host with the iconic Golden Roof, TicketMatch.ai provides B2B access to 1,400+ group experiences at exclusive rates.",
    highlights: [
      "Golden Roof (Goldenes Dachl) — The iconic balcony with 2,657 gilded copper tiles, Innsbruck's landmark since 1500",
      "Nordkette Cable Car — From the city center to 2,334m Alpine peaks in 20 minutes with stunning views",
      "Hofburg Palace — The imperial residence of the Habsburgs in Tyrol with Giant's Hall and chapel",
      "Bergisel Ski Jump — Zaha Hadid-designed Olympic ski jump with panoramic café and viewing platform",
      "Swarovski Crystal Worlds — Dazzling crystal art installation and museum in nearby Wattens",
      "Altstadt (Old Town) — Medieval old town with colorful baroque facades along the Inn river",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "70+", description: "Old town walks, Golden Roof tours, Nordkette cable car, Alpine panorama tours, and Innsbruck by night." },
      { slug: "outdoor", name: "Outdoor & Alps", icon: "\u{1F3D4}\u{FE0F}", count: "60+", description: "Nordkette hiking, Alpine coaster rides, rafting on the Inn, skiing, paragliding, and mountain biking." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Nordkette, Swarovski Crystal Worlds, Bergisel ski jump, Hofburg Palace, and Alpenzoo." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "50+", description: "Swarovski Crystal Worlds, Stubai Glacier, Brenner Pass to Italy, Zugspitze, and Neuschwanstein Castle." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "20+", description: "Tyrolean State Museum, Hofburg, Ambras Castle, Bell Museum (Grassmayr), and Bergisel museum." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "30+", description: "Tyrolean dumpling making, apple strudel workshops, craft beer tastings, mountain hut dining, and market walks." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "15+", description: "Tyrolean evening shows, folk music performances, Ambras Castle art collection, and Christmas market events." },
      { slug: "river-cruises", name: "Cable Cars", icon: "\u{1F6A1}", count: "10+", description: "Nordkette Bahnen, Hungerburgbahn, Patscherkofel, and Stubai Glacier lifts." },
      { slug: "winter-sports", name: "Winter Sports", icon: "\u{26F7}\u{FE0F}", count: "20+", description: "Ski passes, snowboard lessons, cross-country skiing, ski jumping tours, and après-ski experiences." },
    ],
    geoLat: 47.2692,
    geoLon: 11.4041,
    faq: [
      { q: "What group experiences are available in Innsbruck?", a: "TicketMatch.ai provides access to 1,400+ experiences: Nordkette cable car, Swarovski Crystal Worlds, Alpine adventures, old town tours, and more — all at exclusive B2B group rates." },
      { q: "Can groups visit the Alps from Innsbruck?", a: "Absolutely. The Nordkette takes you from city center to 2,334m in 20 minutes. TicketMatch.ai offers group Alpine experiences: hiking, paragliding, glacier visits, and mountain hut lunches at B2B rates." },
      { q: "What is Swarovski Crystal Worlds?", a: "A dazzling crystal art experience in Wattens, 20 minutes from Innsbruck. TicketMatch.ai offers group tickets with transport and combined Swarovski + Innsbruck city packages at B2B rates." },
      { q: "Is Innsbruck good for group travel?", a: "Perfect for groups that want culture + nature. The compact old town is walkable, and the Alps are literally at your doorstep. TicketMatch.ai helps plan Tyrolean group itineraries year-round." },
    ],
  },
  {
    slug: "hallstatt",
    name: "Hallstatt",
    province: "Upper Austria",
    country: "Austria",
    flag: "\u{1F1E6}\u{1F1F9}",
    experiences: "600+",
    categories: 7,
    viatorDestId: 25793,
    tagline: "The world's most Instagrammed village — Alpine lake perfection",
    description:
      "Hallstatt is a UNESCO World Heritage lakeside village so beautiful it was cloned in China. Nestled between towering Alps and a crystal-clear lake, with 7,000 years of salt mining history, TicketMatch.ai provides B2B access to 600+ group experiences at exclusive rates.",
    highlights: [
      "Hallstatt Skywalk — Viewing platform 350m above the lake with breathtaking panoramic views",
      "Salt Mine (Salzwelten) — The world's oldest salt mine with underground slides and a subterranean salt lake",
      "Hallstatt Ossuary (Bone House) — Chapel housing 1,200+ painted skulls, a unique Alpine tradition",
      "Lake Hallstatt — Crystal-clear Alpine lake surrounded by mountains, perfect for boat tours",
      "Market Square — The iconic lakeside square with pastel houses and the postcard-perfect view",
      "Dachstein Ice Cave — Spectacular ice formations inside the mountain with the Giant Ice Curtain",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "30+", description: "Village walking tours, Skywalk visits, salt mine tours, bone house visits, and photography tours." },
      { slug: "outdoor", name: "Outdoor & Nature", icon: "\u{1F3D4}\u{FE0F}", count: "25+", description: "Lake boat trips, Skywalk, hiking trails, Dachstein Five Fingers viewpoint, and Alpine swimming." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "15+", description: "Salzwelten salt mine, Skywalk, Dachstein Ice Cave, Five Fingers, and bone house chapel." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "20+", description: "From Salzburg (1.5h), Vienna (3.5h), combined with Dachstein, and Salzkammergut lake district tours." },
      { slug: "river-cruises", name: "Lake Cruises", icon: "\u{1F6A2}", count: "10+", description: "Lake Hallstatt ferry crossings, scenic boat tours, and private group boat charters." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "5+", description: "Hallstatt Museum (World Heritage), bone house, salt mine exhibition, and prehistoric archaeology." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "10+", description: "Lakeside dining, Austrian pastry tastings, mountain hut lunches, and local fish specialties." },
    ],
    geoLat: 47.5622,
    geoLon: 13.6493,
    faq: [
      { q: "What group experiences are available in Hallstatt?", a: "TicketMatch.ai provides access to 600+ experiences: Skywalk, salt mine tours, lake boat trips, Dachstein Ice Cave, and more — all at exclusive B2B group rates." },
      { q: "Can groups visit Hallstatt as a day trip?", a: "Yes. Hallstatt is 1.5 hours from Salzburg and 3.5 hours from Vienna. TicketMatch.ai offers group day trips with transport, guided tours, and combined Hallstatt + Dachstein packages at B2B rates." },
      { q: "Is Hallstatt suitable for large groups?", a: "Hallstatt is small — medium groups (max 20-25) work best. TicketMatch.ai helps plan staggered visits, off-peak timing, and combined lake district itineraries to manage group size." },
      { q: "What is the Hallstatt salt mine?", a: "The world's oldest salt mine (7,000 years). Groups ride underground slides, cross a salt lake on a raft, and explore ancient mining tunnels. TicketMatch.ai offers group tickets at B2B rates." },
    ],
  },
];
