import type { CityData } from "./cities-data";

export const belgianCities: CityData[] = [
  {
    slug: "brussels",
    name: "Brussels",
    province: "Brussels-Capital",
    country: "Belgium",
    flag: "\u{1F1E7}\u{1F1EA}",
    experiences: "3,200+",
    categories: 11,
    viatorDestId: 458,
    tagline: "Heart of Europe — EU capital, Art Nouveau & world-class chocolate",
    description:
      "Brussels is the vibrant capital of Belgium and the European Union, where stunning Grand-Place architecture meets world-famous chocolate, waffles, and beer culture. From Art Nouveau masterpieces to the Atomium, TicketMatch.ai provides B2B access to 3,200+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Grand-Place — UNESCO World Heritage square surrounded by opulent guildhalls and the Gothic Town Hall",
      "Atomium — The iconic 102-meter structure of nine connected spheres, built for the 1958 World Expo",
      "Manneken Pis — Brussels' cheeky 61cm bronze statue, dressed in different costumes 130+ times a year",
      "Royal Museums of Fine Arts — Four museums in one with Bruegel, Magritte, and Old Masters collections",
      "European Quarter — The EU Parliament, European Commission, and Parlamentarium visitor center",
      "Mini-Europe — Miniature park with 350+ reproductions of Europe's most famous landmarks at 1:25 scale",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "150+", description: "Grand-Place walks, Art Nouveau tours, EU Quarter visits, comic strip murals, and Brussels by night." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "130+", description: "Chocolate workshops, Belgian beer tastings, waffle tours, frites crawls, and Delirium Café visits." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "50+", description: "Atomium, Mini-Europe, Manneken Pis, Royal Palace, Parlamentarium, and Autoworld." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "60+", description: "Magritte Museum, Royal Museums of Fine Arts, Musical Instruments Museum (MIM), Belgian Comic Strip Center, and Train World." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "Bruges, Ghent, Antwerp, Waterloo battlefield, Luxembourg, and Bastogne WWII memorial." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "40+", description: "Art Nouveau walks (Horta Museum), comic strip mural tours, Magritte trail, and Royal Theatre visits." },
    ],
    geoLat: 50.8503,
    geoLon: 4.3517,
    faq: [
      { q: "What group experiences are available in Brussels?", a: "TicketMatch.ai provides access to 3,200+ experiences: Grand-Place tours, chocolate workshops, Belgian beer tastings, Bruges day trips, EU Quarter visits, and more — all at exclusive B2B group rates." },
      { q: "Can I book chocolate and beer experiences for groups?", a: "Absolutely! Brussels is the world capital of chocolate and beer. TicketMatch.ai offers group chocolate-making workshops, praline tastings, brewery tours, beer pairing dinners, and combined chocolate + beer tours at B2B rates." },
      { q: "Can I combine Brussels with Bruges and Ghent?", a: "Yes. Bruges is 1 hour and Ghent 30 minutes from Brussels. TicketMatch.ai offers combined day trips and multi-city Belgian packages at B2B rates." },
      { q: "Is Brussels good for group travel?", a: "Excellent. Brussels is compact, multilingual (French/Dutch/English), has great rail connections, and is central to Belgium's top cities. TicketMatch.ai helps plan multi-city Belgian group itineraries." },
    ],
  },
  {
    slug: "bruges",
    name: "Bruges",
    province: "West Flanders",
    country: "Belgium",
    flag: "\u{1F1E7}\u{1F1EA}",
    experiences: "1,800+",
    categories: 9,
    viatorDestId: 5073,
    tagline: "The Venice of the North — medieval canals, lace & Belgian chocolate",
    description:
      "Bruges is a perfectly preserved medieval gem — a UNESCO World Heritage city of winding canals, cobblestone streets, and Gothic architecture. Famous for chocolate, beer, and lace, TicketMatch.ai provides B2B access to 1,800+ group experiences at exclusive rates.",
    highlights: [
      "Markt Square — The stunning central square with the 83-meter Belfry tower and colorful guild houses",
      "Belfry of Bruges — The iconic medieval bell tower with 366 steps and panoramic city views",
      "Canal Boat Tours — Glide through Bruges' UNESCO canals past medieval bridges and hidden gardens",
      "Basilica of the Holy Blood — 12th-century basilica housing a relic said to contain Christ's blood",
      "Groeningemuseum — Flemish Primitive masterpieces including works by Jan van Eyck and Hans Memling",
      "Minnewater (Lake of Love) — Romantic park and lake at the south end of the old town",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Medieval walking tours, canal boat rides, horse-drawn carriage tours, Belfry climbs, and hidden corners of Bruges." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "70+", description: "Chocolate tastings, Belgian beer tours (De Halve Maan brewery), waffle workshops, and Flemish cuisine experiences." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Belfry tower, Basilica of Holy Blood, Begijnhof, Minnewater, and Church of Our Lady (Michelangelo's Madonna)." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "20+", description: "Groeningemuseum, Choco-Story chocolate museum, Diamond Museum, Lace Centre, and Historium Bruges." },
      { slug: "river-cruises", name: "Canal Cruises", icon: "\u{1F6A2}", count: "15+", description: "Classic canal boat tours, private group boats, sunset cruises, and photography boat tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "30+", description: "Ghent, Brussels, Ypres WWI battlefields, Belgian coast (Ostend), and Flanders Fields." },
    ],
    geoLat: 51.2094,
    geoLon: 3.2247,
    faq: [
      { q: "What group experiences are available in Bruges?", a: "TicketMatch.ai provides access to 1,800+ experiences: canal boat tours, chocolate workshops, Belfry climbs, brewery visits, and more — all at exclusive B2B group rates." },
      { q: "What chocolate experiences are available in Bruges?", a: "Bruges has 50+ chocolate shops. TicketMatch.ai offers group chocolate-making workshops, Choco-Story museum, praline tastings, and combined chocolate + beer tours at B2B rates." },
      { q: "Can groups take canal boat tours?", a: "Yes. Canal boats are Bruges' signature experience. TicketMatch.ai offers group boat tours, private charters, and combined boat + walking packages at B2B rates." },
      { q: "Is Bruges a good day trip destination?", a: "Perfect. Bruges is 1 hour from Brussels and 30 minutes from Ghent by train. TicketMatch.ai offers Bruges-only and combined Bruges + Ghent group packages at B2B rates." },
    ],
  },
  {
    slug: "ghent",
    name: "Ghent",
    province: "East Flanders",
    country: "Belgium",
    flag: "\u{1F1E7}\u{1F1EA}",
    experiences: "1,200+",
    categories: 8,
    viatorDestId: 5074,
    tagline: "Belgium's hidden gem — medieval grandeur without the crowds",
    description:
      "Ghent is Belgium's best-kept secret — a vibrant university city with a stunning medieval skyline, world-famous altarpiece, and thriving food scene, all without the tourist crowds of Bruges. TicketMatch.ai provides B2B access to 1,200+ group experiences at exclusive rates.",
    highlights: [
      "St. Bavo's Cathedral & Ghent Altarpiece — Home to the Van Eyck brothers' Adoration of the Mystic Lamb, one of the world's most important artworks",
      "Gravensteen (Castle of the Counts) — Imposing 12th-century medieval castle in the heart of the city",
      "Graslei & Korenlei — Stunning medieval guild houses lining both banks of the River Leie",
      "St. Michael's Bridge — The viewpoint with Ghent's famous three-tower skyline panorama",
      "STAM City Museum — Ghent's story told through an abbey, monastery, and modern extension",
      "Patershol — Medieval neighborhood of narrow alleys, now filled with restaurants and bars",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "60+", description: "Medieval city walks, Ghent Altarpiece tours, canal boat tours, street art walks, and Gravensteen castle visits." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "50+", description: "Flemish food tours, cuberdons (Ghent nose candy), craft beer tastings, waterzooi cooking, and chocolate walks." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "Gravensteen castle, St. Bavo's Cathedral, Belfry, St. Nicholas' Church, and Design Museum." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "20+", description: "STAM City Museum, MSK Fine Arts, SMAK contemporary art, Design Museum, and Dr. Guislain psychiatry museum." },
      { slug: "river-cruises", name: "Canal Cruises", icon: "\u{1F6A2}", count: "10+", description: "Graslei canal tours, kayaking on the Leie, and private group boat trips." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "20+", description: "Bruges, Brussels, Ypres WWI sites, Flanders Fields, and Oudenaarde (Tour of Flanders)." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "15+", description: "Van Eyck trail, street art tours, Ghent Festival events, and Flemish Primitive art walks." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "10+", description: "Canal kayaking, Blaarmeersen recreational park, Coupure park walks, and cycling along the Leie." },
    ],
    geoLat: 51.0543,
    geoLon: 3.7174,
    faq: [
      { q: "What group experiences are available in Ghent?", a: "TicketMatch.ai provides access to 1,200+ experiences: Ghent Altarpiece tours, Gravensteen castle, canal boats, food tours, and more — all at exclusive B2B group rates." },
      { q: "What is the Ghent Altarpiece?", a: "The Adoration of the Mystic Lamb by the Van Eyck brothers (1432) is one of the most important artworks in history. TicketMatch.ai offers group visits to St. Bavo's Cathedral with dedicated altarpiece tours at B2B rates." },
      { q: "How does Ghent compare to Bruges?", a: "Ghent is larger, livelier (university city), less touristy, and has a more authentic local vibe. TicketMatch.ai offers both cities as separate or combined group experiences at B2B rates." },
      { q: "Is Ghent good for group travel?", a: "Excellent. Ghent is compact, walkable, affordable, and only 30 minutes from Bruges and Brussels. TicketMatch.ai helps plan combined Belgian city group itineraries." },
    ],
  },
  {
    slug: "antwerp",
    name: "Antwerp",
    province: "Antwerp",
    country: "Belgium",
    flag: "\u{1F1E7}\u{1F1EA}",
    experiences: "1,500+",
    categories: 9,
    viatorDestId: 5072,
    tagline: "Diamond capital — Rubens, fashion & the world's coolest port city",
    description:
      "Antwerp is Belgium's coolest city — the diamond capital of the world, birthplace of Rubens, a fashion powerhouse, and home to Europe's second-largest port. With a stunning cathedral and vibrant nightlife, TicketMatch.ai provides B2B access to 1,500+ group experiences at exclusive rates.",
    highlights: [
      "Cathedral of Our Lady — Gothic masterpiece housing four Rubens altarpieces, Antwerp's tallest building",
      "MAS (Museum aan de Stroom) — Striking red sandstone tower museum on the waterfront with panoramic roof terrace",
      "Diamond District — The world's diamond trading hub since the 15th century, processing 84% of rough diamonds",
      "Central Station — Regularly voted the world's most beautiful railway station, a 1905 masterpiece",
      "Rubens House — The former home and studio of Baroque master Peter Paul Rubens",
      "Het Eilandje — The revitalized dock area with MAS museum, Red Star Line Museum, and trendy restaurants",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Rubens walking tours, Diamond District visits, fashion district walks, port tours, and Art Deco architecture." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "40+", description: "MAS, Rubens House, Royal Museum of Fine Arts, Red Star Line Museum, FOMU photography, and Plantin-Moretus (UNESCO)." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "50+", description: "Antwerp chocolate tours, craft beer tastings, Flemish cuisine walks, diamond-shaped pralines, and street food." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Cathedral of Our Lady, Central Station, Antwerp Zoo, Grote Markt, and MAS rooftop." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "25+", description: "Rubens trail, fashion academy tours, street art in Zurenborg, and contemporary galleries in the South Quarter." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "30+", description: "Brussels, Mechelen, Lier, Turnhout, Dutch border towns, and Flanders battlefields." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "10+", description: "Scheldt river walks, Rivierenhof park, cycling tours, and harbour boat trips." },
      { slug: "river-cruises", name: "Boat Tours", icon: "\u{1F6A2}", count: "10+", description: "Scheldt river cruises, harbour tours, and sunset boat trips." },
      { slug: "shopping", name: "Shopping", icon: "\u{1F6CD}\u{FE0F}", count: "15+", description: "Meir shopping boulevard, fashion district, vintage markets, and Diamond District showrooms." },
    ],
    geoLat: 51.2194,
    geoLon: 4.4025,
    faq: [
      { q: "What group experiences are available in Antwerp?", a: "TicketMatch.ai provides access to 1,500+ experiences: Rubens House, Diamond District, MAS museum, food tours, fashion walks, and more — all at exclusive B2B group rates." },
      { q: "What diamond experiences are available?", a: "Antwerp processes 84% of the world's rough diamonds. TicketMatch.ai offers group Diamond District tours, cutting demonstrations, showroom visits, and diamond history walks at B2B rates." },
      { q: "What makes Antwerp special for groups?", a: "Antwerp combines world-class art (Rubens), diamonds, fashion (Royal Academy), and the best Flemish food scene in Belgium. Less touristy than Bruges with more urban energy." },
      { q: "Is Antwerp good for group travel?", a: "Very. Antwerp has excellent train connections (30 min from Brussels), a compact walkable center, and diverse experiences from art to diamonds. TicketMatch.ai helps plan Belgian group itineraries." },
    ],
  },
];
