import type { CityData } from "./cities-data";

export const frenchCities: CityData[] = [
  {
    slug: "paris",
    name: "Paris",
    province: "Île-de-France",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "8,500+",
    categories: 14,
    viatorDestId: 479,
    tagline: "The City of Light — world capital of art, fashion & gastronomy",
    description:
      "Paris needs no introduction — the world's most visited city offers an unmatched density of iconic landmarks, world-class museums, and unforgettable experiences. From the Eiffel Tower and Louvre to Montmartre and the Seine, TicketMatch.ai provides B2B access to 8,500+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Eiffel Tower — The 330-meter iron icon visited by 7 million people annually, with summit and second-floor group access",
      "Louvre Museum — World's largest art museum housing the Mona Lisa, Venus de Milo, and 380,000+ works",
      "Musée d'Orsay — Impressionist masterpiece collection in a stunning former railway station",
      "Palace of Versailles — Louis XIV's magnificent palace with Hall of Mirrors and 800 hectares of gardens",
      "Arc de Triomphe — Napoleon's monumental arch at the top of the Champs-Élysées with panoramic rooftop views",
      "Sacré-Cœur Basilica — Romano-Byzantine church crowning Montmartre with sweeping city views",
      "Notre-Dame Cathedral — Gothic masterpiece on Île de la Cité, reopened after restoration",
      "Moulin Rouge — The legendary cabaret venue in Pigalle, operating since 1889",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "320+", description: "Louvre, Musée d'Orsay, Centre Pompidou, Orangerie, Rodin Museum, Picasso Museum, and 300+ more museums at B2B group rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "400+", description: "Eiffel Tower tours, Seine river cruises, Montmartre walks, catacombs, Latin Quarter, and after-dark Paris experiences." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "150+", description: "Eiffel Tower, Arc de Triomphe, Disneyland Paris, Versailles, Sainte-Chapelle, Panthéon, and more." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "200+", description: "Wine tastings, cheese tours, patisserie classes, market walks in Le Marais, cooking classes, and Michelin-star dining experiences." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "180+", description: "Versailles, Giverny (Monet's Garden), Mont Saint-Michel, Loire Valley châteaux, Champagne region, and Normandy D-Day beaches." },
      { slug: "river-cruises", name: "River Cruises", icon: "\u{1F6A2}", count: "80+", description: "Seine dinner cruises, Bateaux Mouches, hop-on hop-off boats, sunset champagne cruises, and private group charters." },
    ],
    geoLat: 48.8566,
    geoLon: 2.3522,
    faq: [
      { q: "What group experiences are available in Paris?", a: "TicketMatch.ai provides access to 8,500+ experiences in Paris: skip-the-line Louvre and Eiffel Tower tickets, Seine cruises, Versailles day trips, food tours, Montmartre walks, and more — all at exclusive B2B group rates." },
      { q: "How do I book group tickets for the Louvre?", a: "Through TicketMatch.ai, you can book group skip-the-line tickets for the Louvre, including guided tours with licensed guides, evening visits, and combined Louvre + Musée d'Orsay packages at wholesale B2B rates." },
      { q: "Can I book Versailles day trips for groups?", a: "Yes. TicketMatch.ai offers multiple Versailles group options: palace-only tickets, palace + gardens, guided tours with transport from Paris, and VIP skip-the-line access. All at B2B rates with flexible group sizes." },
      { q: "What food experiences are available for groups in Paris?", a: "Paris food experiences include guided market tours in Le Marais, cheese and wine tastings, patisserie masterclasses, cooking classes, chocolate tours, and multi-course dinners in historic venues — all bookable at B2B group rates." },
      { q: "Is Paris suitable for large group travel?", a: "Absolutely. Paris is Europe's #1 group travel destination with excellent metro connections, thousands of group-ready venues, and multilingual guides. TicketMatch.ai's busyness data helps plan visits outside peak hours." },
    ],
  },
  {
    slug: "lyon",
    name: "Lyon",
    province: "Auvergne-Rhône-Alpes",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "2,800+",
    categories: 10,
    viatorDestId: 5630,
    tagline: "France's gastronomic capital with 2,000 years of history",
    description:
      "Lyon is France's third-largest city and its undisputed culinary capital. With a UNESCO-listed old town, world-class museums, and a food scene that rivals Paris, TicketMatch.ai provides B2B access to 2,800+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Vieux Lyon — UNESCO World Heritage Renaissance district with traboules (secret passageways)",
      "Basilique Notre-Dame de Fourvière — Hilltop basilica overlooking the city with stunning mosaics",
      "Musée des Confluences — Futuristic science museum at the confluence of the Rhône and Saône",
      "Les Halles de Lyon Paul Bocuse — Legendary indoor food market honoring the father of nouvelle cuisine",
      "Presqu'île — Central peninsula between two rivers with Place Bellecour and designer boutiques",
      "Parc de la Tête d'Or — Vast urban park with free zoo, botanical gardens, and lake boating",
    ],
    topCategories: [
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "120+", description: "Bouchon Lyonnais dining, Les Halles market tours, wine tastings (Beaujolais, Côtes du Rhône), cooking classes, and chocolate workshops." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "150+", description: "Vieux Lyon traboule walks, Fourvière hill tours, Presqu'île architecture walks, street art tours, and Rhône river cruises." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "60+", description: "Musée des Confluences, Musée des Beaux-Arts, Lugdunum Roman museum, Institut Lumière (birthplace of cinema), and more." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "40+", description: "Fourvière Basilica, Roman amphitheatre, Parc de la Tête d'Or, aquarium, and panoramic viewpoints." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "Beaujolais wine country, Pérouges medieval village, Annecy lake, Mont Blanc, and Côtes du Rhône vineyard tours." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "30+", description: "Rhône and Saône river cruises, cycling along the rivers, Parc de la Tête d'Or, and hiking in nearby Alps foothills." },
    ],
    geoLat: 45.7640,
    geoLon: 4.8357,
    faq: [
      { q: "What group experiences are available in Lyon?", a: "TicketMatch.ai provides access to 2,800+ experiences in Lyon: food tours at Les Halles, Vieux Lyon traboule walks, Beaujolais wine excursions, museum visits, river cruises, and more — all at exclusive B2B group rates." },
      { q: "Why is Lyon called the gastronomic capital of France?", a: "Lyon earned this title thanks to legendary chef Paul Bocuse, its iconic bouchons (traditional restaurants), Les Halles market, and proximity to Beaujolais and Côtes du Rhône wine regions. TicketMatch.ai offers 120+ food & drink group experiences." },
      { q: "Can I combine Lyon with wine region day trips?", a: "Yes. TicketMatch.ai offers group day trips to Beaujolais, Côtes du Rhône, and other wine regions near Lyon. Private vineyard visits, tastings, and combined city + wine packages are available at B2B rates." },
      { q: "Is Lyon good for group travel?", a: "Lyon is excellent for groups with its compact walkable center, efficient metro/tram system, diverse venues, and France's best food scene. TicketMatch.ai's AI assistant helps plan optimal group itineraries." },
    ],
  },
  {
    slug: "nice",
    name: "Nice",
    province: "Provence-Alpes-Côte d'Azur",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "3,200+",
    categories: 11,
    viatorDestId: 483,
    tagline: "The jewel of the French Riviera and gateway to Côte d'Azur",
    description:
      "Nice is the stunning capital of the French Riviera, where the Mediterranean meets Belle Époque elegance. With its famous Promenade des Anglais, vibrant old town, and easy access to Monaco and Cannes, TicketMatch.ai provides B2B access to 3,200+ group experiences at exclusive rates.",
    highlights: [
      "Promenade des Anglais — The iconic 7km seafront boulevard along the Baie des Anges",
      "Vieux Nice — Colorful old town with Cours Saleya flower market, baroque churches, and gelato",
      "Castle Hill (Colline du Château) — Panoramic viewpoint over Nice's coastline and terracotta rooftops",
      "Musée Matisse — Dedicated to Henri Matisse in a 17th-century Genoese villa",
      "MAMAC — Museum of Modern and Contemporary Art with Klein, Warhol, and Niki de Saint Phalle",
      "Place Masséna — Nice's main square with its striking checkerboard pavement and fountains",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "200+", description: "Old Nice walking tours, Promenade bike rides, street art tours, panoramic bus tours, and segway tours along the coast." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "180+", description: "Monaco & Monte Carlo, Cannes, Saint-Tropez, Èze village, Antibes, Grasse perfume factories, and Provence lavender fields." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Cours Saleya market tours, Niçoise cooking classes, Provençal wine tastings, olive oil tours, and socca street food walks." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "60+", description: "Castle Hill, Promenade des Anglais, Russian Orthodox Cathedral, Parc Phoenix, and beach clubs." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "40+", description: "Musée Matisse, MAMAC, Chagall Museum, Museum of Photography, and Musée Masséna." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "50+", description: "Mediterranean boat trips, snorkeling, kayaking, coastal hiking trails, and paragliding over the Riviera." },
    ],
    geoLat: 43.7102,
    geoLon: 7.2620,
    faq: [
      { q: "What group experiences are available in Nice?", a: "TicketMatch.ai provides access to 3,200+ experiences on the French Riviera: Monaco day trips, Promenade walks, old town food tours, Matisse museum visits, boat trips, and more — all at exclusive B2B group rates." },
      { q: "Can I book Monaco day trips from Nice for groups?", a: "Yes. TicketMatch.ai offers multiple Monaco group options: half-day and full-day trips, combined Monaco + Èze + Monte Carlo tours, Grand Prix circuit visits, and Oceanographic Museum access at B2B rates." },
      { q: "What Côte d'Azur experiences are available?", a: "The full Riviera is covered: Cannes, Saint-Tropez, Antibes, Grasse perfume tours, Èze hilltop village, and even Provence lavender fields — all bookable as group day trips from Nice via TicketMatch.ai." },
      { q: "Is Nice good for group travel?", a: "Excellent. Nice has a modern tram system, compact walkable center, proximity to 10+ Riviera destinations, and year-round mild weather. TicketMatch.ai helps plan multi-destination Riviera itineraries at B2B rates." },
    ],
  },
  {
    slug: "marseille",
    name: "Marseille",
    province: "Provence-Alpes-Côte d'Azur",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "2,100+",
    categories: 10,
    viatorDestId: 4843,
    tagline: "France's oldest city — Mediterranean culture, calanques & bouillabaisse",
    description:
      "Marseille is France's second-largest city and its oldest, founded by the Greeks in 600 BC. With its stunning Calanques National Park, multicultural Vieux-Port, and MuCEM museum, TicketMatch.ai provides B2B access to 2,100+ group experiences at exclusive rates.",
    highlights: [
      "Calanques National Park — Dramatic limestone cliffs and turquoise coves along the Mediterranean coast",
      "Vieux-Port — The historic old harbor lined with restaurants, markets, and the iconic fish stalls",
      "Notre-Dame de la Garde — Hilltop basilica nicknamed 'La Bonne Mère' with 360° city and sea views",
      "MuCEM — Museum of European and Mediterranean Civilisations, a stunning waterfront landmark",
      "Le Panier — Marseille's oldest neighborhood with colorful streets, street art, and artisan shops",
      "Château d'If — The island fortress made famous by Alexandre Dumas' Count of Monte Cristo",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "120+", description: "Vieux-Port walking tours, Le Panier street art walks, panoramic bus tours, and Marseille history tours." },
      { slug: "outdoor", name: "Outdoor & Nature", icon: "\u{1F33F}", count: "80+", description: "Calanques boat trips and hikes, kayaking, snorkeling, Frioul islands, and Château d'If boat excursions." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "60+", description: "Bouillabaisse dining, Noailles market tours, pastis tastings, Provençal cooking classes, and navette biscuit workshops." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "35+", description: "MuCEM, Musée des Civilisations, Cosquer Cave replica, Musée Cantini, and more." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "70+", description: "Aix-en-Provence, Cassis, Avignon, Arles (Van Gogh), Camargue nature reserve, and Provence lavender tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Notre-Dame de la Garde, Château d'If, Vieux-Port, Unité d'Habitation (Le Corbusier), and Palais Longchamp." },
    ],
    geoLat: 43.2965,
    geoLon: 5.3698,
    faq: [
      { q: "What group experiences are available in Marseille?", a: "TicketMatch.ai provides access to 2,100+ experiences: Calanques boat trips, Vieux-Port food tours, MuCEM museum visits, Château d'If excursions, and more — all at exclusive B2B group rates." },
      { q: "Can I book Calanques National Park for groups?", a: "Yes. TicketMatch.ai offers group boat trips through the Calanques, guided hiking, kayaking, and combined land + sea tours. All at B2B rates with flexible group sizes." },
      { q: "What day trips are available from Marseille?", a: "Group day trips include Aix-en-Provence, Cassis fishing village, Avignon's Papal Palace, Arles (Van Gogh), Camargue flamingos, and Provence lavender fields — all bookable at B2B rates." },
      { q: "Is Marseille good for group travel?", a: "Yes. Marseille has a modern metro system, compact center around Vieux-Port, diverse experiences from culture to nature, and excellent connections to Provence. TicketMatch.ai's AI helps plan multi-day Provence itineraries." },
    ],
  },
  {
    slug: "bordeaux",
    name: "Bordeaux",
    province: "Nouvelle-Aquitaine",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "1,900+",
    categories: 9,
    viatorDestId: 5637,
    tagline: "World wine capital with stunning 18th-century architecture",
    description:
      "Bordeaux is the world's wine capital and a UNESCO World Heritage city renowned for its elegant 18th-century architecture. With the Cité du Vin, Saint-Émilion, and the magnificent Place de la Bourse, TicketMatch.ai provides B2B access to 1,900+ group experiences at exclusive rates.",
    highlights: [
      "Cité du Vin — Interactive wine museum and cultural center shaped like a wine decanter",
      "Place de la Bourse — Iconic 18th-century square with the famous Miroir d'Eau water mirror",
      "Saint-Émilion — UNESCO medieval village surrounded by world-famous vineyards, 40 minutes from Bordeaux",
      "Rue Sainte-Catherine — Europe's longest pedestrian shopping street at 1.2km",
      "Bordeaux Cathedral (Cathédrale Saint-André) — 11th-century Gothic cathedral, a UNESCO site",
      "La Grosse Cloche — Medieval bell tower gate, one of the oldest in France",
    ],
    topCategories: [
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "150+", description: "Bordeaux wine tastings, Saint-Émilion vineyard tours, Médoc château visits, canelé workshops, and gourmet market walks." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "100+", description: "UNESCO old town walks, river Garonne cruises, e-bike city tours, night illumination tours, and architecture walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "90+", description: "Saint-Émilion, Médoc wine route, Arcachon Bay & Dune du Pilat, Cognac, and Périgord truffle country." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "25+", description: "Cité du Vin, Musée d'Aquitaine, CAPC contemporary art museum, Bassins de Lumières digital art, and more." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Place de la Bourse, Miroir d'Eau, Grosse Cloche, Bordeaux Cathedral, and Pont de Pierre." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "25+", description: "Garonne river cruises, vineyard cycling, Arcachon Bay oyster boats, Dune du Pilat hiking, and e-bike tours." },
    ],
    geoLat: 44.8378,
    geoLon: -0.5792,
    faq: [
      { q: "What group experiences are available in Bordeaux?", a: "TicketMatch.ai provides access to 1,900+ experiences: wine château tours, Saint-Émilion visits, Cité du Vin, river cruises, food tours, and more — all at exclusive B2B group rates." },
      { q: "Can I book Saint-Émilion wine tours for groups?", a: "Yes. TicketMatch.ai offers group tours to Saint-Émilion including château visits, underground catacombs, wine tastings, and lunch at estates. Full-day and half-day options at B2B rates." },
      { q: "What wine regions can groups visit from Bordeaux?", a: "Médoc (Margaux, Pauillac), Saint-Émilion, Graves, Sauternes, and Entre-Deux-Mers — all accessible as group day trips. TicketMatch.ai also offers multi-day wine route itineraries at B2B rates." },
      { q: "Is Bordeaux good for group travel?", a: "Excellent. Bordeaux's compact UNESCO center is walkable, the tram system is efficient, and it's surrounded by world-class wine regions. TicketMatch.ai helps create wine + culture itineraries for groups." },
    ],
  },
  {
    slug: "strasbourg",
    name: "Strasbourg",
    province: "Grand Est",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "1,400+",
    categories: 8,
    viatorDestId: 23054,
    tagline: "Capital of Europe — where French and German cultures meet",
    description:
      "Strasbourg is the seat of the European Parliament and a city where French and German cultures beautifully merge. Its UNESCO-listed Grande Île, Gothic cathedral, and charming Petite France quarter make it a unique group destination. TicketMatch.ai provides B2B access to 1,400+ group experiences at exclusive rates.",
    highlights: [
      "Strasbourg Cathedral — Gothic masterpiece with astronomical clock and 142-meter spire platform",
      "Petite France — Fairy-tale half-timbered houses along canals in the UNESCO old town",
      "European Parliament — Seat of EU democracy, offering group tours of the hemicycle",
      "Grande Île — UNESCO World Heritage island forming Strasbourg's historic center",
      "Covered Bridges (Ponts Couverts) — Medieval fortified bridges spanning the Ill river",
      "Palais Rohan — Three museums in one Baroque palace: archaeology, decorative arts, fine arts",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Petite France walks, cathedral climbs, canal boat rides, Grande Île tours, and European Quarter visits." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "60+", description: "Alsatian wine route tours, tarte flambée evenings, choucroute tastings, winstub dining, and Christmas market food tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "70+", description: "Alsace wine route, Colmar, Riquewihr, Haut-Koenigsbourg Castle, Black Forest (Germany), and Europa-Park." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "25+", description: "Palais Rohan museums, Alsatian Museum, Museum of Modern Art, Historical Museum, and European Parliament visitor center." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Strasbourg Cathedral, Petite France, European Parliament, Orangerie Park, and Barrage Vauban." },
      { slug: "river-cruises", name: "River Cruises", icon: "\u{1F6A2}", count: "15+", description: "Ill river boat tours through Petite France, Rhine river excursions, and dinner cruises with Alsatian wine." },
    ],
    geoLat: 48.5734,
    geoLon: 7.7521,
    faq: [
      { q: "What group experiences are available in Strasbourg?", a: "TicketMatch.ai provides access to 1,400+ experiences: Petite France canal tours, cathedral visits, Alsace wine route day trips, European Parliament tours, and more — all at exclusive B2B group rates." },
      { q: "Can I book Alsace wine route tours for groups?", a: "Yes. TicketMatch.ai offers group tours along the 170km Alsace wine route: Riesling and Gewürztraminer tastings, medieval village visits (Colmar, Riquewihr, Eguisheim), and château tours at B2B rates." },
      { q: "Is the European Parliament open for group tours?", a: "Yes. Groups can visit the European Parliament hemicycle, Parlamentarium, and European Quarter. TicketMatch.ai helps book guided group tours including combined Parliament + old town itineraries." },
      { q: "Is Strasbourg good for group travel?", a: "Very. Strasbourg has an efficient tram system, compact walkable center, excellent Franco-German cuisine, and easy access to the Alsace wine route. TicketMatch.ai's AI helps plan Alsace group itineraries." },
    ],
  },
  {
    slug: "toulouse",
    name: "Toulouse",
    province: "Occitanie",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "1,200+",
    categories: 8,
    viatorDestId: 5643,
    tagline: "The Pink City — aerospace innovation meets southern French charm",
    description:
      "Toulouse is France's fourth-largest city, known as 'La Ville Rose' for its distinctive pink terracotta buildings. Home to Airbus and the European space industry, it blends aerospace innovation with medieval charm. TicketMatch.ai provides B2B access to 1,200+ group experiences at exclusive rates.",
    highlights: [
      "Cité de l'Espace — Europe's leading space theme park with full-scale rockets and planetarium",
      "Airbus Factory — Behind-the-scenes tours of the A380 and A350 assembly lines",
      "Basilique Saint-Sernin — Europe's largest Romanesque church, a UNESCO pilgrimage site",
      "Place du Capitole — Magnificent 18th-century square and town hall in the city center",
      "Canal du Midi — UNESCO-listed 17th-century canal connecting the Atlantic to the Mediterranean",
      "Musée des Augustins — Fine arts museum in a former Augustinian monastery with Gothic cloisters",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "70+", description: "Pink City walking tours, Capitole square visits, canal boat rides, street art walks, and Toulouse by night." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Cité de l'Espace, Airbus factory tours, Halle de la Machine (giant mechanical creatures), and Basilique Saint-Sernin." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "50+", description: "Cassoulet tastings, Victor Hugo market tours, Armagnac tastings, violet-flavored specialties, and farm-to-table dining." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "60+", description: "Carcassonne medieval citadel, Albi (Toulouse-Lautrec), Canal du Midi cruise, Cathar castles, and Pyrenees mountains." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "20+", description: "Musée des Augustins, Les Abattoirs modern art, Musée Saint-Raymond archaeology, and Aeroscopia aviation museum." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "25+", description: "Canal du Midi cycling, Garonne river walks, Pyrenees hiking day trips, and Japanese Garden visits." },
    ],
    geoLat: 43.6047,
    geoLon: 1.4442,
    faq: [
      { q: "What group experiences are available in Toulouse?", a: "TicketMatch.ai provides access to 1,200+ experiences: Airbus factory tours, Cité de l'Espace, old town walks, Canal du Midi cruises, and more — all at exclusive B2B group rates." },
      { q: "Can I book Airbus factory tours for groups?", a: "Yes. TicketMatch.ai offers group access to the Airbus assembly lines (A380, A350) and the Aeroscopia aviation museum. Tours must be booked well in advance — our platform makes this easy at B2B rates." },
      { q: "What day trips are available from Toulouse?", a: "Group day trips include Carcassonne's medieval citadel, Albi (Toulouse-Lautrec Museum), Canal du Midi boat trips, Cathar castle routes, and Pyrenees mountain excursions — all at B2B rates." },
      { q: "Is Toulouse good for group travel?", a: "Yes. Toulouse has an efficient metro system, walkable pink-brick center, unique aerospace attractions, and is gateway to both the Pyrenees and Mediterranean. TicketMatch.ai helps plan southern France itineraries." },
    ],
  },
  {
    slug: "avignon",
    name: "Avignon",
    province: "Provence-Alpes-Côte d'Azur",
    country: "France",
    flag: "\u{1F1EB}\u{1F1F7}",
    experiences: "1,100+",
    categories: 8,
    viatorDestId: 22006,
    tagline: "City of Popes — medieval grandeur at the heart of Provence",
    description:
      "Avignon is Provence's crown jewel — a walled medieval city famous for its Palais des Papes and the legendary broken bridge. As gateway to Provence's lavender fields, wine regions, and hilltop villages, TicketMatch.ai provides B2B access to 1,100+ group experiences at exclusive rates.",
    highlights: [
      "Palais des Papes — Europe's largest Gothic palace, seat of 14th-century popes",
      "Pont d'Avignon (Pont Saint-Bénézet) — The legendary broken bridge immortalized in the famous song",
      "Avignon City Walls — Remarkably preserved 4.3km medieval ramparts surrounding the old town",
      "Place de l'Horloge — Central square with the opera house and historic clock tower",
      "Rocher des Doms — Hilltop park with panoramic views of the Rhône and Mont Ventoux",
      "Festival d'Avignon — One of the world's greatest performing arts festivals every July",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "60+", description: "Palais des Papes guided tours, old town walks, rampart tours, Rhône river views, and festival-themed cultural tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "Provence lavender fields (Luberon, Valensole), Châteauneuf-du-Pape wine tours, Pont du Gard, Les Baux-de-Provence, and Gordes." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "40+", description: "Provençal market tours, Châteauneuf-du-Pape tastings, olive oil mills, truffle hunts, and cooking classes." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "Palais des Papes, Pont d'Avignon, city ramparts, Rocher des Doms gardens, and Collection Lambert modern art." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "15+", description: "Petit Palais (Italian Renaissance art), Calvet Museum, Angladon Museum (Van Gogh, Picasso), and Palais des Papes exhibits." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "20+", description: "Rhône river cruises, lavender field visits, Mont Ventoux cycling, kayaking under Pont du Gard, and Luberon village cycling." },
    ],
    geoLat: 43.9493,
    geoLon: 4.8055,
    faq: [
      { q: "What group experiences are available in Avignon?", a: "TicketMatch.ai provides access to 1,100+ experiences: Palais des Papes tours, Provence lavender excursions, wine tastings, Pont du Gard visits, and more — all at exclusive B2B group rates." },
      { q: "Can I book Provence lavender tours from Avignon?", a: "Yes. TicketMatch.ai offers group lavender tours to Luberon, Valensole plateau, and Sénanque Abbey. Best season is mid-June to early August. Combined lavender + wine + village tours available at B2B rates." },
      { q: "What wine experiences are available near Avignon?", a: "Châteauneuf-du-Pape is 20 minutes away. TicketMatch.ai offers group château visits, tastings, and combined wine + Provence village tours. Also available: Gigondas, Vacqueyras, and Tavel rosé tours." },
      { q: "Is Avignon a good base for group Provence tours?", a: "Perfect. Avignon is Provence's main transport hub with TGV station, central location for lavender, wine, and hilltop villages. TicketMatch.ai helps plan multi-day Provence group itineraries at B2B rates." },
    ],
  },
];
