import type { CityData } from "./cities-data";

export const germanCities: CityData[] = [
  {
    slug: "berlin",
    name: "Berlin",
    province: "Berlin",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "6,200+",
    categories: 12,
    viatorDestId: 488,
    tagline: "Europe's capital of culture, history & nightlife",
    description:
      "Berlin is Germany's vibrant capital — a city where history meets cutting-edge culture. From the Brandenburg Gate and Museum Island to the East Side Gallery and thriving food scene, TicketMatch.ai provides B2B access to 6,200+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Brandenburg Gate — Berlin's most iconic landmark and symbol of German reunification",
      "Museum Island — UNESCO World Heritage complex with 5 world-class museums including Pergamon",
      "East Side Gallery — The longest remaining section of the Berlin Wall, 1.3 km of street art",
      "Reichstag Building — Seat of the German parliament with its stunning glass dome by Norman Foster",
      "Checkpoint Charlie — The famous Cold War crossing point between East and West Berlin",
      "Berlin TV Tower — 368-meter Fernsehturm with panoramic views over the entire city",
      "Memorial to the Murdered Jews of Europe — Powerful Holocaust memorial by Peter Eisenman",
      "Charlottenburg Palace — Berlin's largest palace with baroque gardens and royal collections",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "180+", description: "Museum Island (Pergamon, Neues, Alte Nationalgalerie), DDR Museum, Jewish Museum, Topography of Terror, and 150+ more museums at B2B group rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "250+", description: "Cold War tours, Berlin Wall walks, Third Reich history, street art tours, bike tours, river cruises, and alternative Berlin experiences." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "80+", description: "Berlin TV Tower, Reichstag dome, Berlin Zoo & Aquarium, Madame Tussauds, LEGOLAND Discovery Centre, and more." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Currywurst tours, craft beer walks, Markthalle Neun visits, multicultural food tours, and group dining in historic venues." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "120+", description: "Street art tours, gallery walks in Kreuzberg, Berlinische Galerie, Urban Nation Museum, and underground culture experiences." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "40+", description: "Tiergarten walks, Spree river cruises, Tempelhof Field, Wannsee lake trips, and cycling tours." },
    ],
    geoLat: 52.5200,
    geoLon: 13.4050,
    faq: [
      { q: "What group experiences are available in Berlin?", a: "TicketMatch.ai provides access to 6,200+ experiences in Berlin: Museum Island tours, Cold War history walks, Berlin Wall sites, street art tours, river cruises, food tours, and more — all at exclusive B2B group rates." },
      { q: "How do I book group museum tickets in Berlin?", a: "With TicketMatch.ai, you can book group tickets for all 5 Museum Island museums (Pergamon, Neues Museum, Alte Nationalgalerie, Altes Museum, Bode Museum), DDR Museum, Jewish Museum, and 150+ more — through one B2B platform at wholesale rates." },
      { q: "What Cold War tours are available for groups in Berlin?", a: "TicketMatch.ai offers guided Cold War group tours covering the Berlin Wall, Checkpoint Charlie, East Side Gallery, Stasi Prison, and the Reichstag. Private group tours can be customized to focus on specific Cold War themes." },
      { q: "Is Berlin good for group travel?", a: "Absolutely. Berlin is one of Europe's top group travel destinations with excellent public transport, walkable neighborhoods, world-class museums, and diverse experiences. TicketMatch.ai's busyness data helps plan optimal visit times for popular venues." },
      { q: "Can I combine Berlin with other German cities?", a: "Yes. Berlin connects easily to Dresden (2h), Hamburg (1.5h), and Leipzig (1h) by train. TicketMatch.ai's package builder creates multi-city German itineraries with B2B rates across all cities." },
      { q: "What is Museum Island in Berlin?", a: "Museum Island (Museumsinsel) is a UNESCO World Heritage complex of 5 museums on an island in the Spree river. It includes the Pergamon Museum, Neues Museum (Nefertiti bust), and more. TicketMatch.ai offers group access at B2B rates." },
    ],
  },
  {
    slug: "munich",
    name: "Munich",
    province: "Bavaria",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "4,800+",
    categories: 11,
    viatorDestId: 490,
    tagline: "Bavaria's crown jewel — beer, culture & Alpine charm",
    description:
      "Munich (München) is the capital of Bavaria and one of Europe's most popular group travel destinations. Home to Oktoberfest, world-class art museums, and stunning Alpine day trips, TicketMatch.ai connects tour operators to 4,800+ group experiences at exclusive B2B rates.",
    highlights: [
      "Marienplatz & Neues Rathaus — Munich's central square with the famous Glockenspiel clock tower",
      "Deutsches Museum — The world's largest science and technology museum with 28,000+ exhibits",
      "Nymphenburg Palace — Baroque palace with stunning gardens, once home to Bavarian royalty",
      "BMW Welt & Museum — Interactive automotive experience and BMW history for groups",
      "English Garden — One of the world's largest urban parks with famous beer gardens",
      "Residenz München — Former royal palace with 130 rooms of art and treasures",
      "Viktualienmarkt — Munich's famous daily food market since 1807",
      "Neuschwanstein Castle — Day trip to Ludwig II's fairy-tale castle in the Alps",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "100+", description: "Deutsches Museum, Pinakothek trio, BMW Museum, Residenz, Lenbachhaus, and 80+ more museums at B2B rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "180+", description: "Old town walks, beer tours, Third Reich history, bike tours, and Bavarian culture experiences." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "90+", description: "Beer hall tours, Viktualienmarkt visits, Bavarian cooking classes, pretzel workshops, and brewery tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "60+", description: "BMW Welt, Olympiapark, Allianz Arena tours, Sea Life, and Hellabrunn Zoo." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F3D4}\u{FE0F}", count: "50+", description: "Neuschwanstein Castle, Salzburg, Dachau Memorial, Eagle's Nest, and Alpine lake excursions." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "40+", description: "Pinakotheken art museums, Lenbachhaus (Blue Rider), opera at Bayerische Staatsoper, and gallery tours." },
    ],
    geoLat: 48.1351,
    geoLon: 11.5820,
    faq: [
      { q: "What group experiences are available in Munich?", a: "TicketMatch.ai offers 4,800+ experiences in Munich: beer hall tours, museum visits, Neuschwanstein Castle day trips, BMW Welt, Oktoberfest events, and Bavarian cultural experiences — all at exclusive B2B group rates." },
      { q: "Can I book Neuschwanstein Castle for groups through TicketMatch?", a: "Yes. TicketMatch.ai offers group day trips from Munich to Neuschwanstein Castle including transport, skip-the-line tickets, and guided tours — at B2B wholesale rates." },
      { q: "What beer-related experiences are available for groups?", a: "Munich is the beer capital of the world. TicketMatch.ai offers beer hall tours (Hofbräuhaus, Augustiner), brewery visits, beer tasting workshops, Oktoberfest packages, and beer garden cycling tours for groups." },
      { q: "How many museums can I book in Munich?", a: "TicketMatch.ai provides group access to 100+ Munich museums including Deutsches Museum, the three Pinakotheken, BMW Museum, Residenz München, Lenbachhaus, and more — all at B2B rates." },
      { q: "Can I combine Munich with Salzburg for group trips?", a: "Yes. Salzburg is just 1.5 hours from Munich by train. TicketMatch.ai's package builder creates multi-city itineraries combining Munich's beer culture with Salzburg's Mozart heritage." },
    ],
  },
  {
    slug: "hamburg",
    name: "Hamburg",
    province: "Hamburg",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "3,100+",
    categories: 10,
    viatorDestId: 489,
    tagline: "Germany's gateway to the world — harbour, music & Speicherstadt",
    description:
      "Hamburg is Germany's second-largest city and its gateway to the world. Known for its spectacular harbour, the UNESCO Speicherstadt warehouse district, and the stunning Elbphilharmonie concert hall, TicketMatch.ai offers B2B access to 3,100+ group experiences.",
    highlights: [
      "Speicherstadt — UNESCO World Heritage warehouse district, the largest in the world",
      "Elbphilharmonie — Hamburg's stunning concert hall, an architectural masterpiece on the harbour",
      "Miniatur Wunderland — The world's largest model railway and top-rated attraction in Germany",
      "Hamburg Harbour — Europe's third-largest port with harbour cruises and fish market",
      "Reeperbahn — Famous entertainment district, Beatles history, and nightlife",
      "International Maritime Museum — Nine floors of seafaring history in a historic warehouse",
      "Planten un Blomen — Beautiful botanical garden in the heart of the city",
      "Kunsthalle Hamburg — World-class art collection from medieval to contemporary",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "60+", description: "Kunsthalle, Maritime Museum, Miniatur Wunderland, Dialog im Dunkeln, Deichtorhallen, and more." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "100+", description: "Harbour cruises, Speicherstadt walks, Reeperbahn tours, Beatles tours, and canal boat trips." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "45+", description: "Miniatur Wunderland, Elbphilharmonie Plaza, Hamburg Dungeon, Tierpark Hagenbeck, and TV tower." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "50+", description: "Fish market tours, harbour dining, Speicherstadt coffee tours, craft beer walks, and traditional sailor food." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "35+", description: "Kunsthalle, Deichtorhallen photography, musical shows, Elbphilharmonie concerts, and gallery walks." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "25+", description: "Alster lake cruises, Planten un Blomen, harbour cycling, and Elbe beach walks." },
    ],
    geoLat: 53.5511,
    geoLon: 9.9937,
    faq: [
      { q: "What group experiences are available in Hamburg?", a: "TicketMatch.ai offers 3,100+ experiences in Hamburg: harbour cruises, Speicherstadt tours, Miniatur Wunderland, Elbphilharmonie visits, Beatles history tours, and more — at exclusive B2B rates." },
      { q: "Is Miniatur Wunderland good for groups?", a: "Yes. Miniatur Wunderland is Germany's #1 rated attraction. TicketMatch.ai offers group bookings with priority entry at B2B rates. It's a must-visit for any group in Hamburg." },
      { q: "What harbour tours are available for groups?", a: "TicketMatch.ai offers multiple harbour cruise options: classic harbour tours, Speicherstadt boat trips, evening cruises, and private charter boats — all at B2B wholesale rates for groups." },
      { q: "Can I visit the Elbphilharmonie with a group?", a: "Yes. TicketMatch.ai offers Elbphilharmonie Plaza visits, guided architecture tours, and concert packages for groups at B2B rates." },
      { q: "How far is Hamburg from Berlin?", a: "Hamburg is just 1.5 hours from Berlin by ICE train. TicketMatch.ai's package builder makes combining Hamburg and Berlin into one group itinerary easy with B2B rates for both cities." },
    ],
  },
  {
    slug: "frankfurt",
    name: "Frankfurt",
    province: "Hesse",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "2,400+",
    categories: 9,
    viatorDestId: 491,
    tagline: "Financial capital meets culture — the Manhattan of Europe",
    description:
      "Frankfurt am Main is Germany's financial capital and a major international hub. Beyond its skyline, Frankfurt offers world-class museums along the Museumsufer, the historic Römerberg square, and easy access to the Rhine Valley. TicketMatch.ai provides B2B access to 2,400+ group experiences.",
    highlights: [
      "Römerberg — Frankfurt's medieval central square with the iconic Römer town hall",
      "Museumsufer — Museum Embankment with 12+ world-class museums along the Main river",
      "Städel Museum — One of Germany's most important art museums with 700 years of art",
      "Palmengarten — One of Europe's largest botanical gardens with tropical greenhouses",
      "Main Tower — Frankfurt's only skyscraper with a public observation deck",
      "Goethe House — Birthplace of Johann Wolfgang von Goethe, Germany's greatest writer",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "50+", description: "Städel Museum, Senckenberg Natural History, German Film Museum, Jewish Museum, and Museumsufer collections." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Old town walks, skyline tours, Main river cruises, apple wine tours, and financial district tours." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "40+", description: "Apple wine (Apfelwein) tours in Sachsenhausen, Kleinmarkthalle visits, and traditional Hessian dining." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F3D4}\u{FE0F}", count: "35+", description: "Rhine Valley castles, Heidelberg, Rothenburg ob der Tauber, and Rüdesheim wine tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Main Tower, Palmengarten, Frankfurt Zoo, Senckenberg Museum, and observation decks." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "25+", description: "Städel, Schirn Kunsthalle, Museum für Moderne Kunst, opera, and gallery walks." },
    ],
    geoLat: 50.1109,
    geoLon: 8.6821,
    faq: [
      { q: "What group experiences are available in Frankfurt?", a: "TicketMatch.ai offers 2,400+ experiences in Frankfurt: Museumsufer museum tours, Römerberg walks, Main river cruises, apple wine tastings, Rhine Valley day trips, and more — at B2B group rates." },
      { q: "What is the Museumsufer in Frankfurt?", a: "The Museumsufer (Museum Embankment) is a stretch of 12+ world-class museums along the Main river. TicketMatch.ai offers group museum passes and guided tours at B2B rates." },
      { q: "What day trips are available from Frankfurt for groups?", a: "TicketMatch.ai offers Rhine Valley castle cruises, Heidelberg day trips, Rothenburg ob der Tauber medieval town visits, and Rüdesheim wine country tours — all at B2B group rates." },
      { q: "Is Frankfurt a good base for German group tours?", a: "Yes. Frankfurt is centrally located with Germany's largest airport and excellent train connections. It's the perfect base for Rhine Valley, Heidelberg, and Central German tours. TicketMatch.ai makes multi-city planning easy." },
    ],
  },
  {
    slug: "cologne",
    name: "Cologne",
    province: "North Rhine-Westphalia",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "2,200+",
    categories: 9,
    viatorDestId: 4374,
    tagline: "2,000 years of history crowned by a Gothic masterpiece",
    description:
      "Cologne (Köln) is one of Germany's oldest cities, crowned by its spectacular Gothic cathedral — a UNESCO World Heritage Site. With a vibrant art scene, famous Kölsch beer culture, and the Rhine riverfront, TicketMatch.ai provides B2B access to 2,200+ group experiences.",
    highlights: [
      "Cologne Cathedral — UNESCO Gothic masterpiece, Germany's most visited landmark (6M visitors/year)",
      "Museum Ludwig — World-class collection of modern art including Picasso, Warhol, and Lichtenstein",
      "Romano-Germanic Museum — 2,000 years of Roman history in Cologne",
      "Chocolate Museum — Interactive Lindt chocolate museum on the Rhine with group workshops",
      "Old Town (Altstadt) — Historic brewhouses, colourful buildings, and Kölsch beer culture",
      "Rhine River — Scenic cruises, riverside walks, and panoramic city views",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "45+", description: "Museum Ludwig, Romano-Germanic Museum, Wallraf-Richartz, NS Documentation Centre, and Chocolate Museum." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "70+", description: "Cathedral tours, Old Town walks, Kölsch brewery tours, Rhine cruises, and Roman history walks." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "40+", description: "Kölsch beer tours, brewery visits, Chocolate Museum workshops, and traditional Brauhaus dining." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Cologne Cathedral tower climb, Chocolate Museum, Cologne Zoo, and Rhine cable car." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "25+", description: "Museum Ludwig, Wallraf-Richartz, Kolumba art museum, street art, and gallery walks." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "15+", description: "Rhine river cruises, Rheinpark walks, cable car rides, and cycling along the Rhine." },
    ],
    geoLat: 50.9375,
    geoLon: 6.9603,
    faq: [
      { q: "What group experiences are available in Cologne?", a: "TicketMatch.ai offers 2,200+ experiences in Cologne: Cathedral tours, Kölsch brewery walks, Chocolate Museum visits, Rhine cruises, Museum Ludwig, and Old Town experiences — all at B2B group rates." },
      { q: "Can groups visit Cologne Cathedral?", a: "Yes. Cologne Cathedral is free to enter but TicketMatch.ai offers guided group tours, tower climb tickets, and combination packages with nearby museums — at exclusive B2B rates." },
      { q: "What is Kölsch and can groups do beer tours?", a: "Kölsch is Cologne's unique local beer, only brewed in Cologne. TicketMatch.ai offers guided brewery tours through traditional Brauhäuser, beer tasting walks, and group dining at historic brewhouses." },
      { q: "Can I combine Cologne with other German cities?", a: "Yes. Cologne connects to Düsseldorf (25 min), Bonn (20 min), and Aachen (45 min). TicketMatch.ai's package builder creates Rhine region multi-city group itineraries at B2B rates." },
    ],
  },
  {
    slug: "dresden",
    name: "Dresden",
    province: "Saxony",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "1,800+",
    categories: 8,
    viatorDestId: 4207,
    tagline: "The Florence on the Elbe — Baroque splendour reborn",
    description:
      "Dresden is known as 'Florence on the Elbe' for its stunning baroque architecture. Rebuilt after WWII, it's home to the Zwinger Palace, Semperoper opera house, and the world-famous Green Vault treasury. TicketMatch.ai provides B2B access to 1,800+ group experiences.",
    highlights: [
      "Zwinger Palace — Baroque masterpiece with Old Masters Gallery (Raphael's Sistine Madonna)",
      "Frauenkirche — Iconic domed church, rebuilt after WWII destruction as symbol of reconciliation",
      "Green Vault (Grünes Gewölbe) — Europe's richest treasury with 4,000+ precious objects",
      "Semperoper — One of the world's most beautiful opera houses with guided group tours",
      "Brühl's Terrace — 'The Balcony of Europe' overlooking the Elbe river",
      "Residenzschloss — Royal palace housing multiple museums and the Green Vault",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "35+", description: "Zwinger Old Masters Gallery, Green Vault, Military History Museum, Transport Museum, and Albertinum." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "55+", description: "Baroque old town walks, Elbe river cruises, Semperoper tours, and Saxon Switzerland day trips." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "30+", description: "Old Masters Gallery, Albertinum modern art, Semperoper, Kunsthofpassage, and gallery walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F3D4}\u{FE0F}", count: "25+", description: "Saxon Switzerland National Park, Meissen porcelain, Moritzburg Castle, and Bastei Bridge." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Frauenkirche dome climb, Green Vault, Panometer, and Transparent Factory (Volkswagen)." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "15+", description: "Saxon cuisine tours, Eierschecke (local cake), Neustadt food walks, and traditional beer gardens." },
    ],
    geoLat: 51.0504,
    geoLon: 13.7373,
    faq: [
      { q: "What group experiences are available in Dresden?", a: "TicketMatch.ai offers 1,800+ experiences in Dresden: Zwinger Palace tours, Green Vault visits, Frauenkirche, Semperoper, Elbe cruises, and Saxon Switzerland day trips — at B2B group rates." },
      { q: "What is the Green Vault in Dresden?", a: "The Green Vault (Grünes Gewölbe) is Europe's richest treasury with 4,000+ precious objects. TicketMatch.ai offers timed group entries to both the Historic and New Green Vault at B2B rates." },
      { q: "Can groups visit Saxon Switzerland from Dresden?", a: "Yes. Saxon Switzerland National Park with the famous Bastei Bridge is just 40 minutes from Dresden. TicketMatch.ai offers guided group day trips including hiking, boat rides, and fortress visits." },
      { q: "How far is Dresden from Berlin?", a: "Dresden is 2 hours from Berlin by ICE train. TicketMatch.ai makes combining both cities into one group itinerary simple with B2B rates for both destinations." },
    ],
  },
  {
    slug: "dusseldorf",
    name: "Düsseldorf",
    province: "North Rhine-Westphalia",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "1,500+",
    categories: 8,
    viatorDestId: 4208,
    tagline: "Fashion, art & the longest bar in the world",
    description:
      "Düsseldorf is Germany's fashion and art capital, home to the famous Königsallee shopping boulevard, a vibrant Altstadt (Old Town) known as 'the longest bar in the world', and world-class art museums. TicketMatch.ai provides B2B access to 1,500+ group experiences.",
    highlights: [
      "Altstadt — 'The longest bar in the world' with 260+ bars and restaurants in one square km",
      "Königsallee (Kö) — Germany's most elegant shopping boulevard along a tree-lined canal",
      "Kunstsammlung NRW — K20 and K21 modern art museums with Klee, Picasso, and video art",
      "MedienHafen — Transformed harbour with Frank Gehry's dancing buildings",
      "Rhine Tower — 240-meter telecommunications tower with revolving restaurant",
      "Schloss Benrath — Baroque pleasure palace with stunning gardens",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "25+", description: "Kunstsammlung NRW (K20/K21), Kunstpalast, Film Museum, Hetjens Museum, and more." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "45+", description: "Altstadt pub crawls, Kö fashion walks, Rhine cruises, MedienHafen architecture, and bike tours." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "30+", description: "Altbier brewery tours, Japanese quarter dining (Little Tokyo), Altstadt food walks, and craft beer tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Rhine Tower, Aquazoo, Schloss Benrath, and Gehry Buildings at MedienHafen." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "20+", description: "K20/K21 museums, Kunstpalast, NRW Forum photography, and contemporary gallery walks." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "10+", description: "Rhine promenade walks, Nordpark Japanese Garden, cycling tours, and river cruises." },
    ],
    geoLat: 51.2277,
    geoLon: 6.7735,
    faq: [
      { q: "What group experiences are available in Düsseldorf?", a: "TicketMatch.ai offers 1,500+ experiences in Düsseldorf: Altstadt pub crawls, Kö shopping tours, art museum visits, Rhine cruises, MedienHafen architecture tours, and more — at B2B group rates." },
      { q: "Why is Düsseldorf called 'the longest bar in the world'?", a: "Düsseldorf's Altstadt (Old Town) has 260+ bars and restaurants in one square kilometer. TicketMatch.ai offers guided group pub crawls through this famous district with Altbier tastings at B2B rates." },
      { q: "What art museums are available for groups in Düsseldorf?", a: "TicketMatch.ai provides group access to Kunstsammlung NRW (K20 modern art, K21 contemporary), Kunstpalast, and NRW Forum — all at B2B wholesale rates." },
      { q: "Can I combine Düsseldorf with Cologne for groups?", a: "Yes. Cologne is just 25 minutes from Düsseldorf by train. TicketMatch.ai's package builder makes Rhine region multi-city planning easy with B2B rates for both cities." },
    ],
  },
  {
    slug: "stuttgart",
    name: "Stuttgart",
    province: "Baden-Württemberg",
    country: "Germany",
    flag: "\u{1F1E9}\u{1F1EA}",
    experiences: "1,600+",
    categories: 8,
    viatorDestId: 4213,
    tagline: "Automotive capital of the world — Mercedes, Porsche & vineyards",
    description:
      "Stuttgart is the automotive capital of the world — home to Mercedes-Benz and Porsche. Surrounded by vineyards and nestled in a valley, it combines engineering excellence with Swabian culture and wine traditions. TicketMatch.ai provides B2B access to 1,600+ group experiences.",
    highlights: [
      "Mercedes-Benz Museum — 9 floors of automotive history from 1886 to today, 160 vehicles",
      "Porsche Museum — Sleek museum showcasing 80+ legendary Porsche vehicles",
      "Staatsgalerie — One of Germany's most visited art museums with old masters and modern art",
      "Wilhelma — Europe's only combined zoological-botanical garden with 11,000+ animals",
      "Stuttgart TV Tower — The world's first TV tower (1956), model for all that followed",
      "Schlossplatz — Central square with the New Palace and Jubilee Column",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "30+", description: "Mercedes-Benz Museum, Porsche Museum, Staatsgalerie, Linden Museum, and State Museum Württemberg." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "50+", description: "Automotive tours, vineyard walks, city history walks, and Black Forest day trips." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "30+", description: "Swabian cuisine tours, Markthalle visits, Stuttgart wine tours, and Spätzle cooking workshops." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "Mercedes-Benz Museum, Porsche Museum, Wilhelma Zoo, TV Tower, and Killesberg park." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F3D4}\u{FE0F}", count: "20+", description: "Black Forest tours, Heidelberg, Lake Constance, Hohenzollern Castle, and Tübingen." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "15+", description: "Staatsgalerie, Kunstmuseum, Stuttgart Ballet, and Weissenhof Estate (Le Corbusier)." },
    ],
    geoLat: 48.7758,
    geoLon: 9.1829,
    faq: [
      { q: "What group experiences are available in Stuttgart?", a: "TicketMatch.ai offers 1,600+ experiences in Stuttgart: Mercedes-Benz Museum, Porsche Museum, vineyard tours, Swabian food experiences, Black Forest day trips, and more — at B2B group rates." },
      { q: "Can groups visit both Mercedes and Porsche museums?", a: "Yes. TicketMatch.ai offers combo packages for both automotive museums at B2B group rates. The Mercedes-Benz Museum has 160 vehicles across 9 floors, while Porsche showcases 80+ legendary sports cars." },
      { q: "What day trips are available from Stuttgart?", a: "TicketMatch.ai offers Black Forest tours, Heidelberg castle visits, Lake Constance excursions, Hohenzollern Castle, and Tübingen university town trips — all at B2B group rates." },
      { q: "Is Stuttgart good for corporate group events?", a: "Absolutely. Stuttgart's automotive industry makes it ideal for corporate groups. TicketMatch.ai offers Mercedes-Benz and Porsche VIP experiences, innovation tours, and team building at vineyards." },
    ],
  },
];
