import type { CityData } from "./cities-data";

export const greekCities: CityData[] = [
  {
    slug: "athens",
    name: "Athens",
    province: "Attica",
    country: "Greece",
    flag: "\u{1F1EC}\u{1F1F7}",
    experiences: "3,600+",
    categories: 11,
    viatorDestId: 496,
    tagline: "Cradle of Western civilization — the Acropolis, mythology & Mediterranean soul",
    description:
      "Athens is where Western civilization began — a living museum of ancient temples, buzzing neighborhoods, and world-class cuisine. From the Acropolis to the Plaka, TicketMatch.ai provides B2B access to 3,600+ group experiences at exclusive rates.",
    highlights: [
      "Acropolis — The iconic hilltop citadel crowned by the Parthenon, symbol of ancient Greece",
      "Acropolis Museum — World-class museum housing the Parthenon marbles and ancient Greek treasures",
      "Plaka — Athens' oldest neighborhood with neoclassical houses, tavernas, and winding streets below the Acropolis",
      "Ancient Agora — The heart of ancient Athenian democracy with the Temple of Hephaestus",
      "Temple of Poseidon (Cape Sounion) — Dramatic clifftop temple overlooking the Aegean Sea at sunset",
      "Monastiraki Flea Market — Vibrant market district with antiques, street food, and Acropolis views",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "200+", description: "Acropolis guided tours, Plaka walks, mythology tours, street food crawls, and Athens by night." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "60+", description: "Acropolis, Ancient Agora, Temple of Zeus, Panathenaic Stadium, and National Garden." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "120+", description: "Greek cooking classes, taverna crawls, olive oil tastings, wine tours, and market walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "120+", description: "Delphi, Meteora, Cape Sounion, Saronic Islands (Hydra, Aegina), Corinth, and Mycenae." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "40+", description: "Acropolis Museum, National Archaeological Museum, Benaki Museum, and Museum of Cycladic Art." },
      { slug: "river-cruises", name: "Island Cruises", icon: "\u{1F6A2}", count: "40+", description: "Saronic Islands day cruises, Hydra + Poros + Aegina, sunset sailing, and catamaran tours." },
    ],
    geoLat: 37.9838,
    geoLon: 23.7275,
    faq: [
      { q: "What group experiences are available in Athens?", a: "TicketMatch.ai provides access to 3,600+ experiences: Acropolis tours, Greek cooking classes, Delphi & Meteora day trips, island cruises, and more — all at exclusive B2B group rates." },
      { q: "How do I book group Acropolis tickets?", a: "Through TicketMatch.ai, book group skip-the-line Acropolis tickets including guided tours, combined Acropolis + Museum packages, and multi-site archaeological passes at B2B rates." },
      { q: "Can I book Meteora day trips for groups?", a: "Yes. Meteora's stunning cliff-top monasteries are a full-day trip from Athens. TicketMatch.ai offers group tours with transport, monastery visits, and sunset options at B2B rates." },
      { q: "Is Athens good for group travel?", a: "Excellent. Athens is walkable, affordable, historically rich, and the gateway to the Greek islands. TicketMatch.ai helps plan combined Athens + island group itineraries." },
    ],
  },
  {
    slug: "santorini",
    name: "Santorini",
    province: "South Aegean",
    country: "Greece",
    flag: "\u{1F1EC}\u{1F1F7}",
    experiences: "1,800+",
    categories: 8,
    viatorDestId: 801,
    tagline: "The iconic caldera — blue domes, sunset & volcanic beauty",
    description:
      "Santorini is the world's most photographed island — a volcanic caldera of whitewashed villages, blue-domed churches, and legendary sunsets. TicketMatch.ai provides B2B access to 1,800+ group experiences at exclusive rates.",
    highlights: [
      "Oia — The iconic village of blue domes and the world's most famous sunset viewpoint",
      "Caldera — The dramatic volcanic crater with cliff-perched villages and deep blue waters",
      "Red Beach — Unique volcanic red sand beach near the ancient site of Akrotiri",
      "Akrotiri — 'The Greek Pompeii', a Minoan Bronze Age settlement preserved by volcanic eruption",
      "Fira — The island's capital perched on the caldera rim with museums, shops, and cable car",
      "Santo Wines — Cliffside winery with caldera views and Assyrtiko wine tastings",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Caldera walks, Oia sunset tours, village hopping, photography tours, and ATV adventures." },
      { slug: "river-cruises", name: "Boat Tours", icon: "\u{1F6A2}", count: "60+", description: "Caldera catamaran cruises, volcano & hot springs boats, sunset sailing, and fishing trips." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "50+", description: "Assyrtiko wine tastings, caldera-view dining, cooking classes, and food tours in Pyrgos." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "30+", description: "Fira-to-Oia caldera hike, Red Beach, kayaking, snorkeling, and volcano crater walks." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Akrotiri archaeological site, Fira cable car, Santo Wines, and volcanic islands." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "15+", description: "Volcano island, Thirassia, and combined caldera + volcano + hot springs tours." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "10+", description: "Akrotiri excavations, Museum of Prehistoric Thera, and traditional village cultural tours." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "5+", description: "Museum of Prehistoric Thera, Akrotiri site, and Wine Museum." },
    ],
    geoLat: 36.3932,
    geoLon: 25.4615,
    faq: [
      { q: "What group experiences are available in Santorini?", a: "TicketMatch.ai provides access to 1,800+ experiences: caldera cruises, wine tastings, Oia sunset tours, volcano visits, and more — all at exclusive B2B group rates." },
      { q: "Can groups do caldera boat tours?", a: "Yes. TicketMatch.ai offers group catamaran cruises, sailing tours, volcano + hot springs boats, and private charters with BBQ and drinks at B2B rates." },
      { q: "Is Santorini suitable for groups?", a: "Medium groups work best. Santorini's villages have narrow paths. TicketMatch.ai helps plan staggered visits, off-peak timing, and optimal boat + land combinations for groups." },
    ],
  },
];
