import type { CityData } from "./cities-data";

export const indianCities: CityData[] = [
  {
    slug: "delhi",
    name: "Delhi",
    province: "Delhi",
    country: "India",
    flag: "🇮🇳",
    experiences: "15,000+",
    categories: 10,
    viatorDestId: 804,
    tagline: "Seven Cities in One — Mughal grandeur, spice-filled lanes, and five millennia of living history",
    description:
      "Delhi is a staggering palimpsest of empires, where Mughal fortresses and Lutyens-era boulevards share the skyline with gleaming metro lines and chaotic bazaars. TicketMatch.ai provides B2B access to 15,000+ group experiences at exclusive rates across India's monumental capital.",
    highlights: [
      "Red Fort — The massive 17th-century Mughal sandstone fortress on the banks of the Yamuna, a UNESCO World Heritage Site",
      "Qutub Minar — The soaring 73-metre victory tower built in 1193, the tallest brick minaret in the world",
      "Humayun's Tomb — The stunning garden tomb that inspired the Taj Mahal, a masterpiece of early Mughal architecture",
      "India Gate — The 42-metre war memorial arch on Rajpath, Delhi's answer to the Arc de Triomphe",
      "Chandni Chowk — Old Delhi's legendary 17th-century market street, a sensory overload of spices, silver, and street food",
      "Jama Masjid — India's largest mosque, built by Shah Jahan in 1656, with capacity for 25,000 worshippers in its vast courtyard",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "3,000+", description: "Old Delhi rickshaw rides, New Delhi colonial walks, Mughal monument circuits, and sunrise Taj Mahal trips." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "4,000+", description: "Taj Mahal sunrise from Delhi, Jaipur pink city, Agra Fort, Mathura-Vrindavan, and Rishikesh yoga retreats." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "2,000+", description: "Chandni Chowk street food walks, Mughlai cooking classes, spice market tours, chai tastings, and fine-dining experiences." },
      { slug: "culture", name: "Culture & Arts", icon: "🎭", count: "1,500+", description: "Qawwali evenings at Nizamuddin, Sikh gurdwara visits, block-printing workshops, and classical dance performances." },
      { slug: "attractions", name: "Attractions", icon: "🎠", count: "1,500+", description: "Red Fort, Humayun's Tomb, Qutub Minar, Lotus Temple, Akshardham, and Rashtrapati Bhavan (Presidential Palace)." },
      { slug: "history", name: "History & Heritage", icon: "🏛️", count: "1,200+", description: "Mughal heritage trails, Partition Museum, Gandhi Smriti, National Museum, and archaeological site explorations." },
    ],
    geoLat: 28.7041,
    geoLon: 77.1025,
    faq: [
      { q: "What group experiences are available in Delhi?", a: "TicketMatch.ai provides access to 15,000+ experiences: Red Fort and Humayun's Tomb tours, Chandni Chowk food walks, Taj Mahal day trips, and cultural evenings — all at exclusive B2B group rates." },
      { q: "Can I book Taj Mahal day trips from Delhi for groups?", a: "Yes. TicketMatch.ai offers group sunrise and full-day Taj Mahal excursions from Delhi including Agra Fort visits — all at competitive B2B rates with private transport." },
      { q: "Are street food tours available for groups?", a: "Absolutely. TicketMatch.ai provides group Chandni Chowk food walks covering chole bhature, paranthas, jalebi, chaat, and more at B2B rates with expert local guides." },
      { q: "Is Delhi suitable for large group travel?", a: "Yes. Delhi has extensive infrastructure for groups with luxury coaches, experienced multilingual guides, and large venue capacity. TicketMatch.ai's B2B platform streamlines booking across all 15,000+ experiences." },
    ],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    province: "Rajasthan",
    country: "India",
    flag: "🇮🇳",
    experiences: "3,500+",
    categories: 8,
    viatorDestId: 4627,
    tagline: "The Pink City — maharaja palaces, hilltop forts, and Rajasthani splendour in terracotta hues",
    description:
      "Jaipur is the rose-tinted jewel of Rajasthan, a city of warrior forts perched on arid hills, opulent maharaja palaces, and bazaars overflowing with gemstones and block-print textiles. TicketMatch.ai provides B2B access to 3,500+ group experiences at exclusive rates.",
    highlights: [
      "Amber Fort — The majestic hilltop fortress of honey-coloured sandstone with mirror-mosaic halls and panoramic Aravalli views",
      "Hawa Mahal — The iconic pink sandstone Palace of Winds with 953 honeycomb windows designed for royal women to observe street life unseen",
      "City Palace — The sprawling palace complex still partially occupied by Jaipur's royal family, blending Rajput and Mughal architecture",
      "Jantar Mantar — The UNESCO-listed 18th-century astronomical observatory with the world's largest stone sundial",
      "Nahargarh Fort — The hilltop fortress offering dramatic sunset views over the entire pink city skyline",
      "Jal Mahal — The ethereal Water Palace floating serenely in the middle of Man Sagar Lake against the Aravalli backdrop",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "700+", description: "Amber Fort elephant and jeep rides, Pink City walking tours, palace circuit visits, and sunrise fort treks." },
      { slug: "culture", name: "Culture & Arts", icon: "🎭", count: "500+", description: "Block-printing workshops, gem-cutting demonstrations, puppet shows, folk dance evenings, and turban-tying classes." },
      { slug: "attractions", name: "Attractions", icon: "🎠", count: "400+", description: "Amber Fort, Hawa Mahal, City Palace, Jantar Mantar, Albert Hall Museum, and Birla Mandir." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "350+", description: "Rajasthani thali experiences, lassi tastings, spice market walks, rooftop Hawa Mahal dinners, and cooking classes." },
      { slug: "shopping", name: "Shopping", icon: "🛍️", count: "300+", description: "Johari Bazaar gem shopping, Bapu Bazaar textiles, blue pottery studios, and artisan workshop tours." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "500+", description: "Pushkar camel fair town, Ranthambore tiger safari, Ajmer Sharif dargah, Chand Baori stepwell, and Bhangarh ghost fort." },
    ],
    geoLat: 26.9124,
    geoLon: 75.7873,
    faq: [
      { q: "What group experiences are available in Jaipur?", a: "TicketMatch.ai provides access to 3,500+ experiences: Amber Fort tours, Hawa Mahal visits, block-printing workshops, Rajasthani dining, and Ranthambore safari day trips — all at exclusive B2B group rates." },
      { q: "Can I book fort and palace tours for groups?", a: "Yes. TicketMatch.ai offers group Amber Fort jeep rides, City Palace tours, Nahargarh sunset visits, and full pink city circuits — all at competitive B2B rates." },
      { q: "Are cultural workshops available for groups?", a: "Absolutely. TicketMatch.ai provides group block-printing, gem-cutting, pottery, and cooking workshops at B2B rates with expert artisan instructors." },
      { q: "Is Jaipur suitable for large group travel?", a: "Yes. Jaipur is a top group destination with heritage hotel ballrooms, experienced operators, and spacious fort grounds. TicketMatch.ai's B2B platform streamlines group booking and pricing." },
    ],
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    province: "Maharashtra",
    country: "India",
    flag: "🇮🇳",
    experiences: "900+",
    categories: 7,
    viatorDestId: 953,
    tagline: "City of Dreams — Bollywood glamour, colonial grandeur, and unstoppable street energy",
    description:
      "Mumbai is India's financial and entertainment capital, a city of stunning contrasts where Victorian Gothic architecture lines the waterfront and Bollywood studios churn out the world's largest film output. TicketMatch.ai provides B2B access to 900+ group experiences at exclusive rates.",
    highlights: [
      "Gateway of India — The grand basalt arch on Mumbai Harbour built in 1924 to commemorate King George V's visit, the city's defining landmark",
      "Dharavi (Slum Tour) — An eye-opening walk through one of Asia's largest slums revealing thriving micro-industries and remarkable community spirit",
      "Elephanta Caves — UNESCO-listed 5th-century rock-cut cave temples on an island in Mumbai Harbour, featuring a monumental Shiva sculpture",
      "Marine Drive — The sweeping 3.6-kilometre Art Deco seafront promenade nicknamed the Queen's Necklace for its glittering nighttime lights",
      "Chhatrapati Shivaji Terminus — The UNESCO-listed Victorian Gothic railway station, one of the most ornate functional buildings on Earth",
      "Dhobi Ghat — The world's largest open-air laundry where thousands of washermen clean Mumbai's clothes in a vast outdoor amphitheatre",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "200+", description: "Gateway of India walks, Dharavi community tours, Bollywood studio visits, and Art Deco heritage trails." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "150+", description: "Street food crawls through Mohammed Ali Road, vada pav tastings, seafood at Worli, and Parsi cafe experiences." },
      { slug: "culture", name: "Culture & Arts", icon: "🎭", count: "120+", description: "Bollywood dance workshops, Koli fishing village visits, temple tours, and contemporary art gallery walks." },
      { slug: "attractions", name: "Attractions", icon: "🎠", count: "100+", description: "Gateway of India, Elephanta Caves, Haji Ali Dargah, Sanjay Gandhi National Park, and Global Vipassana Pagoda." },
      { slug: "boat-tours", name: "Boat Tours", icon: "⛵", count: "80+", description: "Elephanta Caves ferry, Mumbai Harbour cruises, sunset yacht sailings, and Alibaug speedboat transfers." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "100+", description: "Elephanta Caves island, Lonavala hill station, Alibaug beaches, Khandala valleys, and Pune wine region." },
    ],
    geoLat: 19.0760,
    geoLon: 72.8777,
    faq: [
      { q: "What group experiences are available in Mumbai?", a: "TicketMatch.ai provides access to 900+ experiences: Gateway of India tours, Dharavi walks, Bollywood studio visits, Elephanta Caves ferries, and street food crawls — all at exclusive B2B group rates." },
      { q: "Can I book Bollywood experiences for groups?", a: "Yes. TicketMatch.ai offers group Bollywood studio tours, dance workshops, and film location visits — all at competitive B2B rates." },
      { q: "Are Elephanta Caves tours available for groups?", a: "Absolutely. TicketMatch.ai provides group ferry transfers and guided tours of the UNESCO Elephanta Caves at B2B rates." },
      { q: "Is Mumbai suitable for large group travel?", a: "Yes. Mumbai has experienced operators, large-capacity ferries, and diverse venue options. TicketMatch.ai's B2B platform makes group booking seamless with optimised pricing across all 900+ experiences." },
    ],
  },
];
