import type { CityData } from "./cities-data";

export const italianCities: CityData[] = [
  {
    slug: "rome",
    name: "Rome",
    province: "Lazio",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "7,800+",
    categories: 14,
    viatorDestId: 511,
    tagline: "The Eternal City — 2,800 years of history, art & la dolce vita",
    description:
      "Rome is the Eternal City where ancient ruins, Renaissance masterpieces, and vibrant street life collide at every turn. From the Colosseum and Vatican to Trastevere trattorias, TicketMatch.ai provides B2B access to 7,800+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Colosseum — The iconic 2,000-year-old amphitheatre, the largest ever built, seating 50,000 spectators",
      "Vatican Museums & Sistine Chapel — Michelangelo's ceiling masterpiece and 70,000+ artworks across 54 galleries",
      "St. Peter's Basilica — The world's largest church with Michelangelo's dome and Pietà",
      "Roman Forum — The political and social heart of ancient Rome with temples, arches, and basilicas",
      "Pantheon — The best-preserved ancient Roman building with its remarkable unreinforced concrete dome",
      "Trevi Fountain — Baroque masterpiece and Rome's largest fountain, tradition says toss a coin to return",
      "Spanish Steps — Iconic 135-step stairway connecting Piazza di Spagna to Trinità dei Monti church",
      "Borghese Gallery — Bernini and Caravaggio masterpieces in a stunning 17th-century villa",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "250+", description: "Vatican Museums, Borghese Gallery, Capitoline Museums, MAXXI, Palazzo Barberini, and 200+ more at B2B group rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "400+", description: "Colosseum tours, Vatican guided visits, catacombs, ancient Rome walks, Trastevere evening tours, and vespa rides." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "150+", description: "Colosseum, Vatican, Pantheon, Trevi Fountain, Spanish Steps, Castel Sant'Angelo, and Appian Way." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "200+", description: "Trastevere food tours, pasta-making classes, wine tastings, gelato tours, pizza workshops, and market walks in Testaccio." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "120+", description: "Pompeii & Amalfi Coast, Tivoli (Villa d'Este & Hadrian's Villa), Florence, Naples, Orvieto, and Castelli Romani." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "60+", description: "Appian Way cycling, Villa Borghese gardens, Tiber river cruises, and rooftop terrace experiences." },
    ],
    geoLat: 41.9028,
    geoLon: 12.4964,
    faq: [
      { q: "What group experiences are available in Rome?", a: "TicketMatch.ai provides access to 7,800+ experiences: skip-the-line Colosseum and Vatican tours, Sistine Chapel visits, pasta-making classes, Pompeii day trips, and more — all at exclusive B2B group rates." },
      { q: "How do I book group Vatican tickets?", a: "Through TicketMatch.ai, book group skip-the-line Vatican Museum + Sistine Chapel tickets, St. Peter's Basilica dome access, papal audience seats, and early-morning or after-hours visits at wholesale B2B rates." },
      { q: "Can I book Pompeii day trips from Rome for groups?", a: "Yes. TicketMatch.ai offers group day trips from Rome to Pompeii (2h by train), including guided excavation tours, combined Pompeii + Amalfi Coast, and Pompeii + Naples packages at B2B rates." },
      { q: "Is Rome suitable for large group travel?", a: "Absolutely. Rome has extensive public transport, thousands of group-ready venues, and multilingual guides. TicketMatch.ai's busyness data helps avoid peak hours at the Colosseum and Vatican." },
      { q: "What food experiences are available for groups?", a: "Rome is a food lover's paradise. Group experiences include pasta-making in Trastevere, Testaccio market tours, pizza workshops, gelato tastings, and wine dinners in ancient cellars — all at B2B rates." },
    ],
  },
  {
    slug: "florence",
    name: "Florence",
    province: "Tuscany",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "4,500+",
    categories: 12,
    viatorDestId: 512,
    tagline: "Cradle of the Renaissance — art, Tuscan wine & timeless beauty",
    description:
      "Florence is the birthplace of the Renaissance, a living museum where Michelangelo's David, Brunelleschi's dome, and the Uffizi Gallery define Western art. Surrounded by Tuscan vineyards, TicketMatch.ai provides B2B access to 4,500+ group experiences at exclusive rates.",
    highlights: [
      "Uffizi Gallery — The world's greatest collection of Renaissance art, from Botticelli to Leonardo da Vinci",
      "Accademia Gallery — Home to Michelangelo's David, the world's most famous sculpture",
      "Florence Cathedral (Duomo) — Brunelleschi's iconic red-tiled dome dominating the Florentine skyline",
      "Ponte Vecchio — The medieval bridge lined with goldsmith shops spanning the Arno since 1345",
      "Palazzo Pitti & Boboli Gardens — Grand ducal palace with Renaissance gardens and multiple museums",
      "Piazzale Michelangelo — The panoramic terrace with the most famous view of Florence",
      "San Lorenzo Market — The bustling leather market and food hall in Florence's historic center",
      "Palazzo Vecchio — Florence's town hall since 1299, with richly decorated chambers and tower views",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "150+", description: "Uffizi, Accademia (David), Palazzo Pitti, Bargello, San Marco, Medici Chapels, and 120+ more at B2B group rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "250+", description: "Duomo dome climbs, Renaissance art walks, Oltrarno artisan tours, Medici family tours, and sunset walks." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "180+", description: "Tuscan cooking classes, Chianti wine tours, truffle hunting, gelato-making, bistecca fiorentina dinners, and olive oil tastings." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "150+", description: "Chianti wine region, Siena, San Gimignano, Pisa, Cinque Terre, Lucca, and Val d'Orcia." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "80+", description: "Duomo complex, Ponte Vecchio, Palazzo Vecchio, Piazzale Michelangelo, Boboli Gardens, and Basilica di Santa Croce." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "70+", description: "Renaissance art workshops, leather-making, perfume creation, mosaic classes, and Florentine paper marbling." },
    ],
    geoLat: 43.7696,
    geoLon: 11.2558,
    faq: [
      { q: "What group experiences are available in Florence?", a: "TicketMatch.ai provides access to 4,500+ experiences: Uffizi and Accademia tours, Duomo dome climbs, Chianti wine trips, cooking classes, and more — all at exclusive B2B group rates." },
      { q: "How do I book group Uffizi tickets?", a: "Through TicketMatch.ai, book group skip-the-line Uffizi tickets including guided tours, combined Uffizi + Accademia packages, and early-entry visits at wholesale B2B rates." },
      { q: "Can I book Chianti wine tours for groups?", a: "Yes. TicketMatch.ai offers group Chianti excursions: vineyard visits, castle tastings, olive oil mills, combined wine + cooking experiences, and full-day Tuscan countryside tours at B2B rates." },
      { q: "Is Florence good for group travel?", a: "Excellent. Florence's compact center is entirely walkable, filled with world-class art and surrounded by Tuscan wine country. TicketMatch.ai helps plan combined Florence + Tuscany group itineraries." },
    ],
  },
  {
    slug: "venice",
    name: "Venice",
    province: "Veneto",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "3,800+",
    categories: 11,
    viatorDestId: 513,
    tagline: "The floating city — canals, gondolas & centuries of splendor",
    description:
      "Venice is unlike any place on Earth — a floating city of 118 islands connected by 400 bridges, where gondolas glide through historic canals past Byzantine and Gothic palaces. TicketMatch.ai provides B2B access to 3,800+ group experiences at exclusive rates.",
    highlights: [
      "St. Mark's Basilica — Byzantine golden-mosaic masterpiece on Piazza San Marco",
      "Doge's Palace — Gothic masterpiece and former seat of Venetian power with the Bridge of Sighs",
      "Grand Canal — Venice's main waterway lined with 170+ palaces, best seen by vaporetto or gondola",
      "Rialto Bridge — The oldest and most famous of the four bridges spanning the Grand Canal",
      "Murano — The island famous for centuries of exquisite glass-making tradition",
      "Burano — The colorful fishing island known for vibrant houses and delicate lacework",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "220+", description: "St. Mark's guided tours, Doge's Palace secret passages, gondola rides, walking tours, and ghost tours of Venice." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "80+", description: "St. Mark's Basilica, Doge's Palace, Rialto Bridge, Campanile tower, La Fenice opera house, and Peggy Guggenheim." },
      { slug: "river-cruises", name: "Boat Tours", icon: "\u{1F6A2}", count: "100+", description: "Grand Canal vaporetto, gondola rides, lagoon cruises, Murano & Burano island hopping, and sunset boat tours." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "90+", description: "Cicchetti bar crawls, Rialto market tours, pasta-making, Prosecco tastings, and bacaro hopping in Cannaregio." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "Murano, Burano & Torcello islands, Prosecco hills, Verona, Padua, Dolomites, and Palladian villas." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "60+", description: "Peggy Guggenheim, Gallerie dell'Accademia, Ca' Rezzonico, Correr Museum, and Naval History Museum." },
    ],
    geoLat: 45.4408,
    geoLon: 12.3155,
    faq: [
      { q: "What group experiences are available in Venice?", a: "TicketMatch.ai provides access to 3,800+ experiences: St. Mark's tours, gondola rides, Murano glass-making, Doge's Palace, lagoon cruises, and more — all at exclusive B2B group rates." },
      { q: "How do I book group gondola rides?", a: "TicketMatch.ai offers group gondola experiences: shared and private gondolas, Grand Canal rides, serenade gondolas, and combined gondola + walking tour packages at B2B rates." },
      { q: "Can I book Murano and Burano for groups?", a: "Yes. TicketMatch.ai offers group boat tours to Murano (glass-blowing demos), Burano (colorful houses & lace), and Torcello — half-day and full-day options at B2B rates." },
      { q: "Is Venice manageable for group travel?", a: "Yes, with planning. Venice is pedestrian-only and uses water transport. TicketMatch.ai's busyness data helps avoid peak times at St. Mark's and provides optimal routes for group visits." },
    ],
  },
  {
    slug: "milan",
    name: "Milan",
    province: "Lombardy",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "3,200+",
    categories: 11,
    viatorDestId: 514,
    tagline: "Fashion & design capital — Da Vinci's Last Supper & modern Italy",
    description:
      "Milan is Italy's sleek, modern capital of fashion, design, and business, yet hides Renaissance treasures like Leonardo's Last Supper and the majestic Duomo. TicketMatch.ai provides B2B access to 3,200+ group experiences at exclusive rates.",
    highlights: [
      "Milan Cathedral (Duomo) — Italy's largest church with rooftop terraces and 3,400 statues",
      "The Last Supper — Leonardo da Vinci's masterpiece in Santa Maria delle Grazie (UNESCO)",
      "Galleria Vittorio Emanuele II — Italy's oldest shopping gallery, the 'living room of Milan'",
      "La Scala — The world's most prestigious opera house, opened in 1778",
      "Navigli District — Historic canal district with art galleries, bars, and antique markets",
      "Pinacoteca di Brera — Milan's premier art gallery with Raphael, Caravaggio, and Mantegna",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "180+", description: "Duomo rooftop tours, Last Supper visits, fashion district walks, Navigli canal tours, and Milan by night." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "80+", description: "Pinacoteca di Brera, La Scala Museum, Museo del Novecento, Leonardo da Vinci Museum, and Fondazione Prada." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "60+", description: "Duomo terraces, Galleria, La Scala, Sforza Castle, San Siro Stadium, and Cimitero Monumentale." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Aperitivo in Navigli, risotto cooking classes, Milanese food tours, wine tastings, and market visits at Mercato Centrale." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "100+", description: "Lake Como, Lake Garda, Cinque Terre, Bergamo, Verona, Franciacorta wine region, and Swiss Alps." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "50+", description: "Fashion district tours, design showroom visits, La Scala opera, contemporary art at Fondazione Prada, and street art in Isola." },
    ],
    geoLat: 45.4642,
    geoLon: 9.1900,
    faq: [
      { q: "What group experiences are available in Milan?", a: "TicketMatch.ai provides access to 3,200+ experiences: Last Supper tours, Duomo rooftop, Lake Como day trips, fashion walks, and more — all at exclusive B2B group rates." },
      { q: "How do I book Last Supper tickets for groups?", a: "Last Supper tickets are extremely limited (max 25 people per 15-min slot). TicketMatch.ai secures group allocations well in advance at B2B rates, including guided tours with art historian." },
      { q: "Can I book Lake Como day trips for groups?", a: "Yes. TicketMatch.ai offers group Lake Como excursions: Bellagio visits, villa tours, boat cruises, combined Lake Como + Lugano, and luxury experiences at B2B rates." },
      { q: "Is Milan good for group travel?", a: "Excellent. Milan has Italy's best public transport, a compact center, world-class dining, and is the gateway to the Italian Lakes and Alps. TicketMatch.ai helps plan northern Italy group itineraries." },
    ],
  },
  {
    slug: "naples",
    name: "Naples",
    province: "Campania",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "2,800+",
    categories: 10,
    viatorDestId: 515,
    tagline: "Birthplace of pizza — Pompeii, Vesuvius & the Amalfi Coast",
    description:
      "Naples is raw, authentic Italy at its most vibrant — the birthplace of pizza, gateway to Pompeii and the Amalfi Coast, and a treasure trove of underground Greek and Roman ruins. TicketMatch.ai provides B2B access to 2,800+ group experiences at exclusive rates.",
    highlights: [
      "Pompeii — The ancient Roman city frozen in time by Vesuvius' 79 AD eruption, a UNESCO World Heritage site",
      "Amalfi Coast — Dramatic coastal road connecting Positano, Amalfi, and Ravello (UNESCO)",
      "Mount Vesuvius — The only active volcano on mainland Europe, hikeable to the crater rim",
      "Naples Underground (Napoli Sotterranea) — Ancient Greek-Roman tunnels and cisterns beneath the city",
      "National Archaeological Museum — World's finest collection of Greco-Roman antiquities and Pompeii mosaics",
      "Spaccanapoli — The arrow-straight ancient Greek street splitting Naples' historic center in two",
    ],
    topCategories: [
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "180+", description: "Pompeii, Amalfi Coast (Positano, Ravello), Capri, Mount Vesuvius, Herculaneum, Sorrento, and Ischia." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "150+", description: "Naples underground tours, Spaccanapoli walks, Vesuvius hikes, Pompeii guided tours, and street art tours." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Pizza-making classes, street food tours (pizza fritta, sfogliatella), limoncello tastings, and Neapolitan pastry workshops." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "50+", description: "Pompeii ruins, Castel dell'Ovo, Royal Palace, Naples Cathedral, and San Severo Chapel (Veiled Christ)." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "40+", description: "National Archaeological Museum, Capodimonte, MADRE contemporary art, Certosa di San Martino, and underground ruins." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "40+", description: "Vesuvius crater hike, Amalfi Coast boat tours, Capri Blue Grotto, kayaking, and Path of the Gods hiking." },
    ],
    geoLat: 40.8518,
    geoLon: 14.2681,
    faq: [
      { q: "What group experiences are available in Naples?", a: "TicketMatch.ai provides access to 2,800+ experiences: Pompeii tours, Amalfi Coast trips, Vesuvius hikes, pizza-making classes, Capri boats, and more — all at exclusive B2B group rates." },
      { q: "Can I book Pompeii and Amalfi Coast for groups?", a: "Yes. TicketMatch.ai offers combined Pompeii + Amalfi Coast group day trips, separate half-day options, and multi-day packages. Private guides and transport at B2B rates." },
      { q: "What food experiences are available in Naples?", a: "Naples invented pizza. TicketMatch.ai offers group pizza-making classes, street food tours, sfogliatella workshops, limoncello tastings, and market walks in Pignasecca — all at B2B rates." },
      { q: "Is Naples a good base for group travel?", a: "Perfect. Naples is the gateway to Pompeii, Amalfi Coast, Capri, Vesuvius, Sorrento, and Herculaneum. TicketMatch.ai helps plan multi-day Campania group itineraries at B2B rates." },
    ],
  },
  {
    slug: "turin",
    name: "Turin",
    province: "Piedmont",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "1,600+",
    categories: 9,
    viatorDestId: 4947,
    tagline: "Italy's first capital — Baroque elegance, chocolate & the Alps",
    description:
      "Turin is Italy's elegant former capital, a city of grand Baroque arcades, world-class museums, and the gateway to the Italian Alps. Famous for chocolate, Fiat, and the Shroud of Turin, TicketMatch.ai provides B2B access to 1,600+ group experiences at exclusive rates.",
    highlights: [
      "Egyptian Museum — The world's second-largest Egyptian collection after Cairo, fully renovated",
      "Mole Antonelliana — Turin's iconic 167-meter landmark housing the National Cinema Museum",
      "Royal Palace of Turin — UNESCO Savoy residence with Royal Armoury and Chapel of the Holy Shroud",
      "Piazza San Carlo — Turin's elegant 'drawing room' surrounded by Baroque churches and historic cafés",
      "Lingotto — Former Fiat factory with rooftop test track, now a cultural and shopping center",
      "Superga Basilica — Hilltop church with panoramic views of Turin and the Alpine chain",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "50+", description: "Egyptian Museum, Cinema Museum (Mole), Royal Palace, Automobile Museum, GAM modern art, and Palazzo Madama." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Baroque arcade walks, Royal Turin tours, chocolate tastings, vermouth bars, and underground Turin." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "60+", description: "Chocolate tours (gianduja, bicerin), vermouth tastings, Piedmont truffle hunts, Barolo wine tours, and market visits." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "50+", description: "Barolo & Langhe wine region, Alba (truffles), Italian Alps ski resorts, Sacra di San Michele, and Lake Orta." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Mole Antonelliana, Royal Palace, Superga Basilica, Venaria Reale (Italy's Versailles), and Parco del Valentino." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "20+", description: "Po river walks, Alpine day trips, Superga hill funicular, Valentino Park, and cycling in the Langhe." },
    ],
    geoLat: 45.0703,
    geoLon: 7.6869,
    faq: [
      { q: "What group experiences are available in Turin?", a: "TicketMatch.ai provides access to 1,600+ experiences: Egyptian Museum, Cinema Museum, chocolate tours, Barolo wine trips, and more — all at exclusive B2B group rates." },
      { q: "Why is Turin famous for chocolate?", a: "Turin is Italy's chocolate capital — home to gianduja (chocolate-hazelnut), bicerin (chocolate-coffee drink), and historic chocolatiers since the 1700s. TicketMatch.ai offers group chocolate tours at B2B rates." },
      { q: "Can I book wine tours from Turin?", a: "Yes. The Langhe and Barolo region is 1 hour from Turin. TicketMatch.ai offers group vineyard tours, Barolo tastings, Alba truffle hunts, and combined wine + food experiences at B2B rates." },
      { q: "Is Turin good for group travel?", a: "Excellent. Turin is underrated and uncrowded compared to Rome/Florence, with world-class museums, elegant architecture, and proximity to the Alps and Piedmont wine country." },
    ],
  },
  {
    slug: "cinque-terre",
    name: "Cinque Terre",
    province: "Liguria",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "1,200+",
    categories: 7,
    viatorDestId: 5765,
    tagline: "Five colorful fishing villages clinging to the Italian Riviera cliffs",
    description:
      "Cinque Terre is one of Italy's most breathtaking destinations — five pastel-colored fishing villages (Monterosso, Vernazza, Corniglia, Manarola, Riomaggiore) perched on dramatic Ligurian Sea cliffs. TicketMatch.ai provides B2B access to 1,200+ group experiences at exclusive rates.",
    highlights: [
      "Vernazza — The most photogenic village with its colorful harbor, castle, and church tower",
      "Manarola — Famous for its stacked houses on steep cliffs and dramatic sea views",
      "Monterosso al Mare — The largest village with the only sandy beach and excellent seafood restaurants",
      "Corniglia — The only hilltop village, reached by 382 steps (the Lardarina), surrounded by vineyards",
      "Riomaggiore — The southernmost village with Via dell'Amore and pastel houses cascading to the sea",
      "Sentiero Azzurro (Blue Trail) — The famous coastal hiking trail connecting all five villages",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "60+", description: "Five-village walking tours, guided hikes between villages, boat tours along the coast, and photography tours." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "50+", description: "Blue Trail hiking, coastal kayaking, swimming, snorkeling, vineyard walks, and sunset boat rides." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "40+", description: "Pesto-making classes, Sciacchetrà wine tastings, seafood cooking, focaccia workshops, and limoncino tastings." },
      { slug: "river-cruises", name: "Boat Tours", icon: "\u{1F6A2}", count: "30+", description: "Coastal boat tours between villages, sunset cruises, fishing boat experiences, and Portovenere excursions." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "25+", description: "Portovenere, Portofino, Lerici, La Spezia, and combined Cinque Terre + Pisa day trips." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "15+", description: "Vernazza castle, Monterosso giant statue, Manarola nativity scene, and village churches." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "10+", description: "Traditional fishing village life, vineyard heritage tours, and local artisan workshops." },
    ],
    geoLat: 44.1461,
    geoLon: 9.6439,
    faq: [
      { q: "What group experiences are available in Cinque Terre?", a: "TicketMatch.ai provides access to 1,200+ experiences: guided village tours, coastal hikes, boat trips, pesto-making classes, wine tastings, and more — all at exclusive B2B group rates." },
      { q: "Can groups hike between the five villages?", a: "Yes. The Sentiero Azzurro (Blue Trail) connects all five villages. TicketMatch.ai offers guided group hikes with local experts, including combined hike + boat return packages at B2B rates." },
      { q: "What is the best way for groups to visit Cinque Terre?", a: "By train (5-10 min between villages) or boat. TicketMatch.ai offers group day trips from Florence, Milan, and Pisa, as well as multi-day Cinque Terre packages at B2B rates." },
      { q: "Is Cinque Terre suitable for large groups?", a: "Medium-sized groups work best (max 20-25). Villages are small and paths narrow. TicketMatch.ai helps plan staggered visits and optimal timing to avoid overcrowding." },
    ],
  },
  {
    slug: "amalfi-coast",
    name: "Amalfi Coast",
    province: "Campania",
    country: "Italy",
    flag: "\u{1F1EE}\u{1F1F9}",
    experiences: "1,500+",
    categories: 8,
    viatorDestId: 4807,
    tagline: "UNESCO coastal paradise — Positano, Amalfi & Ravello",
    description:
      "The Amalfi Coast is Italy's most glamorous coastline — a UNESCO World Heritage stretch of dramatic cliffs, pastel villages, and azure waters. From Positano to Ravello, TicketMatch.ai provides B2B access to 1,500+ group experiences at exclusive rates.",
    highlights: [
      "Positano — The most iconic Amalfi Coast village with cascading pastel houses and pebble beaches",
      "Amalfi — Historic maritime republic with a stunning 9th-century cathedral and paper-making heritage",
      "Ravello — Hilltop town famous for Villa Rufolo gardens and its summer music festival",
      "Path of the Gods (Sentiero degli Dei) — Spectacular cliffside hiking trail with panoramic sea views",
      "Emerald Grotto (Grotta dello Smeraldo) — Sea cave with ethereal emerald-green waters near Conca dei Marini",
      "Capri — The glamorous island just offshore with the Blue Grotto, Monte Solaro, and designer shopping",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "100+", description: "Positano walks, Amalfi Cathedral visits, Ravello villa tours, scenic drive tours, and Vespa rentals." },
      { slug: "river-cruises", name: "Boat Tours", icon: "\u{1F6A2}", count: "80+", description: "Coast-hopping boats, Capri day trips, sunset cruises, private yacht charters, and fishing village excursions." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "70+", description: "Limoncello tastings, coastal cooking classes, pizza workshops, lemon grove visits, and seafood dining." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "50+", description: "Path of the Gods hiking, kayaking, snorkeling, diving, and beach hopping." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "60+", description: "Capri island, Pompeii, Naples, Sorrento, Ischia, and Paestum Greek temples." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Amalfi Cathedral, Villa Rufolo, Villa Cimbrone, Emerald Grotto, and Fiordo di Furore." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "20+", description: "Paper-making in Amalfi, ceramic workshops in Vietri, Ravello Festival, and local artisan visits." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "10+", description: "Paper Museum (Amalfi), Arsenale Museum, Villa Rufolo exhibits, and Correale Museum (Sorrento)." },
    ],
    geoLat: 40.6340,
    geoLon: 14.6027,
    faq: [
      { q: "What group experiences are available on the Amalfi Coast?", a: "TicketMatch.ai provides access to 1,500+ experiences: Positano tours, Capri boat trips, Path of the Gods hikes, limoncello tastings, cooking classes, and more — all at exclusive B2B group rates." },
      { q: "How do groups travel along the Amalfi Coast?", a: "By private coach, boat, or ferry. TicketMatch.ai offers group transport with knowledgeable drivers on the famous coastal road, plus boat-hopping packages between villages at B2B rates." },
      { q: "Can I combine Amalfi Coast with Pompeii?", a: "Yes. TicketMatch.ai offers combined Pompeii + Amalfi Coast group day trips from Naples or Sorrento, with guided Pompeii tours and coastal drives at B2B rates." },
      { q: "What is the best season for Amalfi Coast groups?", a: "April-June and September-October offer the best weather with fewer crowds. TicketMatch.ai's busyness data helps plan optimal visit times for Positano and Amalfi." },
    ],
  },
];
