import type { CityData } from "./cities-data";

export const japaneseCities: CityData[] = [
  {
    slug: "tokyo",
    name: "Tokyo",
    province: "Tokyo",
    country: "Japan",
    flag: "🇯🇵",
    experiences: "3,800+",
    categories: 10,
    viatorDestId: 334,
    tagline: "Neon and Tradition — the world's largest metropolis where ancient shrines hide among skyscrapers",
    description:
      "Tokyo is a mesmerising collision of ultra-modern innovation and centuries-old tradition, from the neon canyons of Shinjuku to the tranquil gardens of Meiji Shrine. TicketMatch.ai provides B2B access to 3,800+ group experiences at exclusive rates across this extraordinary capital.",
    highlights: [
      "Senso-ji Temple — Tokyo's oldest Buddhist temple in Asakusa, entered through the iconic Kaminarimon thunder gate",
      "Shibuya Crossing — The world's busiest pedestrian intersection, a mesmerising scramble of up to 3,000 people per light change",
      "Meiji Shrine — A serene Shinto sanctuary nestled within 170 acres of old-growth forest in the heart of Harajuku",
      "Tokyo Skytree — The world's tallest broadcasting tower at 634 metres with observation decks offering 360-degree city views",
      "Tsukiji Outer Market — The legendary food market with hundreds of stalls serving the freshest sushi, tamagoyaki, and street eats",
      "Akihabara — Tokyo's electric town and global epicentre of anime, manga, gaming arcades, and otaku culture",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "600+", description: "Guided walks through Asakusa, Harajuku, Shinjuku, and Shibuya — including skip-the-line shrine and palace tours." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "500+", description: "Tsukiji market tastings, ramen crawls, sushi-making workshops, sake brewery visits, and izakaya hopping tours." },
      { slug: "attractions", name: "Attractions", icon: "🎠", count: "400+", description: "Tokyo Skytree, teamLab exhibitions, Imperial Palace, Senso-ji, Robot Restaurant, and Tokyo Tower." },
      { slug: "culture", name: "Culture & Arts", icon: "🎭", count: "350+", description: "Tea ceremonies, kimono rental experiences, calligraphy workshops, kabuki theatre, and sumo tournament viewings." },
      { slug: "nightlife", name: "Nightlife", icon: "🌃", count: "250+", description: "Golden Gai bar hopping, Roppongi club nights, karaoke experiences, Omoide Yokocho, and neon-lit city tours." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "300+", description: "Mount Fuji excursions, Hakone hot springs, Kamakura Great Buddha, Nikko shrines, and Yokohama Chinatown." },
    ],
    geoLat: 35.6762,
    geoLon: 139.6503,
    faq: [
      { q: "What group experiences are available in Tokyo?", a: "TicketMatch.ai provides access to 3,800+ experiences: Senso-ji and Meiji Shrine tours, Tsukiji market tastings, tea ceremonies, Tokyo Skytree visits, and Mount Fuji day trips — all at exclusive B2B group rates." },
      { q: "Can I book food tours for groups in Tokyo?", a: "Yes. TicketMatch.ai offers group food tours including Tsukiji market tastings, ramen crawls, sushi-making classes, sake brewery visits, and izakaya hopping — all at competitive B2B rates." },
      { q: "Are day trips to Mount Fuji available for groups?", a: "Absolutely. TicketMatch.ai provides group day trips to Mount Fuji, Hakone, Kamakura, and Nikko from Tokyo at B2B rates with experienced English-speaking guides." },
      { q: "Is Tokyo suitable for large group travel?", a: "Yes. Tokyo has world-class transport, multilingual guides, and large-capacity venues. TicketMatch.ai's B2B platform streamlines booking across all 3,800+ experiences with group-optimised pricing." },
    ],
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    province: "Kyoto",
    country: "Japan",
    flag: "🇯🇵",
    experiences: "1,400+",
    categories: 8,
    viatorDestId: 332,
    tagline: "Japan's Cultural Soul — thousand temples, geisha twilight, and bamboo whispers",
    description:
      "Kyoto is the spiritual heart of Japan, a city of over 2,000 temples and shrines, immaculate Zen gardens, and living geisha traditions preserved across centuries. TicketMatch.ai provides B2B access to 1,400+ group experiences at exclusive rates in this timeless former imperial capital.",
    highlights: [
      "Fushimi Inari — Thousands of vermilion torii gates marching up the mountainside in Japan's most photographed shrine",
      "Kinkaku-ji (Golden Pavilion) — The dazzling gold-leaf Zen temple reflected perfectly in its mirror-still pond",
      "Arashiyama Bamboo Grove — A towering cathedral of swaying green bamboo stalks creating an otherworldly natural corridor",
      "Kiyomizu-dera — The gravity-defying wooden terrace temple perched on a hillside with sweeping views over cherry blossom valleys",
      "Gion Geisha District — Kyoto's atmospheric historic quarter where geiko and maiko glide along lantern-lit stone lanes at dusk",
      "Nijo Castle — The UNESCO-listed Tokugawa shogunate fortress famous for its nightingale squeaking floors and ornate sliding doors",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "250+", description: "Guided temple circuits, Fushimi Inari early-morning walks, Gion evening strolls, and Philosopher's Path explorations." },
      { slug: "culture", name: "Culture & Arts", icon: "🎭", count: "200+", description: "Tea ceremonies, geisha encounters, kimono dressing, Zen meditation, ikebana, and traditional craft workshops." },
      { slug: "attractions", name: "Attractions", icon: "🎠", count: "180+", description: "Kinkaku-ji, Kiyomizu-dera, Nijo Castle, Ryoan-ji rock garden, Silver Pavilion, and Imperial Palace." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "200+", description: "Kaiseki dining, Nishiki Market tastings, matcha workshops, sake tastings, and tofu cuisine experiences." },
      { slug: "nature", name: "Nature & Gardens", icon: "🌸", count: "150+", description: "Arashiyama bamboo walks, cherry blossom viewings, autumn foliage tours, moss temple visits, and zen garden meditations." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "120+", description: "Nara deer park, Osaka day trips, Uji tea village, Mount Hiei, and Amanohashidate scenic views." },
    ],
    geoLat: 35.0116,
    geoLon: 135.7681,
    faq: [
      { q: "What group experiences are available in Kyoto?", a: "TicketMatch.ai provides access to 1,400+ experiences: Fushimi Inari and Golden Pavilion tours, tea ceremonies, geisha district walks, bamboo grove visits, and Nara day trips — all at exclusive B2B group rates." },
      { q: "Can I book cultural experiences for groups?", a: "Yes. TicketMatch.ai offers group tea ceremonies, kimono dressing, geisha encounters, Zen meditation sessions, and traditional craft workshops — all at competitive B2B rates." },
      { q: "Are temple tours available for groups?", a: "Absolutely. TicketMatch.ai provides guided group tours of Kyoto's top temples and shrines including Fushimi Inari, Kinkaku-ji, Kiyomizu-dera, and Nijo Castle at B2B rates." },
      { q: "Is Kyoto suitable for large group travel?", a: "Yes. Kyoto is experienced in handling group tourism with dedicated operators, chartered buses, and spacious temple grounds. TicketMatch.ai's B2B platform ensures seamless group booking and pricing." },
    ],
  },
  {
    slug: "osaka",
    name: "Osaka",
    province: "Osaka",
    country: "Japan",
    flag: "🇯🇵",
    experiences: "1,000+",
    categories: 8,
    viatorDestId: 333,
    tagline: "Japan's Kitchen — neon-lit street food alleys, bold flavours, and unstoppable energy",
    description:
      "Osaka is Japan's culinary capital and comedy heartland, a city that lives to eat and knows how to have fun. From the dazzling Dotonbori canal to the majestic Osaka Castle, TicketMatch.ai provides B2B access to 1,000+ group experiences at exclusive rates.",
    highlights: [
      "Osaka Castle — The iconic 16th-century fortress surrounded by moats and cherry trees, with panoramic city views from its tower",
      "Dotonbori — The legendary neon-drenched canal street lined with giant 3D signs, takoyaki stalls, and raucous energy",
      "Universal Studios Japan — One of Asia's most popular theme parks with Wizarding World of Harry Potter and Nintendo World",
      "Shinsekai — The retro downtown district centred on the Tsutenkaku Tower, famous for kushikatsu skewers and nostalgic charm",
      "Kuromon Market — Osaka's 190-year-old covered market known as the city's kitchen, serving fresh seafood, wagyu, and street snacks",
      "Nara Deer Park (Day Trip) — Home to 1,200 sacred free-roaming deer alongside UNESCO temples just 45 minutes from Osaka",
    ],
    topCategories: [
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "200+", description: "Dotonbori food crawls, takoyaki and okonomiyaki tastings, Kuromon Market tours, sake brewing, and cooking classes." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "150+", description: "Osaka Castle tours, Dotonbori neon walks, Shinsekai explorations, and river cruise sightseeing." },
      { slug: "attractions", name: "Attractions", icon: "🎠", count: "180+", description: "Universal Studios Japan, Osaka Castle, Osaka Aquarium Kaiyukan, Umeda Sky Building, and Tsutenkaku Tower." },
      { slug: "nightlife", name: "Nightlife", icon: "🌃", count: "80+", description: "Dotonbori pub crawls, Shinsekai izakaya hopping, comedy shows, karaoke, and river cruise dining." },
      { slug: "culture", name: "Culture & Arts", icon: "🎭", count: "100+", description: "Bunraku puppet theatre, taiko drumming workshops, sword-making museums, and kimono strolls through Shitennoji." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "120+", description: "Nara deer park, Kyoto temples, Kobe beef tasting, Himeji Castle, and Mount Koya monastery stays." },
    ],
    geoLat: 34.6937,
    geoLon: 135.5023,
    faq: [
      { q: "What group experiences are available in Osaka?", a: "TicketMatch.ai provides access to 1,000+ experiences: Dotonbori food crawls, Osaka Castle tours, Universal Studios Japan tickets, Kuromon Market tastings, and Nara day trips — all at exclusive B2B group rates." },
      { q: "Can I book food tours for groups in Osaka?", a: "Yes. TicketMatch.ai offers group food experiences including Dotonbori street food crawls, takoyaki classes, Kuromon Market tours, and sake brewery visits — all at competitive B2B rates." },
      { q: "Are Universal Studios Japan tickets available for groups?", a: "Absolutely. TicketMatch.ai provides group tickets and express passes for Universal Studios Japan at B2B rates, including Wizarding World and Super Nintendo World access." },
      { q: "Is Osaka suitable for large group travel?", a: "Yes. Osaka is well-equipped for groups with excellent train connections, large dining venues, and experienced operators. TicketMatch.ai's B2B platform offers seamless group booking and optimised pricing." },
    ],
  },
];
