import type { CityData } from "./cities-data";

export const portugueseCities: CityData[] = [
  {
    slug: "lisbon",
    name: "Lisbon",
    province: "Lisbon District",
    country: "Portugal",
    flag: "\u{1F1F5}\u{1F1F9}",
    experiences: "4,200+",
    categories: 12,
    viatorDestId: 538,
    tagline: "City of seven hills — tiles, trams, pastéis & Atlantic soul",
    description:
      "Lisbon is Europe's sunniest capital, a city of cobblestone hills, iconic yellow trams, azulejo tiles, and world-class pastéis de nata. From the medieval Alfama to the modern waterfront, TicketMatch.ai provides B2B access to 4,200+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Belém Tower — The iconic 16th-century fortress guarding the Tagus river, a UNESCO World Heritage site",
      "Jerónimos Monastery — Magnificent Manueline monastery in Belém, UNESCO World Heritage masterpiece",
      "Alfama — Lisbon's oldest neighborhood of winding alleys, fado houses, and São Jorge Castle views",
      "Tram 28 — The iconic yellow tram rattling through Lisbon's steepest and most historic neighborhoods",
      "Time Out Market — Lisbon's legendary food hall in the Mercado da Ribeira with top Portuguese chefs",
      "São Jorge Castle — Medieval Moorish castle crowning the highest hill with panoramic city views",
      "Praça do Comércio — Grand waterfront square and gateway to Lisbon's Baixa district",
      "LX Factory — Creative hub in a converted industrial complex with shops, restaurants, and street art",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "250+", description: "Tram 28 routes, Alfama walks, tuk-tuk tours, Belém discoveries, street art tours, and fado evenings." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "180+", description: "Pastéis de nata workshops, wine tastings, Time Out Market, ginjinha shots, bacalhau tours, and cooking classes." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "80+", description: "Belém Tower, Jerónimos Monastery, São Jorge Castle, Oceanarium, Santa Justa Elevator, and Sintra palaces." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "150+", description: "Sintra (Pena Palace), Cascais, Óbidos, Fátima, Évora, Arrábida, and Setúbal dolphin watching." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "50+", description: "Museu Nacional do Azulejo, MAAT, Gulbenkian, National Coach Museum, and Berardo Collection." },
      { slug: "river-cruises", name: "River Cruises", icon: "\u{1F6A2}", count: "30+", description: "Tagus river cruises, sunset sailing, catamaran tours, and bridge-to-bridge boat trips." },
    ],
    geoLat: 38.7223,
    geoLon: -9.1393,
    faq: [
      { q: "What group experiences are available in Lisbon?", a: "TicketMatch.ai provides access to 4,200+ experiences: Belém tours, Sintra day trips, pastéis de nata workshops, fado evenings, and more — all at exclusive B2B group rates." },
      { q: "Can I book Sintra day trips for groups?", a: "Yes. Sintra is 40 minutes from Lisbon. TicketMatch.ai offers group tours of Pena Palace, Quinta da Regaleira, Moorish Castle, and combined Sintra + Cascais packages at B2B rates." },
      { q: "What food experiences are available for groups?", a: "Lisbon is a food paradise. TicketMatch.ai offers pastéis de nata baking, Time Out Market visits, bacalhau tastings, wine tours, ginjinha crawls, and Alfama food walks at B2B group rates." },
      { q: "Is Lisbon good for group travel?", a: "Excellent. Lisbon is affordable, sunny, walkable (though hilly!), and has excellent metro and tram systems. TicketMatch.ai's AI helps plan optimal Lisbon group itineraries avoiding steep climbs." },
    ],
  },
  {
    slug: "porto",
    name: "Porto",
    province: "Porto District",
    country: "Portugal",
    flag: "\u{1F1F5}\u{1F1F9}",
    experiences: "2,800+",
    categories: 10,
    viatorDestId: 26879,
    tagline: "Port wine capital — Douro Valley, azulejos & riverside magic",
    description:
      "Porto is Portugal's second city and the birthplace of port wine — a UNESCO-listed riverside gem of stunning azulejo-tiled buildings, medieval streets, and the magnificent Douro Valley. TicketMatch.ai provides B2B access to 2,800+ group experiences at exclusive rates.",
    highlights: [
      "Ribeira District — UNESCO waterfront neighborhood with colorful houses cascading down to the Douro",
      "Livraria Lello — One of the world's most beautiful bookshops, said to have inspired Harry Potter",
      "Dom Luís I Bridge — Iconic double-deck iron bridge spanning the Douro, designed by a student of Eiffel",
      "São Bento Station — Railway station famous for 20,000 hand-painted azulejo tiles depicting Portuguese history",
      "Port Wine Cellars — Historic wine lodges in Vila Nova de Gaia offering tastings and tours",
      "Clérigos Tower — Baroque bell tower with 240 steps and 360° views over Porto's terracotta rooftops",
    ],
    topCategories: [
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "140+", description: "Port wine cellar tastings, Douro Valley vineyard tours, francesinha tastings, food market walks, and cooking classes." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "160+", description: "Ribeira walks, azulejo tile tours, tuk-tuk rides, Clérigos tower climbs, and Porto by night." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "100+", description: "Douro Valley (wine + river cruise), Braga, Guimarães (birthplace of Portugal), Aveiro, and Santiago de Compostela." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "50+", description: "Livraria Lello, São Bento Station, Dom Luís Bridge, Crystal Palace Gardens, and Bolhão Market." },
      { slug: "river-cruises", name: "River Cruises", icon: "\u{1F6A2}", count: "40+", description: "Douro river six-bridges cruise, Douro Valley full-day cruises, sunset boats, and private charters." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "30+", description: "Serralves contemporary art, Portuguese Photography Centre, World of Discoveries, and Port Wine Museum." },
    ],
    geoLat: 41.1579,
    geoLon: -8.6291,
    faq: [
      { q: "What group experiences are available in Porto?", a: "TicketMatch.ai provides access to 2,800+ experiences: port wine cellars, Douro Valley cruises, Ribeira walks, Livraria Lello, and more — all at exclusive B2B group rates." },
      { q: "What port wine experiences are available?", a: "Porto is port wine's home. TicketMatch.ai offers group cellar tours in Vila Nova de Gaia (Taylor's, Graham's, Sandeman), tastings, blending workshops, and combined cellar + Douro Valley at B2B rates." },
      { q: "Can I book Douro Valley day trips for groups?", a: "Yes. TicketMatch.ai offers group Douro Valley excursions: river cruises, vineyard visits, wine tastings, quinta lunches, and combined boat + train packages at B2B rates." },
      { q: "Is Porto good for group travel?", a: "Outstanding. Porto is compact, affordable, UNESCO-listed, and the gateway to the Douro Valley wine region. TicketMatch.ai helps plan combined Porto + Douro group itineraries." },
    ],
  },
  {
    slug: "sintra",
    name: "Sintra",
    province: "Lisbon District",
    country: "Portugal",
    flag: "\u{1F1F5}\u{1F1F9}",
    experiences: "1,000+",
    categories: 7,
    viatorDestId: 50861,
    tagline: "Fairy-tale palaces in misty hills — Portugal's most magical town",
    description:
      "Sintra is a UNESCO World Heritage cultural landscape of fairy-tale palaces, mystical gardens, and misty forested hills just 40 minutes from Lisbon. Lord Byron called it 'glorious Eden.' TicketMatch.ai provides B2B access to 1,000+ group experiences at exclusive rates.",
    highlights: [
      "Pena Palace — Colorful Romanticist palace perched on a hilltop, Portugal's most iconic landmark",
      "Quinta da Regaleira — Mystical estate with initiatic wells, underground tunnels, and symbolic gardens",
      "Moorish Castle — 8th-century hilltop castle ruins with dramatic views over Sintra and the Atlantic",
      "National Palace of Sintra — Medieval royal palace in the town center with iconic twin chimneys",
      "Monserrate Palace — Exotic 19th-century palace surrounded by botanical gardens from five continents",
      "Cabo da Roca — The westernmost point of mainland Europe with dramatic Atlantic cliffs",
    ],
    topCategories: [
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Pena Palace, Quinta da Regaleira, Moorish Castle, National Palace, Monserrate, and Cabo da Roca." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "50+", description: "Palace-hopping tours, Sintra + Cascais combos, tuk-tuk rides, photography tours, and mystical garden walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "30+", description: "From Lisbon: Sintra + Cascais, Sintra + Cabo da Roca, and full-day Sintra palace circuits." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "15+", description: "Travesseiros (local pastry), queijadas de Sintra, wine tastings in Colares, and palace garden picnics." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "15+", description: "Sintra-Cascais Natural Park hiking, Cabo da Roca coastal walks, and mountain biking." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "10+", description: "Romantic era architecture tours, Masonic symbolism at Quinta da Regaleira, and azulejo collections." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "5+", description: "Toy Museum, Sintra Museum of Modern Art, and palace exhibit collections." },
    ],
    geoLat: 38.7980,
    geoLon: -9.3880,
    faq: [
      { q: "What group experiences are available in Sintra?", a: "TicketMatch.ai provides access to 1,000+ experiences: Pena Palace, Quinta da Regaleira, Moorish Castle, Cabo da Roca, and more — all at exclusive B2B group rates." },
      { q: "Can groups visit multiple palaces in one day?", a: "Yes. TicketMatch.ai offers group palace circuit tours covering Pena Palace, Quinta da Regaleira, and Moorish Castle with transport and guides at B2B rates. Early start recommended." },
      { q: "Is Sintra a day trip from Lisbon?", a: "Yes, 40 minutes by train. TicketMatch.ai offers group day trips from Lisbon including transport, palace tickets, and combined Sintra + Cascais + Cabo da Roca packages at B2B rates." },
      { q: "What makes Quinta da Regaleira special?", a: "Its 27-meter initiatic well, underground tunnels, and gardens full of Masonic and alchemical symbolism make it one of Portugal's most mysterious attractions. Group visits at B2B rates via TicketMatch.ai." },
    ],
  },
  {
    slug: "faro",
    name: "Faro & Algarve",
    province: "Algarve",
    country: "Portugal",
    flag: "\u{1F1F5}\u{1F1F9}",
    experiences: "1,800+",
    categories: 9,
    viatorDestId: 23402,
    tagline: "Golden cliffs & turquoise waters — Europe's best-kept beach secret",
    description:
      "The Algarve is Portugal's sun-drenched southern coast, famous for dramatic golden cliffs, hidden sea caves, and some of Europe's finest beaches. With Faro as its gateway, TicketMatch.ai provides B2B access to 1,800+ group experiences at exclusive rates.",
    highlights: [
      "Benagil Cave — The world-famous sea cave with a natural skylight, accessible only by water",
      "Ponta da Piedade — Dramatic golden limestone cliffs and sea stacks near Lagos",
      "Ria Formosa Natural Park — Barrier island lagoon system with flamingos and pristine beaches",
      "Lagos Old Town — Historic walled town with vibrant nightlife and stunning coastal cliffs",
      "Albufeira — The Algarve's most popular resort town with old town charm and beach clubs",
      "Cape St. Vincent — Europe's southwestern tip, the 'End of the World' with dramatic cliffs",
    ],
    topCategories: [
      { slug: "outdoor", name: "Outdoor & Beach", icon: "\u{1F3D6}\u{FE0F}", count: "100+", description: "Benagil cave tours, kayaking, snorkeling, stand-up paddleboarding, cliff walks, and beach hopping." },
      { slug: "river-cruises", name: "Boat Tours", icon: "\u{1F6A2}", count: "80+", description: "Benagil cave boats, dolphin watching, Ria Formosa cruises, sunset sailing, and catamaran parties." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "70+", description: "Lagos cliff walks, Faro old town, Silves castle, Seven Hanging Valleys trail, and jeep safaris." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "50+", description: "Seafood feasts, cataplana cooking, Algarve wine tastings, fig & almond tours, and market walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "40+", description: "Seville (Spain), Lagos, Sagres, Cape St. Vincent, Silves, and Monchique mountain spa." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "Benagil Cave, Ponta da Piedade, Cape St. Vincent, Silves Castle, and Slide & Splash water park." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "10+", description: "Faro Cathedral, bone chapel, Moorish heritage walks, and traditional fishing village visits." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "10+", description: "Municipal Museum of Faro, Maritime Museum, and Lagos Slave Market museum." },
      { slug: "golf", name: "Golf", icon: "\u{26F3}", count: "20+", description: "Vilamoura golf courses, Vale do Lobo, Quinta do Lago, and championship green fee packages." },
    ],
    geoLat: 37.0194,
    geoLon: -7.9322,
    faq: [
      { q: "What group experiences are available in the Algarve?", a: "TicketMatch.ai provides access to 1,800+ experiences: Benagil cave tours, dolphin watching, cliff walks, seafood experiences, and more — all at exclusive B2B group rates." },
      { q: "How do groups visit Benagil Cave?", a: "By boat, kayak, or SUP from nearby beaches. TicketMatch.ai offers group boat tours and kayaking excursions to Benagil with guided options at B2B rates." },
      { q: "What beach activities are available for groups?", a: "The Algarve has 200km of coastline. TicketMatch.ai offers group kayaking, snorkeling, paddleboarding, sailing, jet skiing, and multi-beach tour packages at B2B rates." },
      { q: "Is the Algarve good for group travel?", a: "Outstanding. 300+ sunshine days, diverse beaches, affordable dining, and excellent golf. TicketMatch.ai helps plan multi-day Algarve group itineraries from beach to culture." },
    ],
  },
];
