import type { CityData } from "./cities-data";

export const spanishCities: CityData[] = [
  {
    slug: "barcelona",
    name: "Barcelona",
    province: "Catalonia",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "7,200+",
    categories: 14,
    viatorDestId: 562,
    tagline: "Gaudí's masterpiece — art, architecture & Mediterranean soul",
    description:
      "Barcelona is Spain's cosmopolitan jewel on the Mediterranean coast, where Gaudí's surreal architecture meets vibrant street life, world-class cuisine, and golden beaches. From the Sagrada Família to La Rambla, TicketMatch.ai provides B2B access to 7,200+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Sagrada Família — Gaudí's unfinished masterpiece, UNESCO World Heritage basilica under construction since 1882",
      "Park Güell — Gaudí's colorful mosaic park overlooking the city with panoramic Mediterranean views",
      "Casa Batlló — Gaudí's fantastical residential building on Passeig de Gràcia with dragon-spine roof",
      "La Rambla — Barcelona's most famous tree-lined boulevard stretching from Plaça de Catalunya to the port",
      "Gothic Quarter (Barri Gòtic) — Medieval labyrinth of narrow streets, plazas, and the Barcelona Cathedral",
      "Camp Nou — FC Barcelona's legendary stadium, one of the largest in Europe with 99,000+ capacity",
      "La Boqueria Market — Iconic covered market on La Rambla with fresh produce, tapas, and juices",
      "Montjuïc — Hilltop park with Olympic stadium, Miró Foundation, Magic Fountain, and panoramic cable car",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "200+", description: "Picasso Museum, Miró Foundation, MACBA, MNAC, CosmoCaixa, FC Barcelona Museum, and 180+ more at B2B group rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "350+", description: "Gaudí architecture tours, Gothic Quarter walks, tapas tours, bike tours, Montjuïc cable car, and rooftop experiences." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "120+", description: "Sagrada Família, Park Güell, Casa Batlló, Casa Milà, Camp Nou, Barcelona Aquarium, and PortAventura day trips." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "180+", description: "Tapas tours in El Born, La Boqueria market walks, paella cooking classes, cava tastings, wine & cheese evenings." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "150+", description: "Montserrat monastery, Costa Brava, Girona, Figueres (Dalí Museum), Penedès wine region, and Andorra." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "80+", description: "Barceloneta beach activities, kayaking, sailing, Montjuïc hiking, Tibidabo mountain, and Costa Brava snorkeling." },
    ],
    geoLat: 41.3874,
    geoLon: 2.1686,
    faq: [
      { q: "What group experiences are available in Barcelona?", a: "TicketMatch.ai provides access to 7,200+ experiences: skip-the-line Sagrada Família, Park Güell, Gaudí architecture tours, Gothic Quarter walks, tapas tours, Camp Nou visits, and more — all at exclusive B2B group rates." },
      { q: "How do I book group tickets for Sagrada Família?", a: "Through TicketMatch.ai, book group skip-the-line tickets for Sagrada Família including tower access, guided tours, and combined Gaudí packages (Sagrada Família + Park Güell + Casa Batlló) at wholesale B2B rates." },
      { q: "Can I book Montserrat day trips for groups?", a: "Yes. TicketMatch.ai offers group Montserrat excursions: monastery visits, Black Madonna viewing, boys' choir performances, hiking, and combined Montserrat + wine tasting tours at B2B rates." },
      { q: "Is Barcelona good for group travel?", a: "Excellent. Barcelona has an efficient metro system, walkable neighborhoods, year-round weather, and thousands of group-ready venues. TicketMatch.ai's busyness data helps avoid crowds at Sagrada Família and Park Güell." },
      { q: "What food experiences are available for groups?", a: "Barcelona is a tapas paradise. Group experiences include La Boqueria market tours, El Born tapas crawls, paella cooking classes, cava vineyard visits, and exclusive group dining in Gothic Quarter venues." },
    ],
  },
  {
    slug: "madrid",
    name: "Madrid",
    province: "Community of Madrid",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "5,800+",
    categories: 13,
    viatorDestId: 566,
    tagline: "Spain's passionate capital — world-class art, tapas & flamenco",
    description:
      "Madrid is Spain's grand capital, a city of world-class art museums, royal palaces, legendary nightlife, and passionate culture. From the Prado to flamenco tablaos, TicketMatch.ai provides B2B access to 5,800+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Prado Museum — One of the world's greatest art collections with Velázquez, Goya, and El Greco masterpieces",
      "Royal Palace (Palacio Real) — Europe's largest royal palace with 3,418 rooms and stunning gardens",
      "Reina Sofía Museum — Home to Picasso's Guernica and Spain's premier modern art collection",
      "Puerta del Sol — Madrid's central square and the symbolic heart of Spain (Km 0)",
      "Plaza Mayor — Grand 17th-century arcaded square, the historic center of Madrid life",
      "Retiro Park — 125-hectare royal park with Crystal Palace, boating lake, and rose garden",
      "Santiago Bernabéu Stadium — Real Madrid's iconic home, recently renovated with retractable roof",
      "Gran Vía — Madrid's Broadway, the vibrant main boulevard lined with theaters, shops, and rooftop bars",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "180+", description: "Prado, Reina Sofía, Thyssen-Bornemisza (the 'Golden Triangle'), Royal Palace, CaixaForum, and 150+ more at B2B rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "280+", description: "Royal Madrid walks, tapas tours, flamenco shows, literary Madrid, rooftop bar tours, and night tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "100+", description: "Royal Palace, Bernabéu Stadium, Retiro Park, Mercado de San Miguel, Warner Bros Park, and Parque Europa." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "160+", description: "Tapas tours in La Latina, Mercado de San Miguel, wine tastings, cooking classes, churros at San Ginés, and group flamenco dinners." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "130+", description: "Toledo, Segovia (Roman aqueduct), El Escorial, Ávila, Cuenca, and Chinchón — all within 1-2 hours of Madrid." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "90+", description: "Flamenco shows, opera at Teatro Real, Thyssen museum, street art in Malasaña, and art workshops." },
    ],
    geoLat: 40.4168,
    geoLon: -3.7038,
    faq: [
      { q: "What group experiences are available in Madrid?", a: "TicketMatch.ai provides access to 5,800+ experiences: Prado museum tours, Royal Palace visits, flamenco shows, tapas tours, Toledo day trips, and more — all at exclusive B2B group rates." },
      { q: "How do I book group museum tickets in Madrid?", a: "TicketMatch.ai offers group access to the Golden Triangle (Prado + Reina Sofía + Thyssen), Royal Palace, and 150+ more museums. Skip-the-line, guided, and combined packages at wholesale B2B rates." },
      { q: "Can I book Toledo day trips for groups?", a: "Yes. Toledo is 30 minutes from Madrid by train. TicketMatch.ai offers group tours including the Cathedral, Alcázar, El Greco, synagogues, and combined Toledo + Segovia day trips at B2B rates." },
      { q: "What flamenco experiences are available for groups?", a: "Madrid is Spain's flamenco capital. TicketMatch.ai offers group flamenco shows at traditional tablaos, dinner + flamenco packages, and private group performances in historic venues at B2B rates." },
      { q: "Is Madrid good for group travel?", a: "Outstanding. Madrid has an extensive metro, walkable center, world-class museums, and is a hub for day trips to 6+ UNESCO cities. TicketMatch.ai's AI helps plan multi-day central Spain itineraries." },
    ],
  },
  {
    slug: "seville",
    name: "Seville",
    province: "Andalusia",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "3,400+",
    categories: 10,
    viatorDestId: 556,
    tagline: "The soul of Andalusia — flamenco, Alcázar & orange-blossom streets",
    description:
      "Seville is the passionate heart of Andalusia, where flamenco was born, Moorish palaces dazzle, and tapas culture thrives. With the Real Alcázar, Seville Cathedral, and Plaza de España, TicketMatch.ai provides B2B access to 3,400+ group experiences at exclusive rates.",
    highlights: [
      "Real Alcázar — Stunning Mudéjar palace complex, a UNESCO World Heritage site and Game of Thrones filming location",
      "Seville Cathedral & Giralda — World's largest Gothic cathedral with the iconic Giralda bell tower",
      "Plaza de España — Spectacular semicircular plaza from the 1929 Ibero-American Exposition with ceramic tile alcoves",
      "Barrio de Santa Cruz — The enchanting former Jewish quarter with winding alleys and flower-filled patios",
      "Metropol Parasol (Las Setas) — The world's largest wooden structure with rooftop walkway and views",
      "Triana — Historic neighborhood across the river, birthplace of many flamenco legends",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "200+", description: "Alcázar guided tours, Santa Cruz walks, horse-drawn carriage rides, rooftop tours, and Guadalquivir river cruises." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "70+", description: "Real Alcázar, Cathedral & Giralda, Plaza de España, Metropol Parasol, Torre del Oro, and Isla Mágica." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Tapas tours in Triana, sherry tastings, Andalusian cooking classes, market tours, and flamenco dinner shows." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "80+", description: "Flamenco shows in Triana, Museo de Bellas Artes, ceramic workshops, and Semana Santa cultural tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "90+", description: "Córdoba (Mezquita), Granada (Alhambra), Ronda, Cádiz, Jerez (sherry bodegas), and white village routes." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "30+", description: "Guadalquivir kayaking, cycling tours, Doñana National Park, and Aljarafe olive grove visits." },
    ],
    geoLat: 37.3891,
    geoLon: -5.9845,
    faq: [
      { q: "What group experiences are available in Seville?", a: "TicketMatch.ai provides access to 3,400+ experiences: Alcázar tours, Cathedral visits, flamenco shows, tapas tours in Triana, Córdoba day trips, and more — all at exclusive B2B group rates." },
      { q: "Can I book Alhambra day trips from Seville?", a: "Yes. TicketMatch.ai offers group day trips from Seville to Granada's Alhambra (2.5h). Options include Alhambra + Generalife, combined Granada city tours, and overnight packages at B2B rates." },
      { q: "What flamenco experiences are available in Seville?", a: "Seville is the birthplace of flamenco. TicketMatch.ai offers group shows in Triana tablaos, private performances, dinner + flamenco packages, and flamenco museum visits at B2B rates." },
      { q: "Is Seville good for group travel?", a: "Excellent. Seville has a compact walkable center, efficient tram system, and is the perfect base for Andalusia day trips (Córdoba, Granada, Ronda). TicketMatch.ai helps plan multi-city Andalusia itineraries." },
    ],
  },
  {
    slug: "valencia",
    name: "Valencia",
    province: "Valencian Community",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "2,600+",
    categories: 10,
    viatorDestId: 811,
    tagline: "City of Arts & Sciences — birthplace of paella on the Mediterranean",
    description:
      "Valencia is Spain's third-largest city, blending futuristic architecture with medieval charm. Home to the stunning City of Arts and Sciences, the birthplace of paella, and Las Fallas festival, TicketMatch.ai provides B2B access to 2,600+ group experiences at exclusive rates.",
    highlights: [
      "City of Arts and Sciences — Santiago Calatrava's futuristic complex with Oceanogràfic, Hemisfèric, and Science Museum",
      "Oceanogràfic — Europe's largest aquarium with 45,000+ marine creatures and dolphin shows",
      "La Lonja de la Seda — UNESCO Gothic silk exchange, a masterpiece of civil Gothic architecture",
      "Central Market (Mercado Central) — One of Europe's largest and most beautiful covered markets",
      "Valencia Cathedral — Houses the Holy Grail (Santo Cáliz) and Miguelete bell tower with city views",
      "Turia Gardens — 9km former riverbed park running through the city, perfect for walking and cycling",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "150+", description: "Old town walks, City of Arts tours, bike rides through Turia Gardens, street art tours, and e-scooter tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "60+", description: "City of Arts & Sciences, Oceanogràfic, Bioparc zoo, Central Market, La Lonja, and Valencia Cathedral." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Authentic paella cooking classes, Central Market tours, horchata tastings, wine tours, and tapas crawls in El Carmen." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "50+", description: "Turia Gardens cycling, Albufera boat rides, beach watersports, sailing, and Montanejos hot springs." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "60+", description: "Albufera Natural Park (paella's birthplace), Peñíscola, Xàtiva castle, Requena wine region, and Cuenca." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "35+", description: "Science Museum, IVAM modern art, Fallas Museum, Ceramics Museum, and Silk Museum." },
    ],
    geoLat: 39.4699,
    geoLon: -0.3763,
    faq: [
      { q: "What group experiences are available in Valencia?", a: "TicketMatch.ai provides access to 2,600+ experiences: City of Arts tours, paella cooking classes, old town walks, Albufera boat trips, and more — all at exclusive B2B group rates." },
      { q: "Can I book paella experiences for groups?", a: "Absolutely! Valencia is paella's birthplace. TicketMatch.ai offers group cooking classes, Albufera rice field visits, traditional restaurant lunches, and market-to-table paella experiences at B2B rates." },
      { q: "What is the City of Arts and Sciences?", a: "Santiago Calatrava's futuristic complex includes Europe's largest aquarium (Oceanogràfic), a planetarium (Hemisfèric), science museum, and opera house. TicketMatch.ai offers combined group packages at B2B rates." },
      { q: "Is Valencia good for group travel?", a: "Very. Valencia is compact, affordable, has great weather year-round, and offers diverse experiences from futuristic to medieval. TicketMatch.ai's AI helps plan optimal Valencia group itineraries." },
    ],
  },
  {
    slug: "malaga",
    name: "Málaga",
    province: "Andalusia",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "2,800+",
    categories: 10,
    viatorDestId: 956,
    tagline: "Picasso's birthplace — Costa del Sol gateway with year-round sunshine",
    description:
      "Málaga is the vibrant capital of the Costa del Sol, Picasso's birthplace, and one of Europe's oldest cities. With 30+ museums, a revitalized port, and 300+ days of sunshine, TicketMatch.ai provides B2B access to 2,800+ group experiences at exclusive rates.",
    highlights: [
      "Picasso Museum — Dedicated to Málaga's most famous son with 285+ works in a Renaissance palace",
      "Alcazaba — 11th-century Moorish fortress-palace with beautiful gardens and harbor views",
      "Málaga Cathedral (La Manquita) — Renaissance cathedral nicknamed 'One-Armed Lady' for its unfinished tower",
      "Centre Pompidou Málaga — The only Centre Pompidou outside France, housed in a colorful glass cube at the port",
      "Caminito del Rey — The spectacular 'King's Walkway' cliffside path in El Chorro gorge",
      "Muelle Uno — Revitalized waterfront promenade with restaurants, shops, and cultural venues",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "180+", description: "Historic center walks, tapas tours, Picasso's Málaga, street art tours, and panoramic bus tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "150+", description: "Caminito del Rey, Granada (Alhambra), Ronda, Nerja caves, Gibraltar, Marbella, and white village routes." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "90+", description: "Tapas tours in Atarazanas market area, wine tastings, chiringuito beach dining, and Andalusian cooking classes." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "50+", description: "Alcazaba, Gibralfaro Castle, Cathedral, Centre Pompidou, Automobile Museum, and Soho street art district." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "40+", description: "Picasso Museum, Centre Pompidou, Carmen Thyssen, CAC contemporary art, Russian Museum, and Automobile Museum." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "60+", description: "Caminito del Rey, beach activities, kayaking, sailing, El Torcal nature reserve, and Sierra Nevada excursions." },
    ],
    geoLat: 36.7213,
    geoLon: -4.4214,
    faq: [
      { q: "What group experiences are available in Málaga?", a: "TicketMatch.ai provides access to 2,800+ experiences: Picasso Museum, Alcazaba, Caminito del Rey, tapas tours, Granada day trips, and more — all at exclusive B2B group rates." },
      { q: "Can I book Caminito del Rey for groups?", a: "Yes. The King's Walkway is one of Spain's top attractions. TicketMatch.ai offers group guided tours with transport from Málaga, including combined Caminito + lunch packages at B2B rates." },
      { q: "What day trips are available from Málaga?", a: "Group day trips include Granada (Alhambra), Ronda, Nerja caves, Gibraltar, Córdoba, white villages, and Caminito del Rey — all bookable at B2B rates through TicketMatch.ai." },
      { q: "Is Málaga good for group travel?", a: "Excellent. Málaga has 300+ sunshine days, a compact center, modern airport, and is the gateway to Costa del Sol and Andalusia. TicketMatch.ai helps plan multi-day Andalusia group itineraries." },
    ],
  },
  {
    slug: "granada",
    name: "Granada",
    province: "Andalusia",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "2,200+",
    categories: 9,
    viatorDestId: 554,
    tagline: "Home of the Alhambra — where Moorish Spain lives on",
    description:
      "Granada is one of Spain's most enchanting cities, crowned by the magnificent Alhambra palace against the backdrop of the Sierra Nevada mountains. With its Moorish heritage, cave flamenco shows, and free-tapas culture, TicketMatch.ai provides B2B access to 2,200+ group experiences at exclusive rates.",
    highlights: [
      "Alhambra & Generalife — Spain's most-visited monument, a UNESCO Moorish palace complex with Nasrid Palaces and gardens",
      "Albaicín — UNESCO Moorish quarter with whitewashed houses, narrow streets, and stunning Alhambra views from Mirador San Nicolás",
      "Sacromonte — Cave-dwelling neighborhood famous for authentic zambra flamenco shows",
      "Granada Cathedral & Royal Chapel — Renaissance cathedral housing the tombs of Ferdinand and Isabella",
      "Sierra Nevada — Spain's highest mountain range with skiing, hiking, and Europe's southernmost ski resort",
      "Mirador de San Nicolás — The most famous viewpoint in Granada with the Alhambra framed by Sierra Nevada peaks",
    ],
    topCategories: [
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "60+", description: "Alhambra & Nasrid Palaces, Generalife gardens, Albaicín quarter, Cathedral, Royal Chapel, and Sacromonte caves." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "150+", description: "Alhambra guided tours, Albaicín walks, Sacromonte cave visits, tapas tours, and sunset viewpoint tours." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "70+", description: "Free tapas tours (Granada tradition!), Albaicín tea houses, wine tastings, cooking classes, and market visits." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "50+", description: "Sacromonte cave flamenco shows, hammam (Arab baths), calligraphy workshops, and Federico García Lorca cultural tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "60+", description: "Sierra Nevada, Alpujarras white villages, Córdoba, Nerja, tropical coast, and olive oil region tours." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "30+", description: "Sierra Nevada hiking and skiing, Alpujarras trekking, canyon adventures, and hot springs visits." },
    ],
    geoLat: 37.1773,
    geoLon: -3.5986,
    faq: [
      { q: "What group experiences are available in Granada?", a: "TicketMatch.ai provides access to 2,200+ experiences: Alhambra skip-the-line tours, Albaicín walks, cave flamenco, tapas tours, Sierra Nevada excursions, and more — all at exclusive B2B group rates." },
      { q: "How do I book Alhambra tickets for groups?", a: "Alhambra tickets sell out weeks in advance. TicketMatch.ai secures group allocations for Nasrid Palaces, Generalife, and Alcazaba at B2B rates. Guided tours and combined city packages available." },
      { q: "What is special about Granada's tapas culture?", a: "Granada is famous for FREE tapas — every drink order comes with a complimentary tapa. TicketMatch.ai offers guided group tapas tours through the best bars in the old town at B2B rates." },
      { q: "Is Granada good for group travel?", a: "Perfect. Granada is walkable, affordable, culturally rich, and has the Alhambra (Spain's #1 monument). TicketMatch.ai helps plan combined Andalusia itineraries with Seville, Córdoba, and Málaga." },
    ],
  },
  {
    slug: "bilbao",
    name: "Bilbao",
    province: "Basque Country",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "1,600+",
    categories: 9,
    viatorDestId: 4485,
    tagline: "The Guggenheim city — Basque culture, pintxos & modern reinvention",
    description:
      "Bilbao's transformation from industrial port to cultural powerhouse is one of Europe's great urban stories. The Guggenheim Museum put it on the map, but Basque cuisine, pintxos bars, and the stunning Biscay coast keep visitors coming back. TicketMatch.ai provides B2B access to 1,600+ group experiences at exclusive rates.",
    highlights: [
      "Guggenheim Museum Bilbao — Frank Gehry's titanium masterpiece, the building that transformed a city",
      "Casco Viejo — The charming old quarter with the Seven Streets, pintxos bars, and Plaza Nueva",
      "San Juan de Gaztelugatxe — Dramatic island hermitage connected by a stone bridge (Game of Thrones' Dragonstone)",
      "Mercado de la Ribera — Europe's largest covered market, beautifully renovated on the riverbank",
      "Vizcaya Bridge — UNESCO World Heritage transporter bridge, the world's oldest of its kind (1893)",
      "Nervión Riverside — The revitalized waterfront promenade from the Guggenheim to the Zubizuri bridge",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "30+", description: "Guggenheim Bilbao, Fine Arts Museum, Maritime Museum, Basque Museum, and Azkuna Zentroa cultural center." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "90+", description: "Guggenheim tours, Casco Viejo walks, pintxos tours, architecture tours, and Nervión riverside walks." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "70+", description: "Pintxos bar crawls, Rioja wine tours, Basque cooking classes, txakoli tastings, and market visits." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "San Juan de Gaztelugatxe, San Sebastián, Rioja wine region, Guernica, French Basque Country, and Biscay coast." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "Guggenheim, Vizcaya Bridge, Funicular de Artxanda, Azkuna Zentroa, and Arriaga Theatre." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "20+", description: "Biscay coast hikes, surfing in Mundaka, Urdaibai Biosphere Reserve, and Mount Artxanda walks." },
    ],
    geoLat: 43.2630,
    geoLon: -2.9350,
    faq: [
      { q: "What group experiences are available in Bilbao?", a: "TicketMatch.ai provides access to 1,600+ experiences: Guggenheim tours, pintxos crawls, San Juan de Gaztelugatxe excursions, Rioja wine trips, and more — all at exclusive B2B group rates." },
      { q: "Can I book Guggenheim Museum tours for groups?", a: "Yes. TicketMatch.ai offers group tickets and guided tours of the Guggenheim Bilbao, including combined packages with other Bilbao museums and architecture tours at B2B rates." },
      { q: "What is a pintxos tour?", a: "Pintxos are the Basque version of tapas — small bites served on bread in bars. TicketMatch.ai offers guided group pintxos crawls through Casco Viejo's best bars at B2B rates." },
      { q: "Is Bilbao a good base for Basque Country tours?", a: "Perfect. Bilbao connects easily to San Sebastián (1h), Rioja wine region (1.5h), Guernica (45min), and the stunning Biscay coast. TicketMatch.ai helps plan multi-day Basque Country group itineraries." },
    ],
  },
  {
    slug: "san-sebastian",
    name: "San Sebastián",
    province: "Basque Country",
    country: "Spain",
    flag: "\u{1F1EA}\u{1F1F8}",
    experiences: "1,400+",
    categories: 8,
    viatorDestId: 5505,
    tagline: "Europe's culinary capital — Michelin stars, beaches & Basque soul",
    description:
      "San Sebastián (Donostia) is regularly voted the world's best food city, with the highest concentration of Michelin stars per capita on Earth. Its stunning La Concha beach, Belle Époque architecture, and legendary pintxos scene make it a dream group destination. TicketMatch.ai provides B2B access to 1,400+ group experiences at exclusive rates.",
    highlights: [
      "La Concha Beach — Consistently ranked among Europe's most beautiful urban beaches",
      "Parte Vieja (Old Town) — The pintxos epicenter with dozens of legendary bars in narrow streets",
      "Monte Igueldo — Hilltop with vintage funicular and panoramic views over La Concha bay",
      "San Telmo Museum — Basque culture museum in a renovated 16th-century Dominican convent",
      "Kursaal — Rafael Moneo's striking glass cubes housing the city's conference and cultural center",
      "Zurriola Beach — The surfer's beach in Gros neighborhood, home to the San Sebastián Film Festival",
    ],
    topCategories: [
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Pintxos tours in Parte Vieja, Michelin-star dining, txakoli wine tastings, cooking classes, and cider house visits." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Old town walks, Monte Igueldo funicular, La Concha promenade tours, Belle Époque architecture, and coastal walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "60+", description: "French Basque Country (Biarritz, Saint-Jean-de-Luz), Rioja wine region, Bilbao, Hondarribia, and Flysch geopark." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "30+", description: "La Concha beach activities, surfing at Zurriola, coastal hiking (Camino del Norte), sailing, and Basque pelota." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Monte Igueldo, Aquarium, Kursaal, Buen Pastor Cathedral, and Miramar Palace." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "15+", description: "San Telmo Museum, Chillida-Leku sculpture park, Film Festival venues, and Basque cultural workshops." },
    ],
    geoLat: 43.3183,
    geoLon: -1.9812,
    faq: [
      { q: "What group experiences are available in San Sebastián?", a: "TicketMatch.ai provides access to 1,400+ experiences: world-class pintxos tours, cooking classes, La Concha beach, French Basque day trips, and more — all at exclusive B2B group rates." },
      { q: "Why is San Sebastián famous for food?", a: "San Sebastián has the highest Michelin star concentration per capita in the world. Its Parte Vieja old town has 100+ pintxos bars. TicketMatch.ai offers guided group food tours at B2B rates." },
      { q: "Can I visit the French Basque Country from San Sebastián?", a: "Yes. The French border is 20 minutes away. TicketMatch.ai offers group day trips to Biarritz, Saint-Jean-de-Luz, Bayonne, and Espelette at B2B rates." },
      { q: "Is San Sebastián good for group travel?", a: "Outstanding. Compact, walkable, stunning scenery, world-class food, and easy access to both Spanish and French Basque Country. TicketMatch.ai helps plan multi-day Basque group itineraries." },
    ],
  },
];
