import type { CityData } from "./cities-data";

export const swissCities: CityData[] = [
  {
    slug: "zurich",
    name: "Zurich",
    province: "Zürich",
    country: "Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
    experiences: "2,400+",
    categories: 10,
    viatorDestId: 898,
    tagline: "Switzerland's cosmopolitan hub — lake, Alps & world-class culture",
    description:
      "Zurich is Switzerland's largest city and financial capital, beautifully set on Lake Zurich with the Swiss Alps as a backdrop. With world-class museums, a charming old town, and easy access to Alpine adventures, TicketMatch.ai provides B2B access to 2,400+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Lake Zurich — Crystal-clear lake stretching 40km with boat cruises, swimming, and Alpine panoramas",
      "Altstadt (Old Town) — Medieval streets with guild houses, Lindenhof hill, and the iconic Grossmünster church",
      "Bahnhofstrasse — One of the world's most exclusive shopping streets, running from the station to the lake",
      "Kunsthaus Zürich — Switzerland's premier art museum with Giacometti, Monet, Picasso, and Chagall",
      "Grossmünster — Romanesque Protestant church where the Swiss Reformation began in 1519",
      "Swiss National Museum — Switzerland's most visited museum housed in a fairy-tale castle building",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "120+", description: "Old town walks, lake boat cruises, Bahnhofstrasse tours, chocolate tastings, and panoramic tram rides." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "100+", description: "Lucerne, Jungfraujoch (Top of Europe), Rhine Falls, Mt. Pilatus, Mt. Titlis, and Liechtenstein." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "40+", description: "Lake Zurich boats, Grossmünster towers, Uetliberg mountain, Lindt Chocolate Museum, and FIFA Museum." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "60+", description: "Swiss chocolate workshops, cheese fondue experiences, Lindt factory, wine tastings, and old town food tours." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "40+", description: "Kunsthaus, Swiss National Museum, FIFA Museum, Rietberg Museum, and Museum für Gestaltung." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "30+", description: "Lake Zurich swimming, Uetliberg hiking, river Limmat kayaking, and Alpine day trips." },
      { slug: "river-cruises", name: "Lake Cruises", icon: "\u{1F6A2}", count: "15+", description: "Lake Zurich boat tours, sunset cruises, dinner boats, and Rapperswil ferry trips." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "20+", description: "Kunsthaus tours, opera house visits, Cabaret Voltaire (birthplace of Dada), and gallery walks." },
      { slug: "winter-sports", name: "Winter Sports", icon: "\u{26F7}\u{FE0F}", count: "15+", description: "Flumserberg skiing, Titlis snow experiences, and Alpine winter day trips from Zurich." },
      { slug: "shopping", name: "Shopping", icon: "\u{1F6CD}\u{FE0F}", count: "10+", description: "Bahnhofstrasse luxury shopping, vintage markets, Swiss watch showrooms, and chocolate boutiques." },
    ],
    geoLat: 47.3769,
    geoLon: 8.5417,
    faq: [
      { q: "What group experiences are available in Zurich?", a: "TicketMatch.ai provides access to 2,400+ experiences: lake cruises, chocolate workshops, Jungfraujoch day trips, old town tours, and more — all at exclusive B2B group rates." },
      { q: "Can I book Jungfraujoch trips from Zurich?", a: "Yes. The 'Top of Europe' is a spectacular day trip from Zurich. TicketMatch.ai offers group packages with scenic train, Sphinx terrace, Ice Palace, and combined mountain experiences at B2B rates." },
      { q: "What chocolate experiences are available?", a: "Switzerland is the world's chocolate capital. TicketMatch.ai offers group Lindt Home of Chocolate visits, praline workshops, chocolate-making classes, and old town chocolate walks at B2B rates." },
      { q: "Is Zurich good for group travel?", a: "Excellent. Zurich has Europe's best public transport, is compact and walkable, and is the gateway to the Swiss Alps. TicketMatch.ai helps plan combined city + mountain group itineraries." },
    ],
  },
  {
    slug: "lucerne",
    name: "Lucerne",
    province: "Lucerne",
    country: "Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
    experiences: "1,800+",
    categories: 9,
    viatorDestId: 899,
    tagline: "Switzerland's picture-perfect gem — Chapel Bridge, lake & Alpine peaks",
    description:
      "Lucerne is Switzerland at its most magical — a medieval city on the shores of Lake Lucerne surrounded by dramatic Alpine peaks. With the iconic Chapel Bridge, Lion Monument, and easy access to Mt. Pilatus and Mt. Rigi, TicketMatch.ai provides B2B access to 1,800+ group experiences at exclusive rates.",
    highlights: [
      "Chapel Bridge (Kapellbrücke) — Europe's oldest covered wooden bridge (1333) with 17th-century paintings",
      "Lion Monument — Mark Twain called it 'the most mournful and moving piece of stone in the world'",
      "Lake Lucerne — Stunning Alpine lake surrounded by peaks, perfect for steamboat cruises",
      "Mt. Pilatus — The legendary dragon mountain (2,132m) accessible by the world's steepest cogwheel railway",
      "Old Town — Medieval painted facades, cobblestone squares, and the Musegg Wall with 9 watchtowers",
      "Mt. Rigi — The 'Queen of the Mountains' with panoramic views of the Alps and 13 lakes",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Chapel Bridge walks, old town tours, lake cruises, William Tell Express, and panoramic photography tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "Mt. Pilatus (Golden Round Trip), Mt. Rigi, Mt. Titlis, Jungfraujoch, Interlaken, and Engelberg." },
      { slug: "river-cruises", name: "Lake Cruises", icon: "\u{1F6A2}", count: "25+", description: "Historic paddle steamer cruises, sunset boats, dinner cruises, and combined lake + mountain packages." },
      { slug: "outdoor", name: "Outdoor & Alps", icon: "\u{1F3D4}\u{FE0F}", count: "40+", description: "Mt. Pilatus cogwheel railway, Mt. Rigi cable car, Alpine hiking, paragliding, and lake swimming." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "Chapel Bridge, Lion Monument, Musegg Wall, Swiss Museum of Transport, and Glacier Garden." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "15+", description: "Swiss Museum of Transport, Richard Wagner Museum, Rosengart Collection (Picasso), and Glacier Garden." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "20+", description: "Swiss fondue evenings, chocolate tastings, lakeside dining, and Alpine cheese experiences." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "10+", description: "KKL Culture & Convention Centre, Rosengart Collection, carnival traditions, and Swiss folklore evenings." },
      { slug: "winter-sports", name: "Winter Sports", icon: "\u{26F7}\u{FE0F}", count: "10+", description: "Mt. Titlis glacier, Engelberg skiing, tobogganing, and winter lake cruises." },
    ],
    geoLat: 47.0502,
    geoLon: 8.3093,
    faq: [
      { q: "What group experiences are available in Lucerne?", a: "TicketMatch.ai provides access to 1,800+ experiences: Chapel Bridge tours, Mt. Pilatus, lake steamboat cruises, fondue evenings, and more — all at exclusive B2B group rates." },
      { q: "What is the Mt. Pilatus Golden Round Trip?", a: "A spectacular circular journey: boat across Lake Lucerne, world's steepest cogwheel railway up Pilatus, cable car and gondola down. TicketMatch.ai offers group packages at B2B rates." },
      { q: "Can groups take steamboat cruises on Lake Lucerne?", a: "Yes. Lake Lucerne has a fleet of historic paddle steamers. TicketMatch.ai offers group cruises, dinner boats, and combined lake + mountain packages at B2B rates." },
      { q: "Is Lucerne good for group travel?", a: "Perfect. Lucerne is compact, scenic, and the ideal base for Swiss Alpine experiences. TicketMatch.ai helps plan combined Lucerne + mountain group itineraries." },
    ],
  },
  {
    slug: "interlaken",
    name: "Interlaken",
    province: "Bern",
    country: "Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
    experiences: "1,200+",
    categories: 8,
    viatorDestId: 5122,
    tagline: "Adventure capital of Switzerland — between two lakes, beneath the Jungfrau",
    description:
      "Interlaken sits dramatically between Lake Thun and Lake Brienz in the shadow of the Eiger, Mönch, and Jungfrau peaks. As Switzerland's adventure capital and gateway to Jungfraujoch, TicketMatch.ai provides B2B access to 1,200+ group experiences at exclusive rates.",
    highlights: [
      "Jungfraujoch — 'Top of Europe' at 3,454m with Sphinx terrace, Ice Palace, and Aletsch Glacier views",
      "Harder Kulm — The panoramic viewpoint (1,322m) above Interlaken with a glass viewing platform",
      "Lake Thun — Beautiful Alpine lake with castle-dotted shoreline and steamboat cruises",
      "Lake Brienz — Crystal-clear turquoise lake with Giessbach Falls and traditional Swiss villages",
      "Schilthorn — Revolving restaurant Piz Gloria (James Bond filming location) at 2,970m",
      "Trümmelbach Falls — Ten glacier waterfalls inside a mountain, the only accessible underground falls in Europe",
    ],
    topCategories: [
      { slug: "outdoor", name: "Outdoor & Adventure", icon: "\u{1F3D4}\u{FE0F}", count: "80+", description: "Paragliding, skydiving, bungee jumping, canyoning, white-water rafting, and Alpine hiking." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "60+", description: "Jungfraujoch, Schilthorn, Grindelwald First, Lauterbrunnen Valley, and Trümmelbach Falls." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "50+", description: "Harder Kulm panorama, Lauterbrunnen Valley, scenic train rides, and helicopter tours." },
      { slug: "river-cruises", name: "Lake Cruises", icon: "\u{1F6A2}", count: "20+", description: "Lake Thun steamboat, Lake Brienz cruises, Giessbach Falls boat, and sunset lake tours." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "15+", description: "Mountain hut fondue, chocolate workshops, Alpine cheese-making, and lakeside dining." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "15+", description: "Jungfraujoch, Harder Kulm, Schilthorn Piz Gloria, St. Beatus Caves, and Mystery Park." },
      { slug: "winter-sports", name: "Winter Sports", icon: "\u{26F7}\u{FE0F}", count: "20+", description: "Jungfrau ski region, Grindelwald slopes, snowshoeing, sledding, and ice climbing." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "5+", description: "Traditional Swiss folk evenings, alphorn workshops, and wood-carving demonstrations in Brienz." },
    ],
    geoLat: 46.6863,
    geoLon: 7.8632,
    faq: [
      { q: "What group experiences are available in Interlaken?", a: "TicketMatch.ai provides access to 1,200+ experiences: Jungfraujoch, paragliding, lake cruises, canyoning, and more — all at exclusive B2B group rates." },
      { q: "How do groups visit Jungfraujoch?", a: "The 'Top of Europe' is reached by scenic cogwheel train from Interlaken via Grindelwald or Lauterbrunnen. TicketMatch.ai offers group packages with reserved seats and combined mountain experiences at B2B rates." },
      { q: "What adventure activities are available for groups?", a: "Interlaken is Europe's adventure capital: paragliding, skydiving, bungee jumping, canyoning, rafting, and more. TicketMatch.ai offers group adventure packages at B2B rates with safety certified operators." },
      { q: "Is Interlaken good for group travel?", a: "Outstanding. Interlaken is the perfect Alpine base with two lakes, three iconic peaks (Eiger, Mönch, Jungfrau), and excellent rail connections. TicketMatch.ai helps plan multi-day Swiss Alps group itineraries." },
    ],
  },
  {
    slug: "geneva",
    name: "Geneva",
    province: "Geneva",
    country: "Switzerland",
    flag: "\u{1F1E8}\u{1F1ED}",
    experiences: "1,600+",
    categories: 9,
    viatorDestId: 900,
    tagline: "International city of peace — Lake Geneva, CERN & Mont Blanc views",
    description:
      "Geneva is the world's most international city — home to the UN, Red Cross, CERN, and the iconic Jet d'Eau on Lake Geneva with Mont Blanc as its backdrop. TicketMatch.ai provides B2B access to 1,600+ group experiences at exclusive rates.",
    highlights: [
      "Jet d'Eau — Geneva's iconic 140-meter water fountain on Lake Geneva, visible from across the city",
      "Lake Geneva (Lac Léman) — Europe's largest Alpine lake shared with France, with boat cruises and beaches",
      "CERN — The world's largest particle physics laboratory where the Higgs boson was discovered",
      "Old Town — Geneva's hilltop medieval quarter with St. Pierre Cathedral and winding alleys",
      "Palais des Nations — The European headquarters of the United Nations, open for guided tours",
      "Patek Philippe Museum — Five centuries of watchmaking history from Geneva's most prestigious brand",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Old town walks, UN Palais des Nations tours, CERN visits, lakefront promenades, and watchmaking tours." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "70+", description: "Chamonix & Mont Blanc, Montreux & Chillon Castle, Lausanne, Annecy (France), and Gruyères cheese village." },
      { slug: "river-cruises", name: "Lake Cruises", icon: "\u{1F6A2}", count: "20+", description: "Lake Geneva boat tours, Belle Époque paddle steamers, dinner cruises, and Montreux ferry." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "30+", description: "Jet d'Eau, CERN, Palais des Nations, Flower Clock, Reformation Wall, and Ariana Museum." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "30+", description: "Swiss fondue experiences, chocolate workshops, lakeside dining, wine tastings, and market tours." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "25+", description: "Patek Philippe Museum, CERN exhibitions, Red Cross Museum, Art & History Museum, and Ariana ceramics." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "20+", description: "Lake Geneva swimming, Mont Salève cable car, jet skiing, paddleboarding, and lakefront cycling." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "15+", description: "Grand Théâtre opera, Reformation history tours, international diplomacy tours, and watchmaking workshops." },
      { slug: "shopping", name: "Shopping", icon: "\u{1F6CD}\u{FE0F}", count: "10+", description: "Swiss watch boutiques, Rue du Rhône luxury shopping, Carouge artisan village, and Plainpalais flea market." },
    ],
    geoLat: 46.2044,
    geoLon: 6.1432,
    faq: [
      { q: "What group experiences are available in Geneva?", a: "TicketMatch.ai provides access to 1,600+ experiences: Lake Geneva cruises, CERN visits, Chamonix day trips, UN tours, chocolate workshops, and more — all at exclusive B2B group rates." },
      { q: "Can groups visit CERN?", a: "Yes. CERN offers group tours of its exhibitions and facilities including the ATLAS experiment. TicketMatch.ai helps book group visits at B2B rates — advance booking essential." },
      { q: "Can I book Chamonix & Mont Blanc day trips?", a: "Yes. Chamonix is just 1 hour from Geneva. TicketMatch.ai offers group excursions including Aiguille du Midi cable car (3,842m), Mer de Glace glacier, and Mont Blanc panoramas at B2B rates." },
      { q: "Is Geneva good for group travel?", a: "Excellent. Geneva is compact, multilingual (French/English), has excellent transport, and is gateway to the Alps and French Riviera. TicketMatch.ai helps plan Swiss + French Alps group itineraries." },
    ],
  },
];
