import type { CityData } from "./cities-data";

export const thaiCities: CityData[] = [
  {
    slug: "bangkok",
    name: "Bangkok",
    province: "Bangkok",
    country: "Thailand",
    flag: "🇹🇭",
    experiences: "450+",
    categories: 8,
    viatorDestId: 343,
    tagline: "City of Angels — golden temples, floating markets, and electric nightlife",
    description:
      "Bangkok is a dazzling metropolis where ancient temples glitter alongside futuristic skyscrapers and street-food smoke fills the air. From the opulent Grand Palace to the serene canals of Thonburi, TicketMatch.ai provides B2B access to 450+ group experiences at exclusive rates.",
    highlights: [
      "Grand Palace — The dazzling royal complex housing the sacred Emerald Buddha and 200 years of Thai regal history",
      "Wat Pho (Reclining Buddha) — Home to the magnificent 46-metre gilded reclining Buddha and Thailand's oldest massage school",
      "Wat Arun (Temple of Dawn) — Iconic riverside spire encrusted with colourful porcelain and seashell mosaics",
      "Chatuchak Weekend Market — One of the world's largest outdoor markets with 15,000+ stalls across 35 acres",
      "Chao Phraya River — Bangkok's lifeline offering scenic long-tail boat tours past temples, palaces, and stilted houses",
      "Khao San Road — The legendary backpacker strip buzzing with street food carts, live music, and vibrant nightlife",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "80+", description: "Guided temple tours, tuk-tuk city rides, Chinatown walks, and canal boat excursions through historic Bangkok." },
      { slug: "attractions", name: "Attractions", icon: "🎠", count: "60+", description: "Grand Palace, Wat Pho, Wat Arun, Jim Thompson House, Erawan Shrine, and Mahanakhon SkyWalk." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "70+", description: "Street food crawls, Thai cooking classes, floating market tastings, rooftop dining, and craft cocktail tours." },
      { slug: "river-cruises", name: "River Cruises", icon: "🚢", count: "50+", description: "Chao Phraya dinner cruises, long-tail canal tours, rice barge excursions, and sunset cocktail sailings." },
      { slug: "nightlife", name: "Nightlife", icon: "🌃", count: "40+", description: "Rooftop bar hopping, Muay Thai ringside evenings, cabaret shows, and night market walking tours." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "55+", description: "Ayutthaya ancient ruins, Damnoen Saduak floating market, Kanchanaburi Bridge, and Maeklong railway market." },
    ],
    geoLat: 13.7563,
    geoLon: 100.5018,
    faq: [
      { q: "What group experiences are available in Bangkok?", a: "TicketMatch.ai provides access to 450+ experiences: Grand Palace and temple tours, Chao Phraya dinner cruises, Thai cooking classes, floating market excursions, and Muay Thai events — all at exclusive B2B group rates." },
      { q: "Can I book river cruise experiences for groups?", a: "Yes. TicketMatch.ai offers group Chao Phraya cruises including dinner sailings, long-tail canal tours, and sunset cocktail cruises — all at competitive B2B rates." },
      { q: "Are day trips to Ayutthaya available for groups?", a: "Absolutely. TicketMatch.ai provides group day trips to the UNESCO-listed Ayutthaya ruins, floating markets, and the Bridge over the River Kwai at B2B rates." },
      { q: "Is Bangkok suitable for large group travel?", a: "Yes. Bangkok has excellent infrastructure for groups of all sizes with dedicated tour operators, spacious venues, and efficient transport. TicketMatch.ai's B2B platform streamlines booking and offers group-optimised pricing." },
    ],
  },
  {
    slug: "phuket",
    name: "Phuket",
    province: "Phuket",
    country: "Thailand",
    flag: "🇹🇭",
    experiences: "2,700+",
    categories: 8,
    viatorDestId: 349,
    tagline: "Pearl of the Andaman — turquoise waters, limestone cliffs, and island-hopping paradise",
    description:
      "Phuket is Thailand's largest island, fringed by powder-white beaches and towering karst formations rising from emerald seas. From the iconic Phi Phi Islands to the cultural charm of Old Town, TicketMatch.ai provides B2B access to 2,700+ group experiences at exclusive rates.",
    highlights: [
      "Phi Phi Islands — Stunning archipelago of crystal lagoons, dramatic cliffs, and world-class snorkelling reachable by speedboat",
      "James Bond Island — The towering limestone needle made famous by The Man with the Golden Gun in spectacular Phang Nga Bay",
      "Big Buddha — The 45-metre white marble Nakkerd Hill statue offering panoramic views across the island and Andaman Sea",
      "Old Town — Charming Sino-Portuguese shophouses, vibrant street art, local cafés, and the Sunday walking market",
      "Phang Nga Bay — A breathtaking seascape of over 40 limestone karst islands, sea caves, and mangrove forests",
      "Patong Beach — Phuket's liveliest stretch of sand with water sports, beach clubs, and the famous Bangla Road nightlife",
    ],
    topCategories: [
      { slug: "boat-tours", name: "Boat Tours", icon: "⛵", count: "600+", description: "Island-hopping speedboats, Phi Phi snorkelling trips, Phang Nga Bay kayaking, and luxury catamaran cruises." },
      { slug: "water-sports", name: "Water Sports", icon: "🤿", count: "400+", description: "Scuba diving, snorkelling safaris, jet-ski tours, parasailing, and surfing lessons at Kata Beach." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "350+", description: "Old Town walking tours, Big Buddha visits, Wat Chalong temple tours, and panoramic viewpoint excursions." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "250+", description: "Thai cooking classes, seafood market tours, night market crawls, and beachfront dining experiences." },
      { slug: "adventure", name: "Adventure", icon: "🧗", count: "300+", description: "Zip-lining through jungle canopies, ATV off-road trails, elephant sanctuaries, and white-water rafting." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "500+", description: "Phi Phi Islands, Similan Islands diving, James Bond Island, Krabi and Railay Beach, and Khao Sok National Park." },
    ],
    geoLat: 7.8804,
    geoLon: 98.3923,
    faq: [
      { q: "What group experiences are available in Phuket?", a: "TicketMatch.ai provides access to 2,700+ experiences: Phi Phi island-hopping, Phang Nga Bay kayaking, scuba diving, Thai cooking classes, and elephant sanctuary visits — all at exclusive B2B group rates." },
      { q: "Can I book island-hopping tours for groups?", a: "Yes. TicketMatch.ai offers group speedboat and catamaran tours to the Phi Phi Islands, Similan Islands, James Bond Island, and Krabi — all at competitive B2B rates." },
      { q: "Are adventure activities available for groups?", a: "Absolutely. TicketMatch.ai provides group zip-lining, ATV tours, white-water rafting, and scuba diving excursions at B2B rates across Phuket." },
      { q: "Is Phuket suitable for large group travel?", a: "Yes. Phuket is a world-class destination for groups with large-capacity boats, dedicated tour operators, and excellent resort infrastructure. TicketMatch.ai's B2B platform streamlines group booking and pricing." },
    ],
  },
  {
    slug: "chiang-mai",
    name: "Chiang Mai",
    province: "Chiang Mai",
    country: "Thailand",
    flag: "🇹🇭",
    experiences: "500+",
    categories: 7,
    viatorDestId: 5267,
    tagline: "Rose of the North — misty mountains, ancient temples, and elephant sanctuaries",
    description:
      "Chiang Mai is northern Thailand's cultural jewel, encircled by ancient city walls and framed by forested mountains. From sacred hilltop temples to ethical elephant encounters, TicketMatch.ai provides B2B access to 500+ group experiences at exclusive rates.",
    highlights: [
      "Doi Suthep Temple — The sacred golden pagoda perched 1,000 metres above the city with sweeping valley panoramas",
      "Old City Temples — Over 30 historic temples within the ancient moat, including Wat Chedi Luang and Wat Phra Singh",
      "Elephant Sanctuaries — Ethical no-ride sanctuaries where groups can feed, bathe, and walk alongside rescued elephants",
      "Night Bazaar — A sprawling nightly market offering handicrafts, hill-tribe textiles, street food, and live entertainment",
      "Sticky Waterfall (Bua Tong) — A unique limestone cascade you can walk up barefoot, surrounded by lush jungle",
      "Thai Cooking Classes — Hands-on market-to-table experiences learning northern Thai dishes in open-air jungle kitchens",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "🚶", count: "100+", description: "Doi Suthep temple tours, Old City walking tours, hill-tribe village visits, and Royal Flora garden excursions." },
      { slug: "adventure", name: "Adventure", icon: "🧗", count: "80+", description: "Zip-lining, jungle trekking, white-water rafting, bamboo rafting, and waterfall hikes through the mountains." },
      { slug: "wildlife", name: "Wildlife & Nature", icon: "🐘", count: "70+", description: "Ethical elephant sanctuaries, butterfly gardens, Doi Inthanon National Park, and night safari experiences." },
      { slug: "food-drink", name: "Food & Drink", icon: "🍽️", count: "90+", description: "Thai cooking classes, khao soi tastings, night market food crawls, coffee plantation tours, and organic farm visits." },
      { slug: "culture", name: "Culture & Arts", icon: "🎭", count: "60+", description: "Monk chats, meditation retreats, traditional Thai massage courses, lantern-making workshops, and temple ceremonies." },
      { slug: "day-trips", name: "Day Trips", icon: "🚐", count: "75+", description: "Doi Inthanon summit, White Temple (Chiang Rai), Golden Triangle, Sticky Waterfall, and Pai mountain town." },
    ],
    geoLat: 18.7883,
    geoLon: 98.9853,
    faq: [
      { q: "What group experiences are available in Chiang Mai?", a: "TicketMatch.ai provides access to 500+ experiences: Doi Suthep temple visits, ethical elephant sanctuaries, Thai cooking classes, jungle trekking, and night market tours — all at exclusive B2B group rates." },
      { q: "Can I book elephant sanctuary visits for groups?", a: "Yes. TicketMatch.ai offers group elephant sanctuary experiences at ethical no-ride facilities where groups can feed, bathe, and walk with elephants — all at competitive B2B rates." },
      { q: "Are cooking classes available for groups?", a: "Absolutely. TicketMatch.ai provides group Thai cooking classes including market tours and hands-on cooking in open-air kitchens at B2B rates." },
      { q: "Is Chiang Mai suitable for large group travel?", a: "Yes. Chiang Mai is a popular group destination with experienced operators, spacious outdoor venues, and a relaxed pace. TicketMatch.ai's B2B platform makes group booking seamless with optimised pricing." },
    ],
  },
];
