import type { CityData } from "./cities-data";

export const ukCities: CityData[] = [
  {
    slug: "london",
    name: "London",
    province: "England",
    country: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    experiences: "9,200+",
    categories: 15,
    viatorDestId: 737,
    tagline: "The world's stage — royalty, culture & iconic landmarks",
    description:
      "London is one of the world's greatest cities — a global capital of culture, history, and entertainment. From Buckingham Palace and the Tower of London to the West End and Borough Market, TicketMatch.ai provides B2B access to 9,200+ group experiences at exclusive rates for tour operators, DMCs, and travel agencies.",
    highlights: [
      "Tower of London — 1,000-year-old royal fortress housing the Crown Jewels and Beefeater tours",
      "Buckingham Palace — The official residence of the British monarch with the famous Changing of the Guard",
      "British Museum — The world's first public museum with 8 million objects including the Rosetta Stone",
      "Westminster Abbey — Gothic coronation church of British monarchs for nearly 1,000 years",
      "Tower Bridge — London's iconic Victorian bascule bridge with glass-floor walkway and engine rooms",
      "The London Eye — 135-meter observation wheel with panoramic views over 55+ London landmarks",
      "St Paul's Cathedral — Sir Christopher Wren's Baroque masterpiece with the famous Whispering Gallery",
      "Houses of Parliament & Big Ben — The iconic seat of British democracy on the Thames",
    ],
    topCategories: [
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "300+", description: "British Museum, Natural History Museum, V&A, Tate Modern, National Gallery, Science Museum, and 250+ more at B2B group rates." },
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "500+", description: "Royal London walks, Harry Potter tours, Jack the Ripper, street art in Shoreditch, pub crawls, and open-top bus tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "200+", description: "Tower of London, London Eye, Madame Tussauds, The Shard, SEA LIFE, London Dungeon, and Warner Bros Studio Tour." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "180+", description: "Borough Market tours, afternoon tea experiences, gin tastings, East End food walks, and Thames dinner cruises." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "200+", description: "Stonehenge, Bath, Oxford, Cambridge, Cotswolds, Windsor Castle, and Canterbury Cathedral." },
      { slug: "river-cruises", name: "River Cruises", icon: "\u{1F6A2}", count: "60+", description: "Thames sightseeing cruises, dinner boats, speed boat rides, Greenwich river buses, and private charters." },
    ],
    geoLat: 51.5074,
    geoLon: -0.1278,
    faq: [
      { q: "What group experiences are available in London?", a: "TicketMatch.ai provides access to 9,200+ experiences: Tower of London, Warner Bros Harry Potter Studio, West End shows, Thames cruises, Stonehenge day trips, and more — all at exclusive B2B group rates." },
      { q: "How do I book group museum tickets in London?", a: "Many London museums offer free general admission, but TicketMatch.ai provides group access to special exhibitions, guided tours, and priority entry at the British Museum, Natural History Museum, V&A, and 250+ more." },
      { q: "Can I book Stonehenge day trips for groups?", a: "Yes. TicketMatch.ai offers group Stonehenge excursions: Stonehenge-only, combined Stonehenge + Bath, Stonehenge + Windsor + Oxford, and private tours at B2B rates." },
      { q: "What Harry Potter experiences are available?", a: "TicketMatch.ai offers group Warner Bros Studio Tour (Making of Harry Potter), Platform 9¾ visits, filming location walking tours, and Harry Potter-themed afternoon tea at B2B rates." },
      { q: "Is London suitable for large group travel?", a: "Absolutely. London has the world's best public transport (Tube, buses, river boats), thousands of group-ready venues, and multilingual guides. TicketMatch.ai's platform handles groups of any size." },
    ],
  },
  {
    slug: "edinburgh",
    name: "Edinburgh",
    province: "Scotland",
    country: "United Kingdom",
    flag: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
    experiences: "3,400+",
    categories: 11,
    viatorDestId: 738,
    tagline: "Scotland's historic capital — castles, whisky & the Royal Mile",
    description:
      "Edinburgh is one of Europe's most dramatic cities, where a medieval Old Town and elegant Georgian New Town sit beneath an ancient volcanic castle. With the world's largest arts festival, legendary whisky heritage, and Harry Potter connections, TicketMatch.ai provides B2B access to 3,400+ group experiences at exclusive rates.",
    highlights: [
      "Edinburgh Castle — Iconic fortress on Castle Rock dominating the city skyline for 900+ years",
      "Royal Mile — The historic mile-long street running from Edinburgh Castle to the Palace of Holyroodhouse",
      "Arthur's Seat — Ancient volcanic peak (251m) in the heart of the city with panoramic views",
      "Palace of Holyroodhouse — The official Scottish residence of the British monarch since the 16th century",
      "Scotch Whisky Experience — World-class whisky journey at the top of the Royal Mile",
      "Edinburgh Fringe — The world's largest arts festival every August with 3,000+ shows",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "200+", description: "Royal Mile walks, ghost tours, underground vaults, Harry Potter tours, literary Edinburgh, and open-top bus tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "70+", description: "Edinburgh Castle, Palace of Holyroodhouse, Camera Obscura, Dynamic Earth, and Royal Yacht Britannia." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "100+", description: "Scotch whisky tastings, gin distillery tours, Scottish food tours, haggis experiences, and afternoon tea." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "120+", description: "Scottish Highlands, Loch Ness, St Andrews, Stirling Castle, Isle of Skye, and Outlander filming locations." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "50+", description: "National Museum of Scotland, Scottish National Gallery, Museum of Edinburgh, Writers' Museum, and Surgeons' Hall." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "40+", description: "Fringe Festival venues, Scottish music sessions, ceilidh dancing, bagpipe experiences, and literary pub crawls." },
    ],
    geoLat: 55.9533,
    geoLon: -3.1883,
    faq: [
      { q: "What group experiences are available in Edinburgh?", a: "TicketMatch.ai provides access to 3,400+ experiences: Edinburgh Castle, whisky tastings, Highlands day trips, ghost tours, Loch Ness excursions, and more — all at exclusive B2B group rates." },
      { q: "Can I book Scottish Highlands trips for groups?", a: "Yes. TicketMatch.ai offers group Highlands excursions: Loch Ness, Glencoe, Isle of Skye (1-3 day tours), Stirling Castle, and Outlander filming locations at B2B rates." },
      { q: "What whisky experiences are available?", a: "Edinburgh is the gateway to Scotland's whisky regions. TicketMatch.ai offers Scotch Whisky Experience, distillery tours, tasting masterclasses, and whisky + food pairing dinners at B2B group rates." },
      { q: "Is Edinburgh good for group travel?", a: "Excellent. Edinburgh is compact, walkable, culturally rich, and is the gateway to the Scottish Highlands. TicketMatch.ai helps plan combined Edinburgh + Highlands group itineraries." },
    ],
  },
  {
    slug: "manchester",
    name: "Manchester",
    province: "England",
    country: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    experiences: "1,800+",
    categories: 9,
    viatorDestId: 5394,
    tagline: "The original industrial city — football, music & Northern soul",
    description:
      "Manchester is a powerhouse of culture, sport, and innovation — birthplace of the Industrial Revolution, home to two Premier League clubs, and the city that gave the world Oasis, The Smiths, and Joy Division. TicketMatch.ai provides B2B access to 1,800+ group experiences at exclusive rates.",
    highlights: [
      "Old Trafford — Theatre of Dreams, home of Manchester United with 74,000+ capacity stadium tours",
      "Etihad Stadium — Manchester City's home with behind-the-scenes tours and club museum",
      "Manchester Museum — Newly renovated university museum with dinosaurs, mummies, and natural history",
      "Northern Quarter — Manchester's creative heart with street art, indie shops, craft bars, and live music",
      "John Rylands Library — Stunning neo-Gothic library housing medieval manuscripts and rare books",
      "MediaCityUK — Home to BBC and ITV studios at Salford Quays with waterfront dining",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "100+", description: "Football stadium tours, Northern Quarter walks, Industrial Revolution history, music heritage tours, and canal walks." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "40+", description: "Old Trafford, Etihad Stadium, SEA LIFE, Legoland Discovery Centre, and The Crystal Maze Experience." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "60+", description: "Curry Mile tours, craft beer walks, afternoon tea, Northern Quarter food crawls, and gin tastings." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "40+", description: "Manchester Museum, Science & Industry Museum, Imperial War Museum North, People's History Museum, and Whitworth Gallery." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "80+", description: "Lake District, Peak District, Liverpool, York, Chester, and North Wales castles." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "30+", description: "Live music at Band on the Wall, Lowry Theatre, HOME arts centre, and Manchester music heritage walks." },
    ],
    geoLat: 53.4808,
    geoLon: -2.2426,
    faq: [
      { q: "What group experiences are available in Manchester?", a: "TicketMatch.ai provides access to 1,800+ experiences: Old Trafford and Etihad stadium tours, Northern Quarter walks, Lake District trips, and more — all at exclusive B2B group rates." },
      { q: "Can I book football stadium tours for groups?", a: "Yes. TicketMatch.ai offers group tours at both Old Trafford (Man United) and Etihad Stadium (Man City), including museum access and matchday experiences at B2B rates." },
      { q: "What day trips are available from Manchester?", a: "Lake District (1.5h), Peak District (1h), Liverpool (1h), York (1.5h), and Chester (1h) — all bookable as group excursions at B2B rates." },
      { q: "Is Manchester good for group travel?", a: "Very. Manchester has excellent transport links, vibrant nightlife, world-class sport, and is the gateway to the Lake District and Peak District. TicketMatch.ai helps plan Northern England itineraries." },
    ],
  },
  {
    slug: "liverpool",
    name: "Liverpool",
    province: "England",
    country: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    experiences: "1,400+",
    categories: 9,
    viatorDestId: 5395,
    tagline: "The Beatles' city — maritime heritage, football & cultural capital",
    description:
      "Liverpool is forever linked to The Beatles, but this UNESCO-recognized maritime city offers so much more — Premier League football, world-class museums, a revitalized waterfront, and a legendary nightlife scene. TicketMatch.ai provides B2B access to 1,400+ group experiences at exclusive rates.",
    highlights: [
      "The Beatles Story — The world's largest permanent Beatles exhibition at Albert Dock",
      "Anfield Stadium — Liverpool FC's legendary home, one of football's most iconic grounds",
      "Royal Albert Dock — UNESCO waterfront complex with museums, galleries, restaurants, and bars",
      "Liverpool Cathedral — Britain's largest cathedral and the world's fifth-largest church",
      "Cavern Club — The legendary venue where The Beatles performed 292 times in the early 1960s",
      "Tate Liverpool — The national gallery of modern art in the North, housed at Albert Dock",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "80+", description: "Beatles walking tours, Magical Mystery Tour bus, waterfront walks, maritime history, and street art tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "35+", description: "Beatles Story, Anfield Stadium, Cavern Club, Liverpool ONE, Radio City Tower, and Mersey Ferry." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "35+", description: "Beatles Story, Museum of Liverpool, Maritime Museum, Tate Liverpool, World Museum, and Walker Art Gallery." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "40+", description: "Bold Street food tours, gin distillery visits, afternoon tea, waterfront dining, and Liverpool pub history walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "50+", description: "Chester, North Wales, Lake District, Manchester, Snowdonia, and Beatles childhood homes." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "25+", description: "Cavern Club live music, Philharmonic Hall concerts, Royal Court Theatre, and street art in the Baltic Triangle." },
    ],
    geoLat: 53.4084,
    geoLon: -2.9916,
    faq: [
      { q: "What group experiences are available in Liverpool?", a: "TicketMatch.ai provides access to 1,400+ experiences: Beatles tours, Anfield stadium visits, Albert Dock museums, Mersey Ferry, and more — all at exclusive B2B group rates." },
      { q: "What Beatles experiences are available for groups?", a: "TicketMatch.ai offers Beatles Story museum, Magical Mystery Tour bus, Cavern Club, childhood homes tours, and walking tours covering all major Beatles sites at B2B group rates." },
      { q: "Can I book Anfield Stadium tours for groups?", a: "Yes. TicketMatch.ai offers group Anfield tours including museum, dressing rooms, the tunnel, and pitch-side access. Matchday hospitality packages also available at B2B rates." },
      { q: "Is Liverpool good for group travel?", a: "Excellent. Liverpool is compact, affordable, culturally rich, and has excellent rail connections. TicketMatch.ai helps plan combined Liverpool + Manchester group itineraries." },
    ],
  },
  {
    slug: "oxford",
    name: "Oxford",
    province: "England",
    country: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    experiences: "1,100+",
    categories: 8,
    viatorDestId: 5397,
    tagline: "The City of Dreaming Spires — 900 years of academic excellence",
    description:
      "Oxford is one of the world's most prestigious university cities, with 900 years of academic history, stunning medieval colleges, and connections to Harry Potter, Alice in Wonderland, and Tolkien. TicketMatch.ai provides B2B access to 1,100+ group experiences at exclusive rates.",
    highlights: [
      "Bodleian Library — One of the oldest libraries in Europe, a Harry Potter filming location",
      "Christ Church — The grandest Oxford college with its cathedral, Great Hall (Hogwarts inspiration), and meadow",
      "Radcliffe Camera — The iconic circular reading room, Oxford's most photographed building",
      "Ashmolean Museum — The world's first university museum, founded in 1683",
      "University Church of St Mary — 13th-century church with tower views over Oxford's dreaming spires",
      "Covered Market — Historic indoor market since 1774 with independent shops and food stalls",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "60+", description: "College walking tours, Harry Potter filming locations, Inspector Morse tours, punting on the Thames, and ghost tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "Christ Church, Bodleian Library, Radcliffe Camera, Sheldonian Theatre, and Oxford Castle." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "20+", description: "Ashmolean Museum, Pitt Rivers Museum, Natural History Museum, History of Science Museum, and Modern Art Oxford." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "30+", description: "Historic pub tours (Eagle and Child, Turf Tavern), afternoon tea in colleges, Covered Market food walks, and gin tastings." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "40+", description: "Blenheim Palace, Cotswolds villages, Stratford-upon-Avon, Bicester Village, and Thames river trips." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "15+", description: "Literary Oxford walks, Tolkien & C.S. Lewis tours, college choir concerts, and Shakespeare at the Playhouse." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "10+", description: "Punting on the Cherwell, Thames river walks, Port Meadow, and Cotswolds cycling." },
      { slug: "river-cruises", name: "River Cruises", icon: "\u{1F6A2}", count: "10+", description: "Punting tours, Thames river cruises, and private group boat hire." },
    ],
    geoLat: 51.7520,
    geoLon: -1.2577,
    faq: [
      { q: "What group experiences are available in Oxford?", a: "TicketMatch.ai provides access to 1,100+ experiences: college tours, Harry Potter locations, Bodleian Library, Blenheim Palace trips, punting, and more — all at exclusive B2B group rates." },
      { q: "Can I visit Oxford colleges with groups?", a: "Yes. TicketMatch.ai offers group tours of Christ Church (Great Hall / Hogwarts), Bodleian Library, New College, and more. College access varies by season — our platform handles availability at B2B rates." },
      { q: "What Harry Potter locations are in Oxford?", a: "Christ Church (Great Hall = Hogwarts), Bodleian Library (Hogwarts Library & Infirmary), New College (courtyard scene), and Divinity School. TicketMatch.ai offers guided group Harry Potter tours at B2B rates." },
      { q: "Is Oxford a good day trip for groups?", a: "Perfect. Oxford is 1 hour from London by train. TicketMatch.ai offers Oxford-only group tours and combined Oxford + Cotswolds or Oxford + Stratford-upon-Avon packages at B2B rates." },
    ],
  },
  {
    slug: "cambridge",
    name: "Cambridge",
    province: "England",
    country: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    experiences: "900+",
    categories: 7,
    viatorDestId: 5396,
    tagline: "Where Newton, Darwin & Hawking studied — punting & ancient colleges",
    description:
      "Cambridge is Oxford's illustrious rival — a stunning university city where Newton discovered gravity, Darwin studied, and Hawking revolutionized physics. With gorgeous medieval colleges along the River Cam, TicketMatch.ai provides B2B access to 900+ group experiences at exclusive rates.",
    highlights: [
      "King's College Chapel — The iconic masterpiece of late Gothic architecture with the world's largest fan vault",
      "The Backs — Beautiful college gardens and lawns along the River Cam, best seen by punt",
      "Fitzwilliam Museum — Cambridge's premier art museum with antiquities, paintings, and decorative arts",
      "Trinity College — Newton's college, the largest in Cambridge with the famous Wren Library",
      "Mathematical Bridge — The intriguing wooden bridge at Queens' College, allegedly designed without bolts",
      "Eagle Pub — Where Watson and Crick announced they had discovered the structure of DNA in 1953",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "50+", description: "College walking tours, punting on the Cam, science history tours, ghost tours, and cycling tours." },
      { slug: "river-cruises", name: "Punting", icon: "\u{1F6A2}", count: "20+", description: "Guided punt tours past the Backs, private punting hire, champagne punts, and group chauffeured punts." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "King's College Chapel, Trinity College, St John's College, Bridge of Sighs, and Round Church." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "15+", description: "Fitzwilliam Museum, Sedgwick Earth Sciences, Polar Museum, Whipple Science Museum, and Kettle's Yard." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "25+", description: "Historic pub tours (Eagle, Pickerel), afternoon tea in colleges, food market walks, and gin tastings." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "20+", description: "Ely Cathedral, Imperial War Museum Duxford, Anglesey Abbey, Newmarket horse racing, and Norfolk Broads." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "10+", description: "College choir evensong, Kettle's Yard modern art, ADC Theatre, and literary Cambridge walks." },
    ],
    geoLat: 52.2053,
    geoLon: 0.1218,
    faq: [
      { q: "What group experiences are available in Cambridge?", a: "TicketMatch.ai provides access to 900+ experiences: college tours, punting on the Cam, King's College Chapel, science heritage walks, and more — all at exclusive B2B group rates." },
      { q: "Can I book punting for groups?", a: "Yes. TicketMatch.ai offers group punt tours: guided punts past the Backs, private hire, champagne punts, and large group chauffeured options at B2B rates." },
      { q: "What makes Cambridge different from Oxford?", a: "Cambridge is known for science (Newton, Darwin, Hawking, DNA), punting on the Cam, and a more compact layout. TicketMatch.ai offers both cities as separate or combined group experiences." },
      { q: "Is Cambridge a good day trip for groups?", a: "Perfect. Cambridge is 50 minutes from London by train. TicketMatch.ai offers Cambridge-only and combined Cambridge + Oxford group packages at B2B rates." },
    ],
  },
  {
    slug: "bath",
    name: "Bath",
    province: "England",
    country: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    experiences: "800+",
    categories: 7,
    viatorDestId: 5398,
    tagline: "UNESCO Georgian gem — Roman baths, Jane Austen & the Royal Crescent",
    description:
      "Bath is one of England's most beautiful cities — a UNESCO World Heritage site famous for its Roman baths, Georgian architecture, and Jane Austen connections. With natural hot springs and the stunning Royal Crescent, TicketMatch.ai provides B2B access to 800+ group experiences at exclusive rates.",
    highlights: [
      "Roman Baths — Remarkably preserved 2,000-year-old bathing complex built around Britain's only hot spring",
      "Royal Crescent — Iconic sweeping crescent of 30 Georgian townhouses, Bath's most photographed landmark",
      "Bath Abbey — Stunning Perpendicular Gothic church in the heart of the city with fan vaulted ceiling",
      "Thermae Bath Spa — Modern spa using Bath's natural hot spring water with rooftop pool and city views",
      "Pulteney Bridge — One of only four bridges in the world with shops on both sides, inspired by Florence's Ponte Vecchio",
      "Jane Austen Centre — Celebrating Bath's most famous resident with Regency-era exhibits and tea room",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "50+", description: "Roman Baths tours, Georgian architecture walks, Jane Austen walks, ghost tours, and panoramic bus tours." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "20+", description: "Roman Baths, Thermae Bath Spa, Royal Crescent, Bath Abbey, Pulteney Bridge, and Prior Park." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "25+", description: "Bath bun tastings, afternoon tea at the Pump Room, gin distillery tours, and food market walks." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "40+", description: "Stonehenge, Cotswolds, Castle Combe, Lacock (Harry Potter), Wells Cathedral, and Glastonbury." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "15+", description: "Roman Baths Museum, Fashion Museum, Holburne Museum, Herschel Museum, and American Museum." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "10+", description: "River Avon walks, Skyline walking trail, Prior Park landscape garden, and Kennet & Avon Canal." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "10+", description: "Jane Austen Centre, Theatre Royal Bath, Victoria Art Gallery, and Regency-era costume experiences." },
    ],
    geoLat: 51.3811,
    geoLon: -2.3590,
    faq: [
      { q: "What group experiences are available in Bath?", a: "TicketMatch.ai provides access to 800+ experiences: Roman Baths, Thermae Spa, Stonehenge day trips, Jane Austen tours, Cotswolds excursions, and more — all at exclusive B2B group rates." },
      { q: "Can I combine Bath with Stonehenge for groups?", a: "Yes. Bath is the closest city to Stonehenge (40 min). TicketMatch.ai offers combined Stonehenge + Bath group day trips from London, and Stonehenge excursions from Bath at B2B rates." },
      { q: "What is the Thermae Bath Spa?", a: "Britain's only natural thermal spa, using the same hot spring water the Romans bathed in 2,000 years ago. TicketMatch.ai offers group spa packages including rooftop pool sessions at B2B rates." },
      { q: "Is Bath a good day trip for groups?", a: "Perfect. Bath is 1.5 hours from London by train. TicketMatch.ai offers Bath-only, Bath + Stonehenge, and Bath + Cotswolds group packages at B2B rates." },
    ],
  },
  {
    slug: "york",
    name: "York",
    province: "England",
    country: "United Kingdom",
    flag: "\u{1F1EC}\u{1F1E7}",
    experiences: "1,000+",
    categories: 8,
    viatorDestId: 5399,
    tagline: "Medieval walled city — Vikings, Gothic cathedral & the Shambles",
    description:
      "York is one of England's most historic cities, enclosed by medieval walls with a stunning Gothic cathedral, Viking heritage, and the Shambles (inspiration for Diagon Alley). TicketMatch.ai provides B2B access to 1,000+ group experiences at exclusive rates.",
    highlights: [
      "York Minster — Northern Europe's largest Gothic cathedral with medieval stained glass and tower views",
      "The Shambles — Medieval street said to have inspired Harry Potter's Diagon Alley",
      "JORVIK Viking Centre — Award-winning ride-through reconstruction of Viking-age York",
      "York City Walls — The longest medieval city walls in England at 3.4km, fully walkable",
      "National Railway Museum — The world's largest railway museum with iconic locomotives",
      "Clifford's Tower — The last remaining medieval castle tower with 360° city views",
    ],
    topCategories: [
      { slug: "tours", name: "Tours & Sightseeing", icon: "\u{1F6B6}", count: "60+", description: "Medieval walking tours, ghost walks, city wall walks, Roman York, Viking tours, and chocolate trail." },
      { slug: "attractions", name: "Attractions", icon: "\u{1F3A0}", count: "25+", description: "York Minster, JORVIK Viking Centre, York Dungeon, Clifford's Tower, and York's Chocolate Story." },
      { slug: "museums", name: "Museums", icon: "\u{1F3DB}\u{FE0F}", count: "20+", description: "National Railway Museum, Yorkshire Museum, Castle Museum, Fairfax House, and Barley Hall." },
      { slug: "food-drink", name: "Food & Drink", icon: "\u{1F37D}\u{FE0F}", count: "30+", description: "Chocolate tours (York = chocolate capital), afternoon tea, brewery visits, Shambles food walks, and gin tastings." },
      { slug: "day-trips", name: "Day Trips", icon: "\u{1F690}", count: "40+", description: "Yorkshire Dales, North York Moors, Whitby (Dracula), Castle Howard, Harrogate, and the Yorkshire coast." },
      { slug: "art-culture", name: "Art & Culture", icon: "\u{1F3A8}", count: "15+", description: "York Theatre Royal, medieval mystery plays, ghost tours, and Viking festival events." },
      { slug: "outdoor", name: "Outdoor", icon: "\u{1F33F}", count: "10+", description: "City wall walks, River Ouse cruises, Yorkshire Dales hiking, and riverside cycling." },
      { slug: "river-cruises", name: "River Cruises", icon: "\u{1F6A2}", count: "10+", description: "River Ouse sightseeing cruises, evening ghost boats, and lunch cruises." },
    ],
    geoLat: 53.9591,
    geoLon: -1.0815,
    faq: [
      { q: "What group experiences are available in York?", a: "TicketMatch.ai provides access to 1,000+ experiences: York Minster, JORVIK Viking Centre, ghost walks, chocolate tours, Yorkshire day trips, and more — all at exclusive B2B group rates." },
      { q: "What makes York special for groups?", a: "York has England's best-preserved medieval center, walkable city walls, world-class museums, and is the gateway to the Yorkshire Dales and Moors. TicketMatch.ai helps plan Yorkshire group itineraries." },
      { q: "Is the Shambles really Diagon Alley?", a: "J.K. Rowling has denied direct inspiration, but the resemblance is uncanny and the Shambles is now full of Potter-themed shops. TicketMatch.ai offers group walks including the Shambles at B2B rates." },
      { q: "Is York a good day trip for groups?", a: "Yes. York is 2 hours from London (direct train) and 1.5 hours from Edinburgh. TicketMatch.ai offers York-only and combined York + Yorkshire packages at B2B rates." },
    ],
  },
];
